### ISSUE TITLE
Rust binding : Unable to compile text.cpp with new max_width parameter for Text::Size()

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#1004]
## Description
Implementing the binding of the new max_width parameter for Text::Size() failed with following error : 
`
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp: In function ‘sk::vec2 sk::text_size_constrained_g(const C*, text_style_t, float)’:
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:214:35: error: ‘text_step_line_length’ was not declared in this scope
    214 |         float    largest_width  = text_step_line_length<C, char_decode_b_T>(curr, &line_remaining, &curr, style, true, max_width);
        |                                   ^~~~~~~~~~~~~~~~~~~~~
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:214:58: error: expected primary-expression before ‘,’ token
    214 |         float    largest_width  = text_step_line_length<C, char_decode_b_T>(curr, &line_remaining, &curr, style, true, max_width);
        |                                                          ^
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:216:59: error: expected primary-expression before ‘,’ token
    216 |                 float curr_width = text_step_line_length<C, char_decode_b_T>(curr, &line_remaining, &curr, style, true, max_width);
        |                                                           ^
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp: In function ‘sk::vec2 sk::text_char_at_g(const C*, text_style_t, int32_t, vec2*, text_fit_, text_align_, text_align_)’:
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:292:31: error: ‘text_step_height’ was not declared in this scope; did you mean ‘tex_get_height’?
    292 |         float   text_height = text_step_height<C, char_decode_b_T>(text, &text_length, step.style, step.wrap, step.bounds.x);
        |                               ^~~~~~~~~~~~~~~~
        |                               tex_get_height
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:292:49: error: expected primary-expression before ‘,’ token
    292 |         float   text_height = text_step_height<C, char_decode_b_T>(text, &text_length, step.style, step.wrap, step.bounds.x);
        |                                                 ^
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:313:17: error: ‘text_step_next_line’ was not declared in this scope
    313 |                 text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                 ^~~~~~~~~~~~~~~~~~~
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:313:38: error: expected primary-expression before ‘,’ token
    313 |                 text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                                      ^
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:322:25: error: ‘text_step_next_line’ was not declared in this scope
    322 |                         text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                         ^~~~~~~~~~~~~~~~~~~
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:322:46: error: expected primary-expression before ‘,’ token
    322 |                         text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                                              ^
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp: In instantiation of ‘sk::vec2 sk::text_char_at_g(const C*, text_style_t, int32_t, vec2*, text_fit_, text_align_, text_align_) [with C = char; bool (* char_decode_b_T)(const C*, const C**, char32_t*) = utf8_decode_fast_b; vec2 = vec2; text_style_t = unsigned int; int32_t = int; text_fit_ = text_fit_; text_align_ = text_align_]’:
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:333:216:   required from here
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:313:55: error: comparison between distinct pointer types ‘bool (*)(const char*, const char**, char32_t*)’ and ‘sk::vec2*’ lacks a cast [-fpermissive]
    313 |                 text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                                        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:322:63: error: comparison between distinct pointer types ‘bool (*)(const char*, const char**, char32_t*)’ and ‘sk::vec2*’ lacks a cast [-fpermissive]
    322 |                         text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                                                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp: In instantiation of ‘sk::vec2 sk::text_char_at_g(const C*, text_style_t, int32_t, vec2*, text_fit_, text_align_, text_align_) [with C = char16_t; bool (* char_decode_b_T)(const C*, const C**, char32_t*) = utf16_decode_fast_b; vec2 = vec2; text_style_t = unsigned int; int32_t = int; text_fit_ = text_fit_; text_align_ = text_align_]’:
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:334:216:   required from here
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:313:55: error: comparison between distinct pointer types ‘bool (*)(const char16_t*, const char16_t**, char32_t*)’ and ‘sk::vec2*’ lacks a cast [-fpermissive]
    313 |                 text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                                        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/mv/dvlt/abacaba/stereokit-rust/StereoKit/StereoKitC/systems/text.cpp:322:63: error: comparison between distinct pointer types ‘bool (*)(const char16_t*, const char16_t**, char32_t*)’ and ‘sk::vec2*’ lacks a cast [-fpermissive]
    322 |                         text_step_next_line<C, char_decode_b_T>(text, step.style, step.align, step.wrap, step.bounds.x, step.start.x, &step.line_remaining, &step.pos);
        |                                                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gmake[2]: *** [CMakeFiles/StereoKitC.dir/build.make:850 : CMakeFiles/StereoKitC.dir/StereoKitC/systems/text.cpp.o] Erreur 1
  gmake[2]: *** Attente des tâches non terminées....
  gmake[1]: *** [CMakeFiles/Makefile2:234 : CMakeFiles/StereoKitC.dir/all] Erreur 2
  gmake: *** [Makefile:136 : all] Erreur 2
  thread 'main' panicked at /home/mv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 2

`

## Platform / Environment
rust binding. Linux 24.04 gnome wayland

**Comment by mvvvv** [comment]
Android building does not have this problem.

**Comment by maluoi** [comment]
Woah, that's interesting! I wonder why the Actions didn't catch that in the PR 🙀 I'll dig into this!

**Comment by mvvvv** [comment]
It's fixed ! Thanks !
