### ISSUE TITLE
Key press event for the fallback keyboard

### ISSUE THREAD

**Issue by cwule** [StereoKit/StereoKit#1007]
Is there an on key press event for the fallback keyboard?
Currently in one of our input fields where the user specifies a file name, pressing enter creates a new line, which leads to "Invalid user input".
Instead it would be better if Enter confirms the current input and triggers an event.

**Comment by maluoi** [comment]
What version is this with? I've tweaked this a bit in recent versions.

Fallback keyboard layout and events are also now configurable as well! So if you want to tweak it a bit, that's possible too :) Though I would like to make sure the default is good either way.

**Comment by cwule** [comment]
We are version 0.3.10. Is it already configurable there?

**Comment by maluoi** [comment]
I still need to write up some better docs for it, but there's some samples and related info in a few spots:

Here's how to use it at top level:
https://github.com/StereoKit/StereoKit/blob/develop/Examples/StereoKitTest/Demos/DemoTextInput.cs#L65-L70

Here's some info about the format, this description may be a little different from the _actual_ format, but it should be very close.
https://github.com/StereoKit/StereoKit/blob/develop/StereoKitC/tools/virtual_keyboard.cpp#L411-L437

KeySend is basically the Unicode characters that the key submits, which surfaces in Input.TextConsume and the active UI.Input element, and KeyPress is the VK code (the integer value of the corresponding Key enumeration) that shows up in Input.Key.

And these are the default formats, I'd probably just copy these and tweak them as desired.
https://github.com/StereoKit/StereoKit/blob/develop/StereoKitC/tools/virtual_keyboard.cpp#L84-L121

**Comment by austinbhale** [comment]
Thanks Nick, the defaults are great! That \r commit is exactly what we needed here

**Comment by cwule** [comment]
Thanks, so you already solved it before we even realized :)

**Comment by maluoi** [comment]
Awesome, glad that worked out! :D
