### ISSUE TITLE
Closing an app crash when dropping assets.

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#1029]
## Description
Exiting an application crashes when dropping assets. In the screenshot it is on a sprite but if we remove the sprites it will be on a texture.
## Platform / Environment
rust binding. Linux 24.04 gnome wayland

![Capture d’écran du 2024-06-25 15-59-23](https://github.com/StereoKit/StereoKit/assets/810124/6445b6f4-8806-4244-9621-41ea9030c89e)

I wasted hours searching because I thought it was a multi-threading problem before testing my basic template which has the problem. A really painful bug.

**Comment by maluoi** [comment]
> Exiting an application crashes when dropping assets.

Could you give a few more details about this? Are you dropping assets after StereoKit has shut down, or is this just within the main stepping loop? I haven't seen this issue at all, how can I recreate this?

**Comment by mvvvv** [comment]
These are the rust drops that occur after the last line of code. So far they haven't caused any problems. And I don't have this error with the demo examples. But I understand what's the problem now.

**Comment by mvvvv** [comment]
Ok I removed sk_shutdown() from the Sk.drop() and the problem is solved. The sk_shutdown will have to be called after the loop. Rust should follow the order of variable creation during the Drop. But I use a Winit helper which drops Sk before everyone else.
