### ISSUE TITLE
incorrectly renders views when using WiVRn 

### ISSUE THREAD

**Issue by Schmarni-Dev** [StereoKit/StereoKit#1039]
## Description
The right eyes view is displayed on the left eye, the right eye is black. 
this only seems to happen on the dev branch i think
known bad commit: 7b81ad64

## Platform / Environment
Linux using the WiVRn runtime, does not happen with base Monado, gpu brand does not seem to matter

**Comment by maluoi** [comment]
Is this perhaps related to the MSAA changes in https://github.com/StereoKit/StereoKit/commit/5938e5446df3aa062e7dfc20c47b1ae1ed0cf6de? With MSAA, I switched to a double tall texture instead of an array texture for the primary swapchain, which would probably count as a big change here.

I'll see if I can get a wivrn setup here, haven't used that before.

**Comment by Schmarni-Dev** [comment]
yeah looks like that commit broke it, i'll raise the issue in the wivrn side

**Comment by SpookySkeletons** [comment]
@maluoi Heyo, I'm the lead community manager of LVRA, we have a lot of interest in fixing this issue for our WiVRn users.

https://lvra.gitlab.io/docs/community/

Would you be able to hookup with us here so we can help you with setup? We have an orchestrator, docs, and tips to get you going in very short order ideally.

**Comment by Schmarni-Dev** [comment]
it's an issue with wivrn not stereokit from what i can tell see Meumeu/WiVRn#89

**Comment by maluoi** [comment]
Was there a verdict on if this is just a double tall vs. double wide issue? I'm not particularly attached to the current double-tall orientation, I can switch that around if that's helpful.

**Comment by maluoi** [comment]
Double-wide is now part of /develop :)

**Comment by Schmarni-Dev** [comment]
This is fixed for now, i'll let you know when you can swap back to double height
