### ISSUE TITLE
Wireframe material not working on Quest 3

### ISSUE THREAD

**Issue by CanYouCatchMe01** [StereoKit/StereoKit#1040]
## Description
I'm having a material with `Wireframe = true` and the wireframe is not working when I'm running the program locally on my Quest 3. The object is fully solid. If I run my program on my PC with Link cable on Windows and in a Windows window the wireframe is working. I'm guessing this is some OpenGL related issue.

## Platform / Environment
The platform is Android on my Quest 3. It is C# a multi targeted project on version 0.3.9. My Quest 3 headset is on update v.66.

## Logs or exception details
I attached my output in output_wireframe.txt and my code in Program.txt
[output_wireframe.txt](https://github.com/user-attachments/files/16165385/output_wireframe.txt)
[Program.txt](https://github.com/user-attachments/files/16165379/Program.txt)

**Comment by maluoi** [comment]
Unfortunately, GLES (Android) doesn't support this particular feature :( This wireframe flag only works with DirectX, so Desktop only.

I've done wireframe shaders by "3 coloring" a mesh, and then using those colors to identify and discard the center of the triangle. `SV_Barycentrics` might be applicable here, but I'm uncertain if this is available in DX11 or GLES via transpilation, I don't think it is.
