### ISSUE TITLE
Kind of memory corruption with Android Log

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#1077]
## Description
Here is an Android Logcat 

```
32m08-20 16:21:47.274 23396 23423 I SK_StereoKit-rs: Initialization successful
32m08-20 16:21:47.274 23396 23423 I п��z   : <<< After init
33m08-20 16:21:47.274 23396 23423 W �{   : Go go go !!!
34m08-20 16:21:47.274 23396 23423 D �{   : ======================================================================================================================== !!
34m08-20 16:21:47.276 23396 23423 D �{   : sprite_create: Atlased sprites not implemented yet! All atlased sprites will be switched to single.
34m08-20 16:21:47.401 23396 23423 D         : "mobiles.gltf"
34m08-20 16:21:47.401 23396 23423 D         : "mobiles.gltf/mesh/0_0_Icosphere"
```
The Tag appears corrupted after sk_init() completes.

Above:
- line 1 is the last one written in sk_init().
- The following lines are written via the log_????() functions

SkSettings.AppName is StereoKit-rs, I don't really know why it adds SK_ as prefix

## Platform / Environment
rust binding. Linux 24.04 Meta Quest2 V68

## Logs or exception details
The complete log: https://github.com/mvvvv/StereoKit-rust/blob/master/examples/example_of_quest_log.txt

**Comment by maluoi** [comment]
Ohhh, I think I maybe know what this is! Thanks for pointing it out! Will probably have a fix for it today.

The new log tag is the app name, prefixed with SK_. Helps to identify it as from an SK app, but also distinguish between two different SK apps running at the same time.
