### ISSUE TITLE
P2P multiplayer issues with SK 0.3.10

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#1123]
## Description
As soon as you remove the headset the main step loop now pauses in openxr_step_end() and sleeps until it's put back on.
This breaks P2P multiplayer apps because the server will stop processing client data. In multiplayer apps we need to continue processing scripts to send / receive data and update scripts / states.

It's possible to move networking into another thread but that adds a lot of complexity regarding thread safety and means you can't use SK code such as Time.totalf which is not being updated.

It used to be up to the app to pause sound and decide what it should do depending on the headset status. It would be better if this functionality only executed if the developer flagged the app as being single player.

I also have a separate issue relating to single player mode where Meta Body Tracking sometimes breaks at the API level if you remove the headset and put it back on and I wonder if that is related to this issue too. My current workaround is to put up a message and get the user to reboot the headset. It may not be related but it definitely has the same root cause of removing the headset.

## Platform / Environment
0.3.10

Thanks.

**Comment by maluoi** [comment]
Hmm, okay! This makes plenty of sense to me, I'll add a flag to SKSettings to turn this behavior on or off. Probably default to off for v0.3, but default to on for v0.4. I assume this was v0.3.10-preview.2+?

**Comment by Jumbli** [comment]
I'm on 0.3.10-preview-1,  I didn't realise more releases had come out for 3.10 :)

**Comment by maluoi** [comment]
v0.3.10-preview.4 is up and has a new setting for you :)
https://github.com/StereoKit/StereoKit/pull/1124

**Comment by Jumbli** [comment]
That's much better thanks. My multiplayer sessions are now much more stable :) Thanks for the quick turnaround too,
