### ISSUE TITLE
xmake to cmake

### ISSUE THREAD

**Issue by maluoi** [StereoKit/StereoKit#160]
xmake is great and I love working with it, but it seems like cmake is going to work better for other people, especially as a dependency. StereoKit's build system is complicated, considering Android/Linux/Windows/UWP/x64/ARM64, so it may take some time to figure out all of that, but lets put it down on the roadmap here!

**Comment by waruqi** [comment]
You can `xmake project -k cmake` to generate cmakelists.txt

and use `add_rules("utils.install.cmake_importfiles")` + `xmake install` to generate .cmake import files and libraries for other cmake users.

**Comment by maluoi** [comment]
Haha, and this is why I like xmake! Thanks for pointing that out, I will definitely give that a spin!
