### ISSUE TITLE
Sample application isn't running within SteamVR/OpenXR on Ubuntu 20.04

### ISSUE THREAD

**Issue by JoshuaBehrens** [StereoKit/StereoKit#178]
Hey, I'd like to test out this framework. Running Ubuntu 20.04, got a valve index connected, installed dotnet core, created a project in Rider, added NuGet dependency to StereoKit.

I follow the sample snippet from the guide:
```cs
using System;
using StereoKit;

namespace StereoKitExamples
{
    class Program
    {
        static void Main(string[] args)
        {
            if (!SK.Initialize(new SKSettings{ appName = "Project" }))
                Environment.Exit(1);

            Model cube = Model.FromMesh(
                Mesh.GenerateRoundedCube(Vec3.One, 0.2f),
                Default.Material);

            while (SK.Step(() =>
            {
                cube.Draw(Matrix.TS(Vec3.Zero, 0.1f));
            }));

            SK.Shutdown();
        }
    }
}
```

When I do not start the OpenXR server I get a fallback window where my mouse is a hand.

```
[SK diagnostic] Initializing StereoKit v0.3.2...
[SK diagnostic] sk_gpu: Using OpenGL
[SK diagnostic] sk_gpu: 4.5.0 NVIDIA 460.91.03
[SK diagnostic] Starting mixed reality mode
[SK diagnostic] available: XR_KHR_vulkan_enable
[SK diagnostic] available: XR_KHR_vulkan_enable2
[SK diagnostic] available: XR_VALVE_analog_threshold
[SK diagnostic] available: XR_EXT_hand_joints_motion_range
[SK diagnostic] available: XR_KHR_visibility_mask
[SK diagnostic] available: XR_EXT_debug_utils
[SK diagnostic] REQUESTED: XR_KHR_opengl_enable
[SK diagnostic] REQUESTED: XR_EXT_hand_tracking
[SK diagnostic] REQUESTED: XR_EXT_hp_mixed_reality_controller
[SK diagnostic] REQUESTED: XR_KHR_composition_layer_depth
[SK diagnostic] Using system: SteamVR/OpenXR : lighthouse
[SK diagnostic] OpenXR articulated hands ext enabled!
[SK diagnostic] OpenXR depth LSR ext enabled!
[SK diagnostic] Creating view: PrimaryStereo color:rgba32_sRGB depth:depth16 blend:Opaque
[SK diagnostic] Setting view: PrimaryStereo to 3188x3540
[SK info] xrCreateSwapchain failed [XR_ERROR_FEATURE_UNSUPPORTED]
[SK error] Couldn't create OpenXR view swapchains!
[SK info] MixedReality display mode failed, falling back to Flatscreen
[SK diagnostic] Starting flatscreen mode
[SK diagnostic] audio: Using backend PulseAudio
[SK info] Initialization successful
```

When I start the SteamVR so it starts the OpenXR server behind the scenes I get a black window, a blink of an info within SteamVR that Project is launching, right after that it is switching back to Home and just this output:

```
[SK diagnostic] Initializing StereoKit v0.3.2...
[SK diagnostic] sk_gpu: Using OpenGL
[SK diagnostic] sk_gpu: 4.5.0 NVIDIA 460.91.03
[SK diagnostic] Starting mixed reality mode
[SK diagnostic] available: XR_KHR_vulkan_enable
[SK diagnostic] available: XR_KHR_vulkan_enable2
[SK diagnostic] available: XR_VALVE_analog_threshold
[SK diagnostic] available: XR_EXT_hand_joints_motion_range
[SK diagnostic] available: XR_KHR_visibility_mask
[SK diagnostic] available: XR_EXT_debug_utils
[SK diagnostic] REQUESTED: XR_KHR_opengl_enable
[SK diagnostic] REQUESTED: XR_EXT_hand_tracking
[SK diagnostic] REQUESTED: XR_EXT_hp_mixed_reality_controller
[SK diagnostic] REQUESTED: XR_KHR_composition_layer_depth
[SK diagnostic] Using system: SteamVR/OpenXR : lighthouse
[SK diagnostic] OpenXR articulated hands ext enabled!
[SK diagnostic] OpenXR depth LSR ext enabled!
```

Debugging into it eventually ends up at waiting for sk_init.

Any infos I can collect further to know what might be broken here? Monado examples are working and can connect to the OpenXR server so I thought StereoKit can do this too.

**Comment by maluoi** [comment]
There is an outstanding bug with SteamVR where it doesn't support array textures as swapchain targets! That's the `xrCreateSwapchain failed [XR_ERROR_FEATURE_UNSUPPORTED]` you're seeing. I should probably just turn off single pass rendering for SteamVR+Linux. Right now, StereoKit only falls back to single pass if the GPU doesn't support the feature (which in this case it does). Adding a platform check is not my favorite hack though, and I've kinda been hoping they'll just fix the issue at some point.

I'll bump this on my todo list. Most of the Linux users so far have been working on Monado, otherwise I'd have gotten to it sooner!

**Comment by JoshuaBehrens** [comment]
Great to hear that this is a known issue. Means less further debugging :) . I am willing to test for you when there is a patch to build. Can I fake the feature detection or switch to another GPU? I still have some old cards that might not support that.

Thank you for the forum post reference. Will subscribe!

**Comment by JoshuaBehrens** [comment]
But wait. The SteamVR post refers to the C# bindings. When I just use the native library things work out? Or is this just a false assumption?

**Comment by maluoi** [comment]
Ah, I'm not 100% sure about what the mention of C# vs native is in this case! I wouldn't really expect the native side to behave any better here. It's possible there was some confusion related to testing some other native OpenXR sample that wasn't using array textures, and StereoKit/C# which does. Many sample/reference OpenXR projects don't do single pass rendering for the sake of simplicity.

**Comment by maluoi** [comment]
@JoshuaBehrens Okay, I pushed up a preview build with the hack-ey fix, you should be able to use that with the v0.3.3-preview.1 NuGet package! I have _not_ tested this particular situation directly yet, swapping over to SteamVR/Linux is a non-trivial setup for me, but the code path triggers when I 'simulated' it :)

You should see the console log a warning, `SteamVR+Linux disable single pass rendering hack. To be removed when SteamVR bug is fixed.` if this is triggering properly. Let me know if it behaves better!

I also poked someone I know on the SteamVR team, so hopefully they'll take another peek at it in the near future :)

**Comment by JoshuaBehrens** [comment]
Hey @maluoi sorry for the not-so-fast reply (compared to your fix). Thank you very much for the response and "alpha" to try. I can confirm that I get that log message now. So your simulation worked out correctly. I still can't get the sample working.

Current scenario. I start SteamVR. First app that starts is Home. I click start in Rider. This is the output I get.

```
[SK diagnostic] Initializing StereoKit v0.3.3-preview1...
[SK diagnostic] sk_gpu: Using OpenGL
[SK diagnostic] sk_gpu: 4.5.0 NVIDIA 460.91.03
[SK diagnostic] Starting mixed reality mode
[SK diagnostic] available: XR_KHR_vulkan_enable
[SK diagnostic] available: XR_KHR_vulkan_enable2
[SK diagnostic] available: XR_VALVE_analog_threshold
[SK diagnostic] available: XR_EXT_hand_joints_motion_range
[SK diagnostic] available: XR_KHR_visibility_mask
[SK diagnostic] available: XR_EXT_debug_utils
[SK diagnostic] REQUESTED: XR_KHR_opengl_enable
[SK diagnostic] REQUESTED: XR_EXT_hand_tracking
[SK diagnostic] REQUESTED: XR_EXT_hp_mixed_reality_controller
[SK diagnostic] REQUESTED: XR_KHR_composition_layer_depth
[SK diagnostic] Using system: SteamVR/OpenXR : lighthouse
[SK warning] SteamVR+Linux disable single pass rendering hack. To be removed when SteamVR bug is fixed.
[SK diagnostic] OpenXR articulated hands ext enabled!
[SK diagnostic] OpenXR depth LSR ext enabled!
[SK diagnostic] Creating view: PrimaryStereo color:rgba32_sRGB depth:depth16 blend:Opaque
[SK diagnostic] Setting view: PrimaryStereo to 3188x3540
[SK info] xrCreateSwapchain failed [XR_ERROR_FEATURE_UNSUPPORTED]
[SK error] Couldn't create OpenXR view swapchains!
[SK info] MixedReality display mode failed, falling back to Flatscreen
[SK diagnostic] Starting flatscreen mode
[SK diagnostic] audio: Using backend PulseAudio
[SK info] Initialization successful
```

Now I am again with the Flatscreen and a stuck OpenXR server, that tries to load Home again.

I noticed a modal from Source2 stating that I can run an app only once. I assume that is Home.

**Comment by maluoi** [comment]
Oh butts! Yeah, it looks like this didn't quite account for the issue properly. I forgot that even with my current two pass fallback, I still use array textures for the swapchain, I just set one layer as a target at a time! 🤦🏻 That... might have been why I never added this hack when I first discovered the issue, a working hack would require some larger changes to how I track swapchain surfaces 😬 

I'll have to think on this a bit more! I'll poke around in it on Monday, and maybe if I'm lucky I'll hear back from SteamVR people. Thanks for trying out the preview build, I really appreciate it!

**Comment by JoshuaBehrens** [comment]
Unlucky. Just feed me with more things to try and I will. When you need some debug data, I am willing to gdb into it :+1: 

I'd really like to know what that missing feature is. I mean what is missing on the setup? Is it a feature in SteamVRs implementation of the OpenXR standard? Is the GPU the issue? The GPU driver? The HMD?

**Comment by maluoi** [comment]
I believe the issue is specifically calling `xrCreateSwapchain` with an `XrSwapchainCreateInfo::arraySize > 1`? This would be a problem with SteamVR's implementation of the OpenXR runtime, and I believe is actually supposed to be a conformance issue. All conformant OpenXR runtimes should be supporting this particular scenario.

It's a little strange, because this code path _does_ work on their Windows implementation? (even on same machine) I want to say this same thing was a problem in their early iterations of OpenXR on Windows, and fixed pretty quickly, but that was a while ago now and I'm a little fuzzy on the specifics.

**Comment by JoshuaBehrens** [comment]
Sooo a wine steam would provide a different OpenXR server and should work? 💭

**Comment by maluoi** [comment]
Well there's an interesting thought! I don't know too much about Wine, but I'd expect that would use StereoKit's D3D11 backend instead of GL, so yeah, as long as Wine behaves well with VR in general, that could possibly work!

**Comment by JoshuaBehrens** [comment]
I guess I dive into it this night 😁

**Comment by JoshuaBehrens** [comment]
NGL. wine is wine again... Lutris preset for steam on wine is not very useful until you installed something.

Compiled latest monado (as 20.04 debs don't want to install), install, set XR JSON file and it seems to use monado instead but eventually I just see a lighthouse in the HMD, a blackscreen on the flatscreen and non issueing log messages :(

```
[SK diagnostic] Initializing StereoKit v0.3.3-preview1...
[SK diagnostic] sk_gpu: Using OpenGL
[SK diagnostic] sk_gpu: 4.5.0 NVIDIA 460.91.03
[SK diagnostic] Starting mixed reality mode
[SK diagnostic] available: XR_KHR_opengl_es_enable
[SK diagnostic] available: XR_KHR_vulkan_enable
[SK diagnostic] available: XR_KHR_vulkan_enable2
[SK diagnostic] available: XR_KHR_composition_layer_cylinder
[SK diagnostic] available: XR_KHR_composition_layer_equirect
[SK diagnostic] available: XR_KHR_composition_layer_equirect2
[SK diagnostic] available: XR_EXT_debug_utils
[SK diagnostic] available: XR_MND_headless
[SK diagnostic] available: XR_MND_swapchain_usage_input_attachment_bit
[SK diagnostic] REQUESTED: XR_KHR_convert_timespec_time
[SK diagnostic] REQUESTED: XR_KHR_opengl_enable
[SK diagnostic] REQUESTED: XR_KHR_composition_layer_depth
[SK diagnostic] REQUESTED: XR_EXTX_overlay
[SK diagnostic] REQUESTED: XR_MNDX_egl_enable
[SK diagnostic] REQUESTED: XR_EXT_hand_tracking
LOG in xrCreateInstance: Instance created
        createInfo->applicationInfo.applicationName: Project
        createInfo->applicationInfo.applicationVersion: 1
        createInfo->applicationInfo.engineName: StereoKit
        createInfo->applicationInfo.engineVersion: 12291
        appinfo.detected.engine.name: (null)
        appinfo.detected.engine.version: 0.0.0
        quirks.disable_vulkan_format_depth_stencil: false
[SK diagnostic] Using system: Monado: Valve Index (vive)
[SK diagnostic] OpenXR depth LSR ext enabled!
[SK diagnostic] Creating view: PrimaryStereo color:rgba32_sRGB depth:depth32 blend:Opaque
[SK diagnostic] Setting view: PrimaryStereo to 2016x2240
[SK diagnostic] Platform supports single-pass rendering
[SK diagnostic] audio: Using backend PulseAudio
[SK info] Initialization successful
[SK diagnostic] OpenXR session begin.
[SK diagnostic] Bounds updated: 0.00x0.00 at (-0.0,-1.6,-0.0) (-0.00,1.00,-0.00,0.00)
```

I still think SteamVR is the easiest to setup but I couldn't test it further.

**Comment by JoshuaBehrens** [comment]
Nevermind. I got it with the monado service although my hand acts weird but I assume some axis are just confused. So I can work without this being fixed for now but it doesn't seem to be a very good solution for now.

**Comment by maluoi** [comment]
SK uses double-wide in recent builds, array textures on Linux shouldn't be a problem anymore.

**Comment by JoshuaBehrens** [comment]
@maluoi well then I will give it a try again :)
