### ISSUE TITLE
Can't get stereokit to work on Win10 desktop/core

### ISSUE THREAD

**Issue by shawty** [StereoKit/StereoKit#191]
Hi, decided to try out stereokit, but I can't even get off the starting blocks.

Using latest build of VS2019 community preview, have tried using the pre-made template, and doing things by hand, tried on two PC's with 2 different versions of Win10 X64, I've also tried with dotnet command line and switched between 2.0, 3.1 and V5.0 of .NET and every time no matter what I get exactly the same as the following images show:

![image](https://user-images.githubusercontent.com/1876454/133511164-b8a4f9f8-3e59-44bb-9077-4a84061462e6.png)

![image](https://user-images.githubusercontent.com/1876454/133511192-6ed18d0b-6f5f-4fa0-872e-385905137462.png)

Far short of downloading the sources and building from scratch I cannot think of anything else to try.

VR Headset is Windows MR, the machine that's running the HMD is an i7 3.00Ghz 8 core with 16gb DDR3 Ram, the headset itself is a Lenovo Explorer with 2 windows ME BT4 motion controllers.  I have Steam & SteamVR installed, and have verified with other software that everything works correctly.  The LOVR VR Framework also works correctly ( But I don't want to use LUA ;-)   ) for self programmed apps and launches Steam/VR as needed, stereokit however doesn't even seem to get as far as checking the hardware.

The code used is the same code as is in the template downloaded from the VS gallery.

I'd really like to give StereoKit a go, because it looks much more straight forward than using Unity and Co, but not even being able to get the samples running is a bit of a bugger...

Shawty

**Comment by maluoi** [comment]
I think you're the second person to make note of an issue like this! And unfortunately, it's a little tricky to track down, as the logs don't quite produce enough detail for this particular crash. I can see it's getting to the audio system, but right now audio is one of the first systems to initialize after the platform.

I will have some additional logging going into the next build that'll help pin down which system is causing it, but I may still need to do another step or two after that. I'll try and get that build up today, I think.

This could be an issue related to older GPUs? Looking at the `Quadro K1100M`, it's a 2013 model. I've so far assumed that VR hardware trends to the newer side of things, so it's possible that I may be using a feature or two that older GPUs don't have. In particular, I may have something in the single pass rendering system I can look at that may be related here...

**Comment by maluoi** [comment]
It could be worth updating your graphics drivers if you haven't done that in a while?

**Comment by shawty** [comment]
Hi @maluoi ,

Drivers might be suspect, I can try as the drivers in the device that has my VR helmet attached, keeps popping up a message box from time to time, telling me that I'm using (I can't remember the exact words) a remote driver model that's no longer supported and I need to update.

I also had that on the larger PC too recently, so I downloaded and installed the game-ready drivers from NVidia which seemed to solve the issue, on the VR machine however I keep getting told that the drivers I have are the correct ones and Win10 keeps re-installing them.

That said, I do wonder if it's the nature of the machine.

Basically, It's a DELL M4800 Laptop I'm using for the VR as my main machine is installed with Windows 10 N edition, which won't run Windows MR.  Technically the spec of both machines is almost Identical, but as way of a quick test I took the hard drive out the laptop, put it in the main machine and booted off of it to test (That's how I know that I got the same error on both machines)

The main machine has an NVidia GTX 750 Ti in it....

Anyway... back to the laptop....

If you look at the specs for the laptop, it's actually one of these dual graphics things, it has intel graphics and the NVidia K1100M in, and with LOVR I actually had to add the run time to the specific GPU settings so that it ran on NVidia and not the intel card, which makes me wonder if there's something similar I need to do for StereoKit

LOVR was easy to fix, because the way that works is a simple exe runtime that you drop your project folder onto.

I'll try messing with the Gfx drivers on the Laptop see if that makes any difference, because I need to get it to stop moaning about remote fx or what ever it is anyway, if you want me to run any specific testing just let me know what I need to do... I'm having a little breather between contracts at the moment for a few weeks, so I have a little bit of time.

**Comment by shawty** [comment]
PS: As for the VR hardware, it actually seems to prefer the K1100M to the GTX 750 Ti, and I do suspect that's the older one of the two :-)   (Found that out testing games with steam)

**Comment by maluoi** [comment]
I had a problem a couple versions back related to multiple graphics cards, so SK does have some code to determine the "most capable" card on the system! ("Most capable" if I recall, is based on size of available GPU memory) Since it's definitely picking the K1100M over the Intel, I'd expect that part is probably doing fine :)

In the log "This platform does not support single pass rendering" is what really caught my eye! I haven't had an opportunity to test on a device that does that natively. There's probably more than just single-pass stuff missing! I'd kinda expect newer drivers would mitigate this part some.

Short of building from source, I unfortunately don't think I have any good recommendations for things to test. But I'll definitely poke this thread when I have a build with a little more logging in it!

**Comment by shawty** [comment]
Awesome.

As I say, I'll have a fart about with the drivers, see what that does.

I'll let you know if anything changes.

**Comment by maluoi** [comment]
Ok, cool! v0.3.3-preview.6 is available via NuGet now! If you could upload the log when using that at some point, I'd really appreciate it :)

**Comment by shawty** [comment]
@maluoi - Just checked the NuGet version I'm using, seems I'm already using one version above the P6 you mentioned.

![image](https://user-images.githubusercontent.com/1876454/134250928-51d9b00c-027b-4079-804c-b43a2672964a.png)

Is there something I should be doing to get a better log for you, or is the console window output all you need?

**Comment by maluoi** [comment]
I _just_ released v0.3.3 yesterday, so a log from that one will also work! I'm pretty sure the console window output should be fine in this case, but VS's debug output log contains the console window output plus some occasionally useful additional stuff. If you can grab me the VS output log, that'd probably be pretty great :)

**Comment by shawty** [comment]
ok will do, gimme 30 mins.. busy fighting with NVidia driver software!!!  what ever happened to the days of just right clicking on an ini file and selecting install...

Now it's all about registration, and socials, and giving up your soul... gahhhh

:-D

**Comment by maluoi** [comment]
Haha, I know how that goes! No rush, I'll still be around later too :)

**Comment by shawty** [comment]
11:30pm here in the UK... this things been sat "preparing" for almost an hour now, so I'm gonna give up on it and leave it until morning...

**Comment by shawty** [comment]
Ok, I FINALLY managed to get the laptop and all it's drivers and everything (inc Graphics) updated to the most recent versions possible...  it only took me 12 hours!!!

Anyway, attached to this post is a zip file containing the following:

VS 2019 Community solution I'm using for testing
A text file containing the debug window output in VS
A screen shot of the crash in VS
A screen shot of the test app console window.

For completeness, the LT I'm running on and it's specs:

![image](https://user-images.githubusercontent.com/1876454/134349737-2a89303f-9332-4c14-a9aa-5968903e4d5c.png)

![image](https://user-images.githubusercontent.com/1876454/134349874-ad338fd5-2512-4f83-aeee-bf378e2b17f8.png)

![image](https://user-images.githubusercontent.com/1876454/134349929-cf5e795b-e834-4283-97ba-ff2362df867b.png)

![image](https://user-images.githubusercontent.com/1876454/134349979-e42193c7-54f5-4178-9f64-f839438ab93c.png)

If you need anything else give me a shout. :-)

[sktest2.zip](https://github.com/maluoi/StereoKit/files/7210921/sktest2.zip)

**Comment by shawty** [comment]
Hi @maluoi ,

Saw your recent videos on Mixed Reality Days 2022 (Well done...) and I decided to have another go at this (I had to leave it alone previously, due to other work commitments).

Anyway, 1 year later, I decided to give this another go.

and the story unfortunately is still the same for me, but there have been some changes.

Firstly, I've tried this more up to date test in a "Flatscreen" environment.  IE: Not the laptop I was running the VR headset off, previously.

I figured if I could get even just the hello world version running flatscreen, then I might at least have something to try on the VR headset (Which if you recall was a Lenovo Explorer)

So, I'm testing this on a Dell Workstation, one that does have Windows MR installed, but which because of the CPU config will not actually run Windows MR.

It does however, only have one, standard Windows graphics card, an Nvidia GeForce GTX 750 Ti, and the OS has been re-installed since my last attempt, so while not a fresh installation, it is still only about 6 months old and has been kept up to date.

This is a completely different machine to the Laptop I reported this on previously.

I'm also now using Visual Studio 2022, and the most up to date version of Stereokit on NuGet (21st Jun 2022)

I've performed a NuGet install of StereoKit, on a brand new blank Console app, and added the 4 lines required to get a cube up and on display, and as previous, it crashes out straight away on the initialize call, with exactly the same issue as previous.

![image](https://user-images.githubusercontent.com/1876454/174879960-aa1baa12-4e7d-45a2-b73d-ad50c15a7da7.png)

![image](https://user-images.githubusercontent.com/1876454/174880118-e3abc299-b194-4f7d-938c-fea7213813d6.png)


I have not yet tried it on the original Laptop that the VR headset is connected too, the specs as seen by DxDiag for this machine are as follows:

![image](https://user-images.githubusercontent.com/1876454/174880233-0ce933f6-c487-4365-a29b-712f79a05e2d.png)

![image](https://user-images.githubusercontent.com/1876454/174880312-abc1061e-eadd-4bbb-900c-2a2ab134b32d.png)

Driver info from Nvidia CPL:
![image](https://user-images.githubusercontent.com/1876454/174880689-54803465-7507-4b33-a770-f74751fad327.png)

Really hoping we can pin this down, because I really do like what I see in Stereokit, and would really like to give it a good try.

My use case for it, is actually very simple.  I help run a local history group, and as part of the displays we put on for local schools about the history of the area, I use the VR headset to give the pupils a sense of the large factories that we used to have in town.  Right now, all we realistically are doing is displaying 360 degree renders, but I would eventually like to take a scale model of the factories, and allow the viewer to walk around in them. :-)  Stereokit seems like the right balance between having a simple VR engine, but not needing all the latest video game effects that I require.

Regards
Peter "Shawty" Shaw

**Comment by shawty** [comment]
PS: this is what my console chucks out when run :

**Comment by jefmes** [comment]
@shawty Hey there Peter - I would still be leaning toward a graphics driver issue at this point, because everything else you're showing looks solid. That 456.71 driver was released back in Oct 2020 so it's possible the OpenXR support on that driver isn't fully baked for that graphics card. Give a look at this link, I would try driver version 516.40 which was released just last week and appears to have support for the GTX 750 Ti.

https://www.nvidia.com/en-us/drivers/results/190348/

**Comment by shawty** [comment]
@jefmes - I'll give it a go, but when I asked my Nvida control panel if there was an updated driver, it told me no :-S

Stand-by, lets see what happens.

**Comment by jefmes** [comment]
> 

Worth a shot at least! :)  I have seen that control panel lie many, many times so hopefully you'll get lucky.

**Comment by shawty** [comment]
Here goes nothing:
![image](https://user-images.githubusercontent.com/1876454/174887513-4ca08e70-fc72-41f0-847a-adc4da4a47a8.png)

Watch for the mushroom cloud coming from the direction of North East England :-)

**Comment by shawty** [comment]
That's gotta be a first!!!  Driver re-installed, and I wasn't asked to do a reboot... it just blanked the screen and all was good!

![image](https://user-images.githubusercontent.com/1876454/174888585-753211e2-21d1-4974-9e28-b31dba2dcd23.png)

**Comment by shawty** [comment]
@jefmes Unfortunately, all still the same.....

![image](https://user-images.githubusercontent.com/1876454/174888810-27909dad-1ee4-4fb3-bb22-1e12cd385b0b.png)

![image](https://user-images.githubusercontent.com/1876454/174888848-1d4e2acb-e218-42ac-8d53-95e4b80bc0c3.png)

Gonna try a reboot anyway

**Comment by shawty** [comment]
And no difference, even after a reboot :-(

![image](https://user-images.githubusercontent.com/1876454/174889813-85b1f712-fd22-4783-925a-7b1842b4e43e.png)

![image](https://user-images.githubusercontent.com/1876454/174889886-e842d84f-bfa1-4d41-8da5-5246c715bfdc.png)

**Comment by jefmes** [comment]
Bah! Well, one potential issue checked off the list at least. My next two thoughts to check would be:

1. Are you by chance running as a limited/non-admin user on this workstation? Are you able to try running Visual Studio as Administrator and seeing if we get a different result? AccessViolation errors are very often a symptom of permissions problems and security features. I wonder if there have been any other users trying StereoKit on a Xeon processor?

2. With it being a Xeon processor, it would not surprise me if there is some BIOS level memory protection enabled. 

3. I don't recall if you tried this, but perhaps try installing the "OpenXR Tools for Windows Mixed Reality" and we can see what the OpenXR runtime looks like for the machine in the second tab.  
https://apps.microsoft.com/store/detail/openxr-tools-for-windows-mixed-reality/9N5CVVL23QBT?hl=en-us&gl=US

**Comment by shawty** [comment]
@jefmes 

1) I'm running using my normal user account, which is part of the Admin Group, but I'm happy to try the old right click run as admin thing..... (I have full admin access on this machine and can do anything I like)

2) I can't say I've ever noticed anything like that, I have 2 Xeon workstations, one running on Win 10 (This one) and one running Ubuntu 20.04 LTS (Graphics card in that one is not very powerful unfortunately, and Windows 10 Refuses to run on it with multiple Xeons in) I did used to use that machine however, but with only one Physical Xeon CPU in, and the GFX card in this machine, same issue (That was the none Laptop machine I was using when I first opened this)

3) I don't believe I have, but am willing to give it a try.

For reference, the actual Windows MR app on this machine (Dell T3500 workstation) won't run, because it uses a SMID CPU Instruction, that's not available on my CPU, the Laptop (Yet to be retested) is pretty much the same spec, but an older Nvidia Card, however the CPU is an core i7, so the Laptop runs the headset and winmr perfectly fine.  I would however expect this one the T3500 to have no issues running in Flatscreen mode.

Will try 1 & 3 see what happens...

**Comment by shawty** [comment]
@jefmes 
 No luck with running as Admin... no difference.

**Comment by shawty** [comment]
Thanks, I'll let you know how I get on :-)

It's an awkward beast for sure, the ONLY runtime (Apart from SteamVR itself) that I've gotten to run on the VR itself without and hoha was "Lovr" but I just can't bring myself to write my project in LUA 😂😂😂😂😂

**Comment by maluoi** [comment]
Okay, this time I can see that the issue is happening when initializing default assets! That's _mostly_ graphics stuff, but could still be a few other things. Another thing to try here for more info, I added Source Link to StereoKit recently as well, so you can in theory get an error breakpoint in SK's codebase!

Try turning off "Just My Code" (`Tools->Options->Debugging->General->Enable Just My Code`), and enable native debugging for your project! (maybe `Project->Properties->Debug->(Native code debugging)`, may be a bit different depending on your project type) This should grab SK's code off GitHub and show you exactly where it's crashing!

**Comment by shawty** [comment]
@maluoi Thanks Nick, I'll try that tomorrow.  

Cheers
Shawty

PS: Great work on the presentations you did, your a natural presenter..... :-)

**Comment by shawty** [comment]
LOL... completely forgot about this :-)

Just got notified it was still sat here.

I do now actually have a third machine to test this on, when I get around to it.

Best left closed though, as I have no idea when I'll get back to looking at it.
