### ISSUE TITLE
Request: Contributing.md

### ISSUE THREAD

**Issue by Strepto** [StereoKit/StereoKit#208]
Hey, great stuff you have here! 

I wanted to try to prototype a Holographic Remoting integration to the project, but had problems actually starting and contributing.

How do I build the actual StereoKit code myself? 

Do i need cmake?

What is the required Visual Studio version? 

How should I format code?

I tried downloading XMake from (`https://xmake.io/`) and it was flagged as a virus. Is it needed? 

Many questions around this makes the barrier of entry much higher :) 

Consider creating a `contributing.md` for lower barrier of entry and answering some of these common questions for a local dev-environment.

**Comment by maluoi** [comment]
Well this is the kind of problem I _love_ to have, it does seem like I finally may need a contributor doc! I'll put this on the list, and try and get to this during the next update.

The build system is a little on the complex side right now, so apologies there, I do hope to simplify some of this as well. But I'll take a quick stab at answering your questions here.

- **How do I build the actual StereoKit code myself?**
  - Building from the Visual Studio Solution is how I do the vast majority of SK development. I'll set one of the `StereoKitCTest` or `StereoKitTest` projects as the startup project, and build/run like most normal apps.
  - I'd probably recommend unloading the `StereoKitTest_Android` and `StereoKitCTest_Android` projects to start with, as these _do_ work with xmake via Pre-Build Events. If you're only working with Windows, you can just leave it this way, and this should considerably simplify the configuration/setup needed.
  - This should work without too much additional configuration, but I'm not 100% certain what the exact pre-reqs are here. Depending on your setup, some additional VS Workloads may be needed.
  - Full NuGet builds are done via the [Build-Nuget.ps1](https://github.com/maluoi/StereoKit/blob/master/Build-Nuget.ps1) powershell script. It's a mix of VS, WSL, and xmake, so it may be tricky to set up completely. You may be able to set up Windows-only NuGet builds in VS with the `StereoKit` project, but I don't think I've tested this recently.
- **What is the required Visual Studio version?**
  - VS 2019 is what I recommend. I've also successfully used 2022 with some project re-targeting, but 2022 doesn't seem to be a particularly stable product with the current builds. I recently switched back to 2019.
- **Do i need cmake?**
  - The cmake build file currently only works for Linux and Windows builds, it still needs Android support. Some Linux devs are using it at the moment, but official builds on NuGet are still built with VS/xmake.
- **I tried downloading XMake from (https://xmake.io/) and it was flagged as a virus. Is it needed?**
  - xmake is currently used only for the Linux and Android builds. If you aren't building those, it shouldn't be necessary.
- **How should I format code?**
  - For C#, I stick to what I understand the C# standard to be, shouldn't really be surprises there :)
  - C side is done with snake casing, brackets at the end of the line, `_t` to indicate types, stuff like that. It should be relatively clear when you see it. I am not super picky as long as your code vaguely looks like the rest of the code around it.
  - StereoKitC is not an object oriented code base. While it is technically C++, and does occasionally use C++ concepts, it's best to think of StereoKit generally as a C codebase where C++ is occasionally used to assist with readability or C++ interop. So: avoid classes, no STL, use POD structs (Plain Old Data), stuff like that.

I hope that's helpful, please feel free to ask questions about the codebase anytime!

**Comment by maluoi** [comment]
A contributing.md can be found over here now :)
https://github.com/StereoKit/StereoKit/blob/master/CONTRIBUTING.md
