### ISSUE TITLE
VS Add Reference error: A reference to 'StereoKitC_UWP' could not be added.

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#253]
Created a new project for HoloLens 2 using the StereoKit UWP template in VS 2019 and 2022. I added the StereoKit, StereoKitC, and StereoKitC_UWP to my solution because I am tweaking the C++ at the moment, experimenting.
When I try to reference the StereoKitC_UWP as it is in the examples, I get the error. Naturally, if I build the StereoKit code to a nuget package and use that, I have no issue. But I am directly referencing the code as is done in the example projects. Note: I noticed that VS 2019 and 2022 are indicating a problem with the reference as it is in the current examples.
My guess is you manually edited the references to add it in?

## Platform / Environment
Windows 10 and Windows 11, Visual Studio 2019 and Visual Studio 2022.

## Logs or exception details
Error text: A reference to 'StereoKitC_UWP' could not be added. The method or operation is not implemented.
```
Logs are super helpful, please include them if they're at all relevant!
```
_If you have an exception, details about that would also be essential._

**Comment by maluoi** [comment]
I had a fair bit of difficulty with directly referencing native projects from C# projects. I've not been certain if it's something with the specific project files, or something a little more fundamental!

In the StereoKit .sln, I don't reference the native projects directly, but instead rely on the build 'dependencies functionality' to ensure things get built in order. I then manually copy some of the output files using MSBuild/XML commands, so you'll almost certainly need to modify your .csproj to work in this way. Check out [StereoKitTest.csproj](https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/StereoKitTest.csproj#L27) for what I'm doing. I'm not sure how well this translates to external projects, probably doable, but there may need to be some path modifications? I think I use $(SolutionDir) a bunch, and that may not be as durable in this case.

This isn't a use-case I've covered, so you're trailblazing here :)
