### ISSUE TITLE
UI Element Active API

### ISSUE THREAD

**Issue by maluoi** [StereoKit/StereoKit#272]
## Describe the feature
Would be nice to have the ability to query some of SKUI's internal state, for determining which hands were used, or to more easily check focus/active state of elements. This can be really helpful for building custom UI elements

Perhaps some functions such as:
- `BtnState UI.LastElementHandUsed(Handed hand)`
- `BtnState UI.LastElementIsActive()`
- `BtnState UI.LastElementIsFocused()`

## An example use-case
From mlz on Discord
> A simple and clean solution could simply be to expose, as read only of course, the ID of the active element for each hand (exposing also the ID of the “hot” or candidate element would also be great, enabling hovering effects), for this frame and previous frame. So once I am in the UI.Handle, I just have to compare my ID to the one on the hands. Not only can I know which hand or both is using my object, I can also know if the object just entered handling (with previous frame info), no need to have an extra state variable in my code.

> ...so we can change the Color of an unmanipulated object that will be picked. It allows us to give more feedback to the user and avoid him mistakenly picking a wrong object (when objects are crowded).

**Comment by opl-** [comment]
I believe a related use case is being able to ignore key presses in flatscreen mode while a UI input is active. Don't want the user to be moving around while typing because they want to input "sawed" on their keyboard.

**Comment by maluoi** [comment]
This is now live on NuGet in v0.3.6-preview.7! API is basically as described currently, but I'm very much open to feedback here, I added this in a little bit of a rush.

**Comment by maluoi** [comment]
Good call! Yeah, looks like it was still using just the fingertip instead of pinch point, legacy stuff I suspect. Easy fix, will be in the next build :)
