### ISSUE TITLE
Finger bones / skinning / mesh deformation

### ISSUE THREAD

**Issue by ClonedPuppy** [StereoKit/StereoKit#286]
## Description
It seems as if SK offsets the bone nodes for the fingers apart from the thumb, which seems to work ok. It's hard to explain, and it's probably easiest to understand without me writing a lot of text by just having a look at the test project over here:
https://github.com/ClonedPuppy/SKHands

## Platform / Environment
Tested using the StereoKitXPlatform template, Windows and Android(Oculus 2).

## Logs or exception details
First have a go with normal hand tracking, it should work as expected. Finger tips and joint with skin seem to line up correctly as far as I can see (disregard the few skinning issues on the palm etc). After that have a look at the hands when switching to controllers, the nodes shift forward one bone length (apart from the thumb which seems ok). 

I have added the blender file for you to check out, but as far as I can tell it should be ok. I'm a bit perplexed as to why the tip bones need to stick outside the finger tips on the 4 fingers, and not on the thumb. But I can't really figure out what's going on. I have dumped the SK finger nodes from a hand tracking session where I basically just held my hand out as neutral as possible. You can view them by enabling the RefNodes collection.

**Comment by maluoi** [comment]
So I'm still messing around with the flatscreen stuff right now, but I've been playing with it and have some modifications to the skeleton that seem to behave much more appropriately! These joints aren't in exactly the correct spots yet, so there's still distortion on the mesh, but it does map more appropriately to the hand joints. Thumbs in particular here. I'll try and nail it down a bit better.

![image](https://user-images.githubusercontent.com/8484884/150657123-8d58d294-feb8-4d2c-98dd-d23f1d64bf78.png)

There's also some code modifications here that I've done. I skipped joint index 1 on the thumb, and removed some of the palm stuff. But when I'm done messing around with this on Quest later, I'll make a PR on your repo so you can see exactly!

**Comment by ClonedPuppy** [comment]
Do you think it would be easier from an artist view, if you renamed the current indexTip (for instance) to something like indexTerminator? If you have a look at the current skinning, the tip weights end at the dist bone, and the tip bone has no weights at all.
![image](https://user-images.githubusercontent.com/1387713/150662553-7553c94b-b712-4459-9091-54e2d44b2156.png)

But maybe this is something you are already looking at, just thought I'd mention it.

**Comment by maluoi** [comment]
Yeah, the tip 'bones' aren't really relevant, I was just hesitant to delete them too quickly! I did actually delete them in the PR that I just did:
![image](https://user-images.githubusercontent.com/8484884/150668376-da35f3ec-ce17-43be-99cc-dc5bf62ca608.png)

Check out that PR, and see if it makes any sense to you! The only point where doing anything with the tip 'joint' makes sense is for scaling the ModelNodes, which I did _not_ do here, but would be important to account for differing hand sizes. So you'll notice that I'm only working with the first 4 joints on the hand, and only three for the thumb!

I still haven't tried this on Quest yet, I'm still working from my laptop today! But I'd love to know if it fixes anything over there. It might.

**Comment by ClonedPuppy** [comment]
Has there been any recent change on the default scale of the bone nodes, or the way the fingers length or something are detected? Looks longer and thinner now?

**Comment by maluoi** [comment]
There was no change from SK's side! It's possible something may have changed with Oculus runtime v37? I didn't notice anything specific, but I would not be surprised to see ongoing refinements to how hand tracking works.

**Comment by ClonedPuppy** [comment]
Yes probably. Is there a way we can visualize the weights in SK? The falloff seems to be quite different from how blenders falloff seem to work. Been going back and forth experimenting a bit and it's pretty hard to nail down the right amount.

**Comment by maluoi** [comment]
Ah, like the skin weights don't match up? I imagine for this case where the hand skeletons are both likely to be a little different, there could be some discrepancies between how the meshes stretch out. If you think it's more than just that, I can definitely dig into the skinning code to see if there's something wrong with the math!
