### ISSUE TITLE
Identify when a handle is in range to be grabbed and which hand grabbed it

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#319]
## Describe the feature
Currently a handle returns true if it's grabbed. I would like to know when the hand is in a suitable position to grab the handle, but has not yet grabbed it, so I can convey this to the user. It would also be useful to know which hand grabbed the handle.

## An example use-case
For custom controls I want to highlight the control and increase it's scale a little when the hand is in position to interact with it. This lets the user know they are in the correct position to grab the control.

In some situations I want to hide the hand while they are grabbing the control so the user can more clearly see what's happening. It would be helpful if the handle returned which hand grabbed it so I can then hide the correct one.

Maybe rather than returning true or false the handle could return an enum:
HandleState.None
HandleState.Grabbable
HandleState.HeldByRightHand
HandleState.HeldByLeftHand

Thanks.

**Comment by maluoi** [comment]
It sounds like this request does have significant overlap with #272! I'll definitely consider this scenario as well.

**Comment by maluoi** [comment]
#272 is live in v0.3.6-preview.7! If you try it out, I'd love to know how it goes :)

**Comment by Jumbli** [comment]
Yes, I think I have everything I need with this now. Thank you :)
