### ISSUE TITLE
Flag to disable window body grab

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#335]
## Describe the feature

Have a flag to disable any grab interaction with a window's body (but still allow grabbing the window title area).

## An example use-case

When having a slider on a window I find it pretty hard to grab the slider handle, and in lots of cases grab the window body instead causing it to get dragged around.

**Comment by paulmelis** [comment]
> You are supposed to use it by touching it with your index finger and sliding rather than pinching / grabbing the slider.

That's probably the other slider type (`UIConfirm.Push`), where you press it first and then change it. The one I'm using (`UIConfirm.Pinch`) definitely needs a grab to change it, a single index finger does not work, at least not for me.

> a) Keep the body grab mechanism, but only enable it when you are not positioned over the bounds of another interactive area / component. Ideally this would be built into SK rather than us having to code when to enable a flag.

This would indeed be a nice improvement

**Comment by Jumbli** [comment]
Thanks for correcting me, I missed that option. I may switch to using the pinch version now :)

**Comment by maluoi** [comment]
An improved pinch volume is in v0.3.6-preview.4! Would love your feedback on it here :)

**Comment by maluoi** [comment]
Closing this one based on recent improvements, but please feel free to re-open if you test this and still feel like it's not enough!
