### ISSUE TITLE
Using an image as a button

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#340]
## Describe the feature

I don't think there's currently a way to have an image also serve as a button? Maybe this could be done with a new type of handle that responds to a "click" intersection (instead of to a grab). So you can turn any type of 3D item into something clickable.

## An example use-case

Icon-style buttons to perform actions, e.g. switch between 3D models based on their thumbnail buttons.

**Comment by paulmelis** [comment]
By the way, there *is* the hand menu with image sprites, of course. But I don't really find hand menus a good solution as it's easy to make hand gestures that accidentally click the menu items when that's not what you intend. But I should test SK's implementation of hand menus a bit more to see if they are also vulnerable to this.

**Comment by maluoi** [comment]
This is actually something I've been planning on for this update! Technically, there is already [`UI.ButtonRound`](https://stereokit.net/Pages/Reference/UI/ButtonRound.html), which uses a Sprite for the label, but it does look a bit different from a normal button. There's also the somewhat hidden `UI.ButtonBehavior`, which gives you most of the tools you need to make a custom button. But that's work :D

For this update, I'm planning to add a Button that'll support Sprite + Text in a few different layouts:
- Sprite only
- Sprite with text below
- Sprite with text to right

I've been a little tempted to also do something like a `UI.PushButton`/`PopButton` and just make the whole interior "pressable", but I'm not sure how I feel about that quite yet.

**Comment by maluoi** [comment]
This is now live on NuGet in v0.3.6-preview.7! See `UI.ButtonImg`.
