### ISSUE TITLE
Switching between pass-through and opaque mode

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#342]
## Describe the feature

Instead of choosing blending preference during initialization allow it to be switched at any point. Not sure this is even possible in the current framework and/or fits with the capabilities of the different devices.

## An example use-case

Testing with pass-through XR on the XR-3 shows that there are cases where being able to control full VR versus pass-through XR is useful. For example, when viewing a photogrammetry model of a large area I'd like to both be able to see a maquette view (model scaled down to say 1.5x1.5 meters) in XR, but when switching to 1:1 view physical boundaries (e.g. walls) get in the way of a full-size experience and showing the model in full VR would be better.

**Comment by maluoi** [comment]
Peeking at the code, this does look like it should indeed be do-able! I'll look into adding something to the World class that'll do this, I think.

**Comment by maluoi** [comment]
`Device.DisplayBlend` and `Device.ValidBlend()` should be able to control this now. I don't have a device capable of switching passthrough in this manner, so I'd be interested if this works for others.
