### ISSUE TITLE
Filepicker does not support the Chinese path

### ISSUE THREAD

**Issue by suzhouhu** [StereoKit/StereoKit#374]
Filepicker does not support the Chinese path，When I open the file with a Chinese path, it is prompted to find the file!

**Comment by maluoi** [comment]
Hey, thanks for the report! Any chance you could give me some additional details here? I'd love to know:

What OS you're using.
What version of the StereoKit NuGet you're using.
What headset you're using.
And any code or details you think might be helpful here!

A quick suggestion would be to try out the NuGet package for v0.3.6-preview.6, which does have a few file path related fixes for issues in v0.3.5.

**Comment by suzhouhu** [comment]
HTC vive



Thank you very much for answering so in time！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
Hey, thanks for the report! Any chance you could give me some additional details here? I'd love to know:
 
What OS you're using.
 What version of the StereoKit NuGet you're using.
 What headset you're using.
 And any code or details you think might be helpful here!
 
A quick suggestion would be to try out the NuGet package for v0.3.6-preview.6, which does have a few file path related fixes for issues in v0.3.5.

**Comment by maluoi** [comment]
Does StereoKit v0.3.6-preview.6 fix the issue for you?

**Comment by suzhouhu** [comment]
What I currently use is STEREOKIT V0.3.6-preview.6！！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
Does StereoKit v0.3.6-preview.6 fix the issue for you?

**Comment by suzhouhu** [comment]
In addition, I also want to disturb you, that is, I make an organic molecular simulation display. I hope that by clicking on a button, the molecular model in the scene can automatically rotate and swing the function. I don't know the function you need to use?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
Does StereoKit v0.3.6-preview.6 fix the issue for you?

**Comment by maluoi** [comment]
I think I'll still need some additional details! I just tried using the File Picker to open a .glb with `原始邮件` in the name, and a .glb with `原始邮件` as the name of the parent folder. Both worked perfectly fine!

Can you give me something specific I can use to reproduce the error?

With respect to your molecular simulation, I'm not entirely sure I understand the question yet! If you could open up a separate Question [over here](https://github.com/StereoKit/StereoKit/discussions) and provide a more detailed explanation, that'd be great.

I'm heading to sleep now, but I'll check on these in the morning :)

**Comment by suzhouhu** [comment]
In addition, I want to disturb you, that is, I made organic molecular simulation display. I hope that through the button, the molecular model in the scene can automatically rotate and swing the function. I don't know which function can implement this function? Or do you have any related example source code




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
Does StereoKit v0.3.6-preview.6 fix the issue for you?

**Comment by suzhouhu** [comment]
It's hard for you, you can rest first, wait for me to sort it up, maybe I did not describe the reason for the problem to clear




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
I think I'll still need some additional details! I just tried using the File Picker to open a .glb with 原始邮件 in the name, and a .glb with 原始邮件 as the name of the parent folder. Both worked perfectly fine!
 
Can you give me something specific I can use to reproduce the error?
 
With respect to your molecular simulation, I'm not entirely sure I understand the question yet! If you could open up a separate Question over here and provide a more detailed explanation, that'd be great.
 
I'm heading to sleep now, but I'll check on these in the morning :)

**Comment by suzhouhu** [comment]
I tried this morning, as long as the file path contains Chinese characters, all show garbleds and cannot pass!













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
I think I'll still need some additional details! I just tried using the File Picker to open a .glb with 原始邮件 in the name, and a .glb with 原始邮件 as the name of the parent folder. Both worked perfectly fine!
 
Can you give me something specific I can use to reproduce the error?
 
With respect to your molecular simulation, I'm not entirely sure I understand the question yet! If you could open up a separate Question over here and provide a more detailed explanation, that'd be great.
 
I'm heading to sleep now, but I'll check on these in the morning :)

**Comment by maluoi** [comment]
Can you provide an example path, and the specific error that gets thrown?

**Comment by suzhouhu** [comment]
I just use this example,”https://github.com/StereoKit/StereoKit “ ” just change the directory to Chinese




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 上午7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
Can you provide an example path, and the specific error that gets thrown?

**Comment by maluoi** [comment]
I have tried:

- GLTF filename with Chinese characters
- GLTF file in a folder with Chinese characters
- Executable in a folder with Chinese characters loading a file with Chinese characters.

All these things work great for me! I can't reproduce any errors based on what you've given me so far.

I really need some solid details about what you're doing differently. Code, specific exceptions, callstacks, screenshots, etc. More details please!

**Comment by suzhouhu** [comment]
When I finished the class, I will send you my code and all the operating environment in the afternoon




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 上午7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
I have tried:
  
GLTF filename with Chinese characters
 
GLTF file in a folder with Chinese characters
 
Executable in a folder with Chinese characters loading a file with Chinese characters.
  
All these things work great for me! I can't reproduce any errors based on what you've given me so far.
 
I really need some solid details about what you're doing differently. Code, specific exceptions, callstacks, screenshots, etc. More details please!

**Comment by suzhouhu** [comment]
There are my source code in the attachment, and the compiled run EXE program




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StereoKit/StereoKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 上午7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StereoKit/StereoKit] Filepicker does not support the Chinese path (Issue #374)





 
I have tried:
  
GLTF filename with Chinese characters
 
GLTF file in a folder with Chinese characters
 
Executable in a folder with Chinese characters loading a file with Chinese characters.
  
All these things work great for me! I can't reproduce any errors based on what you've given me so far.
 
I really need some solid details about what you're doing differently. Code, specific exceptions, callstacks, screenshots, etc. More details please!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

刘鹄中Picker.rar (57.03M, 2022年06月22日 14:13 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7133363284120bcd14f0891f4764561e03510f56075555551904575054495006570a1b535702071c560b0f0a5853560852550757617464f0c1c3f6e4b1340d525f56441c1305163109&code=4362add1

**Comment by suzhouhu** [comment]
![a542c569aed4eebbd9a80521f0e32f98](https://user-images.githubusercontent.com/23079693/169907970-cbed1a9e-0e6d-42bb-83c0-115b2df78de7.png)
![2ffc2557184c9080c6f3ce59d11c9519](https://user-images.githubusercontent.com/23079693/169908055-687ee77c-347d-4ad1-957c-8a4c4898c1c2.png)
This is strange. Is there a problem with my Windows system? In fact, **delete the Chinese character in the .glt file path**, everything is normal

**Comment by suzhouhu** [comment]
Today I spent **5 hours** to cleanly install windows11 on my computer system, then install VS2022, and then test Filepicker, the result is still unable to open the .glb file with Chinese character path, and then I installed in other several  computer, but it still doesn't open. Basically, it can be determined that it is not a Windows system problem.

**Comment by maluoi** [comment]
Thanks for the screenshots, that's _very_ helpful! I'm still not certain about the solution, but this is very helpful for understanding what's happening.

I guess I'd like to know, I do see that the model loading path has repeating characters in it, `repos\ABCABCABCPicker\bin`. Is that intentional and a valid file path, or is StereoKit picking up bad characters there somehow?

I'll look into seeing if there's some language settings that may be interfering with the behavior of UTF conversion functions!

**Comment by maluoi** [comment]
Just an update on this, I did spin up a fresh VM and switched the language settings over to Chinese! It was still working perfectly for me there. I'll be testing this later with a VM image that's Chinese from the start as well.

One of my co-workers did mention that the ABCABCABC pattern in the file picker string looked related to bad Unicode conversion of some sort, so I've also been digging through some of that code. Nothing obvious yet, but it's tough to check that without the ability to reproduce the error. I'll keep digging!

**Comment by maluoi** [comment]
Okay! I did just find a place that doesn't properly account for Unicode characters! Too many file picker implementations :) I'll work on this part a bit more, and I should have some changes in an upcoming preview build.

**Comment by suzhouhu** [comment]
that would be great! Thank you for your persistence

**Comment by maluoi** [comment]
Okay, I have a change that _should_ fix this! Unless you need this change _right_ now, I'll kick off a new preview build for NuGet later this week, maybe Friday? I have a few additional things I'd like to include in this one! :)

**Comment by suzhouhu** [comment]
Don't worry, you are busy with other things first

**Comment by maluoi** [comment]
Great! I'll poke this thread when the change is live then :)

**Comment by maluoi** [comment]
This is now live on NuGet in v0.3.6-preview.7! Thanks for your patience :)

Please do re-open this if the problem persists.
