### ISSUE TITLE
Add EGL and OpenGL to BackendGraphics enum

### ISSUE THREAD

**Issue by technobaboo** [StereoKit/StereoKit#382]
## An example use-case
In Stardust, I need to ensure that it's running using EGL so I can get an EGL context for all the Wayland stuff...

BackendGraphics as in https://stereokit.net/Pages/Reference/BackendGraphics.html

**Comment by maluoi** [comment]
From Malek on Discord:

```rust
fn sk_get_graphics_data() -> GraphicsData;

enum GraphicsData {
    EGL(EGLContext, EGLDisplay),
    GLX(GLXContext, GLXDisplay, GLXDrawable),
}
```

**Comment by maluoi** [comment]
This is now in v0.3.7-preview.2! @technobaboo feel free to pop this back open if you run into any other related vars that are critical for what you're doing.
