### ISSUE TITLE
Unable to load some GLB files

### ISSUE THREAD

**Issue by jackdaus** [StereoKit/StereoKit#398]
## Description
When I load a particular GLB file, I get the error:
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

This doesn't seem to happen for all GLB files. I've tried two files. One works but the other doesn't. These GLB files are examples provided by KhronosGroup:
- OK: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/glTF-Binary/AnimatedMorphCube.glb
- NOT OK: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb

The model AnimatedMorphCube.glb loads fine. But I can an error for the fox model when calling 
`Model.FromFile("Fox.glb");`

I've loaded both GLB files into this viewer (https://sandbox.babylonjs.com/), and both seem to load fine without error.

## Platform / Environment
I am running the flatscreen simulator on a Windows machine (Windows 10). This is C# code. I began the project with the StereoKitUniversal template. 

I wasn't able to attach the solution to this bug report (file too big). But here is a repo to repro the bug - https://github.com/jackdaus/SKDebug. (Maybe there is a better way to share the code in the future? just lmk)

## Logs or exception details
```
[SK diagnostic] Initializing StereoKit v0.3.6 Win32 x64...
[SK diagnostic] Initializing Assets
[SK diagnostic] Initializing Platform
[SK diagnostic] sk_gpu: Using Direct3D 11: NVIDIA GeForce GTX 1650 Ti with Max-Q Design
[SK diagnostic] Starting mixed reality mode
[SK diagnostic] available: XR_KHR_D3D12_enable
[SK diagnostic] available: XR_KHR_opengl_enable
[SK diagnostic] available: XR_KHR_vulkan_enable
[SK diagnostic] available: XR_KHR_vulkan_enable2
[SK diagnostic] available: XR_KHR_convert_timespec_time
[SK diagnostic] available: XR_KHR_composition_layer_cube
[SK diagnostic] available: XR_KHR_composition_layer_cylinder
[SK diagnostic] available: XR_KHR_composition_layer_equirect
[SK diagnostic] available: XR_KHR_visibility_mask
[SK diagnostic] available: XR_KHR_composition_layer_color_scale_bias
[SK diagnostic] available: XR_EXT_win32_appcontainer_compatible
[SK diagnostic] available: XR_OCULUS_recenter_event
[SK diagnostic] available: XR_FB_display_refresh_rate
[SK diagnostic] available: XR_OCULUS_ovrsession_handle
[SK diagnostic] available: XR_OCULUS_perf_stats
[SK diagnostic] available: XR_FB_hand_tracking_aim
[SK diagnostic] available: XR_FB_hand_tracking_capsules
[SK diagnostic] available: XR_FB_hand_tracking_mesh
[SK diagnostic] available: XR_FB_keyboard_tracking
[SK diagnostic] available: XR_FB_passthrough
[SK diagnostic] available: XR_FB_triangle_mesh
[SK diagnostic] available: XR_FB_render_model
[SK diagnostic] available: XR_FB_spatial_entity
[SK diagnostic] available: XR_FB_spatial_entity_storage
[SK diagnostic] available: XR_FB_spatial_entity_query
[SK diagnostic] available: XR_FB_spatial_entity_container
[SK diagnostic] available: XR_FB_scene
[SK diagnostic] available: XR_EXT_debug_utils
[SK diagnostic] REQUESTED: XR_KHR_D3D11_enable
[SK diagnostic] REQUESTED: XR_KHR_composition_layer_depth
[SK diagnostic] REQUESTED: XR_KHR_win32_convert_performance_counter_time
[SK diagnostic] REQUESTED: XR_OCULUS_audio_device_guid
[SK diagnostic] REQUESTED: XR_FB_color_space
[SK diagnostic] REQUESTED: XR_EXT_hand_tracking
[SK info] Couldn't find our desired MR form factor, no MR device attached/ready? [XR_ERROR_FORM_FACTOR_UNAVAILABLE]
[SK info] MixedReality display mode failed, falling back to Flatscreen
[SK diagnostic] Starting flatscreen mode
[SK diagnostic] Created swapchain: 1280x720 color:rgba32_linear depth:depth32
[SK diagnostic] Initializing Audio
[SK diagnostic] ISAC audio backend not available, falling back to miniaudio! It's likely the device doesn't have Windows Sonic enabled, which can be found under Settings->Sound->Device Properties->Spatial Sound.
[SK info] Using audio backend: WASAPI
[SK diagnostic] Initializing Defaults
[SK diagnostic] Initializing World
[SK diagnostic] Initializing Sprites
[SK diagnostic] Initializing Lines
[SK diagnostic] Initializing UI
[SK diagnostic] Initializing Renderer
[SK diagnostic] Initializing Physics
[SK diagnostic] Initializing Input
[SK info] Initialization successful
[SK warning] Animated weights unsupported
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at StereoKit.NativeAPI.model_create_file(Byte[], IntPtr)
--------------------------------
   at StereoKit.Model.FromFile(System.String, StereoKit.Shader)
   at StereoKitApp.App.Init()
   at SKLoader.Main(System.String[])

```

**Comment by maluoi** [comment]
Okay, it looks like the fox model has no index buffer! The GLTF spec apparently says that's okay, so I added some code to generate indices to match a purely vertex based mesh. Works great! This is currently on `/develop` and will be in the next preview build. I'm not in a rush for the next preview build, so let me know how critical this feature is and when you need it, and I can set that up to build sooner :)

![image](https://user-images.githubusercontent.com/8484884/174138208-6059f9d9-d8ff-4822-8af1-7816f9bac90d.png)

SK's GLTF loader is relatively robust by now, but there are still edge-cases in it. I need to spend some time and set up testing to ensure it's _completely_ compliant, maybe support some additional extensions, but right now I'm handling cases as they come! So if you encounter more of these in the future, just link the GLTF and I can load it up and make it work :)

**Comment by maluoi** [comment]
Okay, v0.3.7-preview.1 is up now and contains fixes for this! I'll close this issue now, but please feel free to re-open it if the problem persists :)
