### ISSUE TITLE
Animated GLTF rotates at end of loop

### ISSUE THREAD

**Issue by jackdaus** [StereoKit/StereoKit#399]
## Description
I am loading a free GLTF I found online (https://sketchfab.com/3d-models/animated-low-poly-spider-game-ready-2d79c585b5404a23b7bcc0be06068283). In other animation players, like Babylon.js Sandbox or Windows 3D Viewer, the animation loops perfectly. However, when I play the "walk forward" (walk_ani_vor) animation in StereoKit, the last frame of the loop seems to rotate the spider 180°! Attached is a gif showing the glitch. I've also attached 2 still frames showing that spider gets rotates 180° at the end of the animation. This may just be a issue in the model itself, but I don't know enough about 3D models to figure out if that's the case. I've attached the model here (spider.zip).

_Screen capture_
![animated spider](https://user-images.githubusercontent.com/53974525/174449495-436e5857-bbd4-4dcb-888d-25a2b55c5120.gif)

_For most of the animation, the spider if facing this way_
![forward spider](https://user-images.githubusercontent.com/53974525/174449494-89804cda-ebe8-4f11-9798-64e60deefff8.png)

_But at then end of the animation, it rotates 180°!_ 
![backward spider](https://user-images.githubusercontent.com/53974525/174449493-c3c19875-5fba-421d-8375-7d4bbb8df334.png)

_The model (same as from link above)_
[Spider.zip](https://github.com/StereoKit/StereoKit/files/8934035/Spider.zip)

There is this warning in the log which might (or might not) be relevant:
`[SK warning] [spider/scene.gltf] Too many texture coordinate channels! Only one supported, the rest will be ignored.`

## Platform / Environment
This occurs on both the flatscreen simulator and on my Oculus Quest 2 + Link. I used the StereoKit Universal template to begin the project. I am using SK version 0.3.6. My graphics card is NVIDIA GeForce GTX 1650 Ti with Max-Q Design. I just updated the drivers today, but that didn't seem to fix the issue. Driver update was from 6/15/2022. 

## Logs or exception details
```
[SK diagnostic] Initializing StereoKit v0.3.6 Win32 x64...
[SK diagnostic] Initializing Assets
[SK diagnostic] Initializing Platform
[SK diagnostic] sk_gpu: Using Direct3D 11: NVIDIA GeForce GTX 1650 Ti with Max-Q Design
[SK diagnostic] Starting mixed reality mode
[SK diagnostic] available: XR_KHR_D3D12_enable
[SK diagnostic] available: XR_KHR_opengl_enable
[SK diagnostic] available: XR_KHR_vulkan_enable
[SK diagnostic] available: XR_KHR_vulkan_enable2
[SK diagnostic] available: XR_KHR_convert_timespec_time
[SK diagnostic] available: XR_KHR_composition_layer_cube
[SK diagnostic] available: XR_KHR_composition_layer_cylinder
[SK diagnostic] available: XR_KHR_composition_layer_equirect
[SK diagnostic] available: XR_KHR_visibility_mask
[SK diagnostic] available: XR_KHR_composition_layer_color_scale_bias
[SK diagnostic] available: XR_EXT_win32_appcontainer_compatible
[SK diagnostic] available: XR_OCULUS_recenter_event
[SK diagnostic] available: XR_FB_display_refresh_rate
[SK diagnostic] available: XR_OCULUS_ovrsession_handle
[SK diagnostic] available: XR_OCULUS_perf_stats
[SK diagnostic] available: XR_FB_hand_tracking_aim
[SK diagnostic] available: XR_FB_hand_tracking_capsules
[SK diagnostic] available: XR_FB_hand_tracking_mesh
[SK diagnostic] available: XR_FB_keyboard_tracking
[SK diagnostic] available: XR_FB_passthrough
[SK diagnostic] available: XR_FB_triangle_mesh
[SK diagnostic] available: XR_FB_render_model
[SK diagnostic] available: XR_FB_spatial_entity
[SK diagnostic] available: XR_FB_spatial_entity_storage
[SK diagnostic] available: XR_FB_spatial_entity_query
[SK diagnostic] available: XR_FB_spatial_entity_container
[SK diagnostic] available: XR_FB_scene
[SK diagnostic] available: XR_EXT_debug_utils
[SK diagnostic] REQUESTED: XR_KHR_D3D11_enable
[SK diagnostic] REQUESTED: XR_KHR_composition_layer_depth
[SK diagnostic] REQUESTED: XR_KHR_win32_convert_performance_counter_time
[SK diagnostic] REQUESTED: XR_OCULUS_audio_device_guid
[SK diagnostic] REQUESTED: XR_FB_color_space
[SK diagnostic] REQUESTED: XR_EXT_hand_tracking
[SK info] Couldn't find our desired MR form factor, no MR device attached/ready? [XR_ERROR_FORM_FACTOR_UNAVAILABLE]
[SK info] MixedReality display mode failed, falling back to Flatscreen
[SK diagnostic] Starting flatscreen mode
[SK diagnostic] Created swapchain: 1280x720 color:rgba32_linear depth:depth32
[SK diagnostic] Initializing Audio
[SK diagnostic] ISAC audio backend not available, falling back to miniaudio! It's likely the device doesn't have Windows Sonic enabled, which can be found under Settings->Sound->Device Properties->Spatial Sound.
[SK info] Using audio backend: WASAPI
[SK diagnostic] Initializing Defaults
[SK diagnostic] Initializing World
[SK diagnostic] Initializing Sprites
[SK diagnostic] Initializing Lines
[SK diagnostic] Initializing UI
[SK diagnostic] Initializing Renderer
[SK diagnostic] Initializing Physics
[SK diagnostic] Initializing Input
[SK info] Initialization successful
[SK warning] [spider/scene.gltf] Too many texture coordinate channels! Only one supported, the rest will be ignored.
[SK info] Animation: warte_pose 3.79167s
[SK info] Animation: walk_ani_vor 1.29167s
[SK info] Animation: walk_left 1.29167s
[SK info] Animation: run_ani_vor 0.66667s
[SK info] Animation: walk_ani_back 1.29167s
[SK info] Animation: run_ani_back 0.66667s
[SK info] Animation: run_right 0.66667s
[SK info] Animation: Attack 1.16667s
[SK info] Animation: fall 0.83333s
[SK info] Animation: run_left 0.66667s
[SK info] Animation: die 3.04167s
[SK info] Animation: Jump 1.25s
[SK info] Animation: walk_right 1.29167s
[SK info] Animation: die 2 1.41667s
[SK info] Session Performance Report:
[SK info] ______________________________________________________
[SK info] |         System | Initialize |   Update |  Shutdown |
[SK info] |________________|____________|__________|___________|
[SK info] |       Defaults |    56.17ms |          |    0.00ms |
[SK info] |     FrameBegin |            |  0.587ms |           |
[SK info] |          Input |     1.24ms |  0.008ms |           |
[SK info] |        Physics |     0.08ms |  0.037ms |    0.00ms |
[SK info] |       Renderer |     0.41ms |  0.002ms |           |
[SK info] |             UI |     0.60ms |  0.004ms |    0.40ms |
[SK info] |       Platform |   524.70ms |          |    8.55ms |
[SK info] |            App |    56.85ms |  0.102ms |           |
[SK info] |      Animation |            |  0.097ms |    3.76ms |
[SK info] |          Lines |     0.15ms |  0.004ms |    0.00ms |
[SK info] |        Sprites |     0.30ms |  0.000ms |    0.00ms |
[SK info] |           Text |            |  0.001ms |    0.00ms |
[SK info] |         UILate |            |  0.001ms |    0.00ms |
[SK info] |          World |     0.33ms |  0.000ms |    0.01ms |
[SK info] |    FrameRender |            |  0.054ms |    0.01ms |
[SK info] |         Assets |     0.05ms |  0.001ms |    0.01ms |
[SK info] |          Audio |   223.71ms |  0.001ms |    0.02ms |
[SK info] |________________|____________|__________|___________|

```

**Comment by jackdaus** [comment]
I've also just found another possible bug related to using this spider gltf in SK. 

When I load the spider model in SK and run the **DotNet** application (with either fallback screen or Quest 2 + Link), the spider model loads.

However when I run the **Android** application, the model fails to load. Let me know if it'd be helpful to open a separate issue and I can do that!

**Comment by maluoi** [comment]
Hey there, thanks for this one as well! I can confirm that there's something odd happening as the animation loops back around to the start. I've been digging around in this a bunch today, but haven't stumbled across what specifically is causing it yet! I _have_ managed to fix an unrelated issue or two in this code though, so thanks for pointing me to that spider model :)

I will continue to hunt this one down, but I figured I'd post an update here as it is taking a bit to find. I'll look into the Android issue after I've finished with this one! I suspect it should be pretty straightforward to reproduce, so no worries about a separate issue or anything.

**Comment by maluoi** [comment]
Okay, I think I got the animation issue solved! Looked like it was trying to blend between two frames of a single frame animation curve 😅 I may try and do a preview build on Monday, or towards the start of the week so you can get access to a few of these fixes :)

**Comment by jackdaus** [comment]
Woohoo glad you tracked it down! 😄
I'm not in any rush to get the fix, so feel free to hold off on the next release until it is convenient for you

**Comment by maluoi** [comment]
So the Android issue was likely a file path slash issue! The Model loaded just fine for me there, but if I used a `\` instead of a `/`, it would fail to find the Model. I did just add in some code that will auto-convert slashes for the current platform when loading files, so that'll also be in the preview build :)

**Comment by maluoi** [comment]
Okay, v0.3.7-preview.1 is up now and contains fixes for this! I'll close this issue now, but please feel free to re-open it if the problem persists :)
