### ISSUE TITLE
Small Solid.AddBox dimensions do not work as expected

### ISSUE THREAD

**Issue by jackdaus** [StereoKit/StereoKit#406]
## Description
When using `Solid.AddBox` with small values for the dimension (such as `V.XYZ(0.1, 0.1f, 0.1f)`), the physics do not seem to work as expected. Specifically, the solid does not seem to collide with another solid!

In the physics demo, if we make the solid's physical shape very small, then the helmet will fall through the floor!

To reproduce the problem, you can try replacing these lines from the physics demo (https://github.com/StereoKit/StereoKit/blob/master/Examples/StereoKitTest/Demos/DemoPhysics.cs):

Replace
```
objects.Last().AddSphere(.45f, 40, V.XYZ(0,0,0.05f));
objects.Last().AddBox(Vec3.One * .35f, 40, V.XYZ(0, 0, 0.05f));
```
with 
```
objects.Last().AddBox(Vec3.One * 0.1f, 40, V.XYZ(0, 0, 0.05f));
```

Now the helmet passes through the floor solid instead of bouncing :o

## Platform / Environment
I am using the flatscreen simulator. This is a C# project using SK version 0.3.7-preview.1. My graphics card is NVIDIA GeForce GTX 1650 Ti with Max-Q Design.

## Logs or exception details
No errors in the log :/

**Comment by jackdaus** [comment]
Ah I think I found the issue! I think since the floor height is soooo small in this demo, when the helmet's solid also has a small height, the helmet _wizzes_ past the floor solid and the collision is not detected. So I was able to work around this issue by increasing the floor's solid's height from
`floorSolid.AddBox(new Vec3(20, .01f, 20));`
to 
`floorSolid.AddBox(new Vec3(20, .1f, 20));`

Another workaround is to decrease the starting height of the helmet. This prevents it from accelerating too much before floor impact. I changed the starting height from 3 to 0 by replacing line 54 with `objects.Add(new Solid(new Vec3(0, 0, -.6f), Quat.LookDir(0,0,1)));`

**Comment by maluoi** [comment]
This does sound like the classic "speedy physics object" problem, where the rigidbody can travel completely past other objects in a single frame without ever touching it to spark collision events! Making the floor box thicker is absolutely the best solution in this particular case! If you have a solid floor, definitely crank that thickness up! Go for like 1000 or something, and move it down by 500 :)

In a more robust physics solution, you might also be able to solve this with some interpolated or continuous collision detection mode. I don't believe the physics engine SK is currently using has this built in? I don't see it at a casual glance at least, so this may not be trivial to add just yet. But that does mean there's definitely no SK API that'll do this yet!

**Comment by jackdaus** [comment]
Great thanks! I'll crank up that floor thickness and I'll be good to go on this one.
