### ISSUE TITLE
[Docs-Hand] Bounds example confusion

### ISSUE THREAD

**Issue by jackdaus** [StereoKit/StereoKit#409]
This might not be a bug, but I thought it would be worth mentioning since it tripped me up and might be a point of confusion for others. 

I was running this example code found at https://stereokit.net/Pages/Reference/Hand.html:
```
// A volume for checking inside of! 10cm on each side, at the origin
Bounds testArea = new Bounds(Vec3.One * 0.1f);

// This is a decent way to show we're working with both hands
for (int h = 0; h < (int)Handed.Max; h++)
{
	// Get the pose for the index fingertip
	Hand hand      = Input.Hand((Handed)h);
	Pose fingertip = hand[FingerId.Index, JointId.Tip].Pose;

	// Draw the fingertip pose axis if it's inside the volume
	if (testArea.Contains(fingertip.position))
		Lines.AddAxis(fingertip);
}
```

I experimented by enlarging the Bounds from `Bounds(Vec3.One * 0.1f)` to `Bounds(Vec3.One)`. But after I made the change, I found that the `testArea` always contained a `fingertip`!

I was using the fallback flatscreen simulator. Turns out the Handed.Left was the culprit. Even though the left hand was not rendered in the simulator, it was somehow contained in the bounds. 

Not sure if this is a bug or the correct behavior, but it left me pretty confused for a while!

**Comment by maluoi** [comment]
That's a really excellent point!

I've generally decided that inactive hands should preserve their last known position. If the hand hasn't been seen before, that's an interesting variation that I'll have to think about!

I'd 100% agree that the sample is not correct though, there should absolutely be a check against `IsTracked` in there, and I'll add that right now :)
