### ISSUE TITLE
Return value from sound_read_samples

### ISSUE THREAD

**Issue by sandrist** [StereoKit/StereoKit#427]
Is there a reason for returning 0 from [sound_read_samples](https://github.com/StereoKit/StereoKit/blob/e461102ec8b486e5d9bffc5ecb38586b08d0f9cd/StereoKitC/asset_types/sound.cpp#L114) when 1 sample was read?

I'm encountering some weird behavior when the microphone truly has 1 unread sample available, but this method says 0 samples were read...

**Comment by maluoi** [comment]
Yeah, that behavior definitely does look pretty weird! I honestly don't remember why this code is the way it is, but removing it doesn't seem to fix any of the strange behavior, or change much at all.

However! I spent the evening re-writing a bunch of this code, and I did get it to a point where my tests are all returning the right numbers :) I still have some cleanup and polish remaining to do, but I think I'll have a fix for this sometime tomorrow.

**Comment by sandrist** [comment]
Wow, thanks for the quick response and coding efforts!

There's no urgency for a quick fix on my end, so take your time. I can work around it for now by waiting until more than 1 unread sample is available, which seems to work fine. Just thought I'd point it out because I couldn't quite make sense of the initial behavior.

**Comment by maluoi** [comment]
Yeah, no problem! I did fit this into the v0.3.7-preview.2 release that just went out, so it's available now! :)

Should all be great now, but feel free to pop this back open if you're still seeing anything weird!
