### ISSUE TITLE
Mobile AR Support

### ISSUE THREAD

**Issue by suyashjoshi** [StereoKit/StereoKit#437]
## Describe the feature
Support for Android and iOS platforms

## An example use-case
It would be nice to add support for hand tracking, 3D file rendering, scene creation in mobile platforms like on Android and iOS using this library

**Comment by maluoi** [comment]
Heyas! Thanks for expressing interest, it's always good to know how many people are interested in this.

Right now, I consider phone-based AR such as AR Core AR Kit to be _out of scope_ for StereoKit. They are a non-trivial amount of work for what is essentially a stepping stone to headset based XR! StereoKit may gain some measure of phone support when WebXR is added to the XR backends, but this is the only related work item that's currently scheduled.

There are a few cases where I'd consider adding phone based AR to StereoKit:
1. AR Core or AR Kit implement an OpenXR runtime.
2. A community member submits a working implementation.

Even in these cases, the implementation should not in any way impede StereoKit's primary focus on headset based XR.

**Comment by suyashjoshi** [comment]
ok
