### ISSUE TITLE
ButtonImg appears to zfight

### ISSUE THREAD

**Issue by Zee2** [StereoKit/StereoKit#440]
## Description
The image on `ButtonImg` appears to flicker/fade/zfight/etc as the button is pressed.

## Platform / Environment
This is using the Universal template, with the `DotNet` target. Repros both in-HMD and flatscreen/simulator.

![image](https://user-images.githubusercontent.com/5544935/180916805-f4bb7822-0ee3-417c-94d7-a0031c211aaf.png)
![image](https://user-images.githubusercontent.com/5544935/180916772-e1e3d670-a68f-4bca-8b01-943c51a03812.png)

## Logs or exception details

https://user-images.githubusercontent.com/5544935/180916665-0237f191-b87b-4b0f-b86f-b65021b540d9.mp4

**Comment by maluoi** [comment]
v0.3.7-preview.3 is now up, and contains the fix for this :)

**Comment by Zee2** [comment]
Woohoo! 🥰🥰🥰
