### ISSUE TITLE
StereoKitCTest：Microphone

### ISSUE THREAD

**Issue by juntao-huang** [StereoKit/StereoKit#442]
## Description
There was no response when I clicked on the microphone

## Platform / Environment
oculus quest2

## Logs or exception details
```
[SK warning] Mic start failed, 'Permission denied'
```
<img width="465" alt="搜狗截图20220726121102" src="https://user-images.githubusercontent.com/66586670/180921506-05dc7dec-abd0-4dce-960f-b92561862f21.png">

**Comment by maluoi** [comment]
I'm not able to reproduce this error in my current environment! I'm using Quest2 + Link, and the StereoKitC project on x64 Debug, same as you. "Permission Denied" is a bit of a strange error to encounter is this context, and I'm not certain that I know of any tools Win32 has to prevent this?

There may be some configuration settings for Windows here that may be involved? Not sure.

**Comment by maluoi** [comment]
No response, can't repro. Closing for now, feel free to re-open if additional details come up.
