### ISSUE TITLE
Zero width UI layout causes UI.Text to crash

### ISSUE THREAD

**Issue by Zee2** [StereoKit/StereoKit#446]
## Description
Calling any SK API (I think?) from a lambda results in an `AccessViolationException`. This is sort of weird because the Step function itself is a delegate, so...?

Seems to happen regardless if the lambda is static, or a local, or even regardless of when it's called. (It's not being called before Init, or the library is loaded, etc) This isn't async or threaded, I'm just invoking the lambda directly in lockstep in my `Step()` function.

## Platform / Environment
Universal Template, DotNet target, running on desktop (flatscreen or Quest Link or, really, anything, haha)

## Logs or exception details
<img width="674" alt="image" src="https://user-images.githubusercontent.com/5544935/181820211-6eeaedeb-f9a2-452d-a3a6-06438c31254f.png">

**Comment by Zee2** [comment]
This is actually getting to be super annoying haha. I really _really_ like anon functions and lambdas in C# and not being able to use them is a big bummer.

If you support them, it'll allow for really nifty things like composable draw functions....

**Comment by maluoi** [comment]
Okay, so this does not look like an issue with lambdas or Actions or anything like that! The root cause here is trying to draw UI text without any UI layout present. Zero width layout is basically throwing it an impossible text layout problem, and it's not handling it very well!

**Comment by Zee2** [comment]
Hmmm.... I'm pretty sure I was doing a valid layout in an earlier test. Let me give it a shot.
