### ISSUE TITLE
GLTF extras

### ISSUE THREAD

**Issue by maluoi** [StereoKit/StereoKit#447]
## Describe the feature
GLTFs have an "Extras" feature that's basically a Key/Value pair list. This could be really nice to have access too, especially since Blender is able to populate these fields! ModelNodes would also need an API for accessing this data.

![image](https://user-images.githubusercontent.com/8484884/181996678-1ca4f2c6-9ca1-4b16-ac12-dafeb73d5024.png)

```json
{
    "extras" : {
        "Name" : "Switch"
    },
    "name" : "Button01",
    "translation" : [
        -0.07500000298023224,
        0,
        -0.11999999731779099
    ]
},
```
## An example use-case
Tagging UI data, or solid/visible attributes. This is basically a better way of implementing the `[solid]name` tagging system used in the StereoKit samples so far.

**Comment by Zee2** [comment]
Ooooh, so that's what the Blender custom properties window does, lol
