### ISSUE TITLE
ButtonImg does not actually draw a button of size "size"

### ISSUE THREAD

**Issue by Zee2** [StereoKit/StereoKit#448]
## Description
The "size" parameter to `ButtonImg` doesn't seem to work correctly. `UI.ButtonAt` and `UI.Button` both create buttons of size `size`, but `ButtonImg` does something... else?

![image](https://user-images.githubusercontent.com/5544935/182612584-73253246-b39c-41f3-85c8-ceb498c82dc2.png)

![image](https://user-images.githubusercontent.com/5544935/182612367-830b0b2e-0266-4d6e-8a05-3fad60cb1c0f.png)

All three of these buttons have the argument `size = new Vec2(0.032f, 0.032f)`, which should result in a 32mm by 32mm button. However, `ButtonImg` seems to have its own opinion of what 32mm is!

## Platform / Environment
SK Universal Template, currently on Dotnet target.

**Comment by maluoi** [comment]
Yeah, it was just a bad padding flag, easy fix!
![image](https://user-images.githubusercontent.com/8484884/182672346-545e3f4d-2098-4603-aa6b-7e795e90237c.png)

**Comment by maluoi** [comment]
v0.3.7-preview.3 is now up, and contains the fix for this :)
