### ISSUE TITLE
Could we expose the bool flag for calculating bounds in `Mesh.SetVerts`?

### ISSUE THREAD

**Issue by austinbhale** [StereoKit/StereoKit#456]
## Describe the feature
I noticed the default case is true, which isn't able to be set to false from the C# interop.

Thanks! :)

**Comment by maluoi** [comment]
Oh good call, thanks for catching that! This is in `/develop` now. I also added `Mesh.SetData` while I was in there, if you're ever setting both verts and inds at the same time, it's a small win too :)

c7e82b9c3a1df39ae035531a2f4032ca06c6b62e

**Comment by austinbhale** [comment]
Sweet, you're the man!

**Comment by maluoi** [comment]
I'm gonna leave this open until it goes into a preview build, it's a little easier for me to track that way :)

**Comment by austinbhale** [comment]
Hey Nick! Is there a preview.4 release on the roadmap? It's not really blocking but just curious when to expect a Nuget release after this issue. Thanks :)

**Comment by maluoi** [comment]
I've been doing a lot of work on a branch that hasn't gotten merged into /develop yet, so I haven't been shipping a ton of preview builds lately! I do preview builds either on request, or critical mass :D

I can look into doing a small release towards the end of the week to make this available, it has been a little long.
