### ISSUE TITLE
Platform.WriteFile adds extra \0 character on Windows

### ISSUE THREAD

**Issue by jackdaus** [StereoKit/StereoKit#477]
## Description
When I use StereoKit's Platform.WriteFile to write a file to the filesystem, the resulting file ends up getting an extra `\0` character appended.

Here's the code to reproduce the issue:
```cs
using StereoKit;
using System;
using System.IO;


// Initialize StereoKit
SKSettings settings = new SKSettings
{
    appName = "FileEndsInNull",
    assetsFolder = "Assets",
};
if (!SK.Initialize(settings))
    Environment.Exit(1);


// Create assets used by the app
Pose cubePose = new Pose(0, 0, -0.5f, Quat.Identity);
Model cube = Model.FromMesh(
    Mesh.GenerateRoundedCube(Vec3.One * 0.1f, 0.02f),
    Default.MaterialUI);

File.WriteAllText("system-written.txt", "Hello World!");
Platform.WriteFile("platform-written.txt", "Hello World!");


// Core application loop
while (SK.Step(() =>
{
    UI.Handle("Cube", ref cubePose, cube.Bounds);
    cube.Draw(cubePose.ToMatrix());
})) ;
SK.Shutdown();
```

When I open both of the files (system-written.txt and platform-written.txt) created from the demo code above, I find that one of the files has an extra '\0' character. 
![image](https://user-images.githubusercontent.com/53974525/190920876-74457730-c925-49d3-946a-173abc936778.png)

## Platform / Environment
- Windows 11
- Flatscreen simulator
- C#
- Using the latest StereoKit .NET Core template
- StereoKit 0.3.6 and 0.3.7-preview.4

## Also
It looks like this behavior changed from v0.3.5 => v0.3.6. SK 0.3.5 didn't have the appened `\0`

**Comment by maluoi** [comment]
Thanks for pointing this out! Just put in a fix for it, should work a lot better now when the next build goes out :)

**Comment by jackdaus** [comment]
Awesome thanks!

**Comment by maluoi** [comment]
This is now in v0.3.7-preview.5!
