### ISSUE TITLE
Suggested improvements for keyboard positioning

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#478]
# UIMove
## Describe the feature
The virtual keyboard and file picker windows use UIMove.FaceUser. I don't use this mode with any of my windows because I find that it always feels off centre and uncomfortable to use. Can you please have a global setting that lets you configure the default UIMove mode for system generated window like these.

## An example use-case
I would set UIMove to Exact so that it is consistent with all the other windows in my project.

# Default position
## Describe the feature
When the virtual keyboard is displayed it typically overlaps the window I am trying to edit and I need to grab it and move it into a more suitable position. Sometimes that overlap is quite extreme so I have to be careful to grab the keyboard rather than the window. 
When the small numeric keyboard is used it can be completely obscured by the window.

A suggested solution is:
1) Get the plane of the input control that just caused the virtual keyboard to activate.
2) Move the keyboard towards the player position until the keyboard is in front of the plane.

Thanks.

**Comment by maluoi** [comment]
Hey yeah, thanks for this! These are both really excellent suggestions, and I agree entirely with both.

The keyboard position one has some pretty clear and straightforward solutions to it, so I'll probably add that today. I'm still thinking a bit about what the default `UIMove` setting should look like, and where it should go, but I'll try and get that in soon as well.

**Comment by maluoi** [comment]
Whups, wrong issue number, ce2a6568494a80dae59174d11ed58e04a4d7a049 belongs here too! :D

I'm still a little iffy about the way I've added UI.SystemMoveType, I kinda feel like a good solution might include a bit more in the way of options. I'll revisit this a bit more with theming later, but in the meantime this should probably work fine for your needs :)

I'll try and have a preview build up this week with these changes!

**Comment by maluoi** [comment]
v0.3.7-preview.5 is up and contains these items! Let me know what you think of 'em, and feel free to re-open this if it's not what you envisioned.

**Comment by Jumbli** [comment]
Tested. That feels much better, thank you :)
