### ISSUE TITLE
Different instances of the same model seem to share model node poses 

### ISSUE THREAD

**Issue by slitcch** [StereoKit/StereoKit#480]
## Description
In my mirror dwelling app, I display two instances of my avatar model. One of them is displayed on top of my body, the other one is "mirrored" across an arbitrary axis. I want to set the scale of the head node to 0 for the instance on top of my body so that my vision is not obstructed, but I want the mirrored instance to have the head displayed normally. 

This should have been accomplished by calling `model_node_set_transform_model` on both models, one with a zeroed-out head pose, but they both ended up either scaled normally or with zero scale, depending on which one I assigned last. I believe this is caused by StereoKit keeping only one model node data representation around per filename, and I got around this by just copying the avatar file and loading from two different filenames. 

I'm in a big hurry right now, I'll add a minimum reproducible snippet in a few days

## Platform / Environment
StereoKitC

**Comment by maluoi** [comment]
This is as designed! SK uses file names as IDs to prevent them from being loaded multiple times. There are two approaches for getting around this:

1. `Model.Copy` is intended to behave appropriately in the context of separate animations or poses per model, but will still share Materials, and some non-skinned meshes.
2. You can change the model's ID after loading it from file, then load the file again.

**Comment by slitcch** [comment]
`model_copy` works perfectly, thanks!
