### ISSUE TITLE
UI option to force horizontal space

### ISSUE THREAD

**Issue by austinbhale** [StereoKit/StereoKit#482]
## Describe the feature
The default behavior for `UI.Space` is to add vertical space at the start of new lines and add horizontal space in the current line. At the start of new lines, it would be nice to have the option to add only horizontal space. 

## An example use-case
I'd like to position text in a line below a UI element (e.g., text below the cursor of an HSlider).

**Comment by maluoi** [comment]
I'm definitely interested in having a separate horizontal and vertical space functionality! I could also be interested in adding something like this directly to the HSlider sometime in the future :)

For this particular issue in the near-term, I might recommend using `UI.LayoutLast` and `Text.Add` for placing text on the HSlider! This should be a much more durable way to implement placing your text!

**Comment by austinbhale** [comment]
Awesome, thanks Nick! The alternative near-term solution tip was very helpful :) (though I couldn't get it _perfectly aligned_ with the Text's bounding box scale, it was close enough!). Having the horizontal space option will feel much less hacky in the future.

If you want to try it out, I posted a script that uses the text-render way up here: https://gist.github.com/austinbhale/c7bb0cef3676259c369cf3e2fe45e962
