### ISSUE TITLE
Can we have a UI.SetElementVisual for "Panel"?

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#484]
## Describe the feature
Can we please have a UI.SetElementVisual for "Panel". I think it currently uses Button with a reduced z-scale. This is giving me issues because I have set up a drop shadow for my button and the panel is so thin it's getting z fighting issues on the Quest and goes all fuzzy.

UI.Button also doesn't have a UI.SetElementVisual so appears inconsistent with developer-created styles. I could just replace it with a regular button so this is not a high priority though.

Thanks,

**Comment by maluoi** [comment]
Should be able to do the Panel bit pretty easily!

Could you clarify what you mean by the `UI.Button` bit here? There is a `UIVisual.Button` that does work, iirc, did you mean some other element, or within a particular context?

**Comment by Jumbli** [comment]
Sorry, I meant the round button.

**Comment by maluoi** [comment]
Oh! Yeah okay that one, will do :)

**Comment by maluoi** [comment]
v0.3.7-preview.5 is up and contains these items! Let me know what you think of 'em, and feel free to re-open this if it's not what you envisioned.

**Comment by Jumbli** [comment]
Panel is not working because it still uses ui_vis_button rather than the newly added ui_vis_panel. 
I'm not sure how to reopen the issue, but I think it's a quick fix anyway.
ButtonRound is working fine.

**Comment by maluoi** [comment]
Ahh, you are totally right! Sorry about that. Fix for panel is in, and I'll try not to take too long with the next preview build.
