### ISSUE TITLE
ERROR (OpenXR) : [SyncCurrentActionDeviceStates] Suggesting bindings not provided for current interaction profile.

### ISSUE THREAD

**Issue by halilibrahim** [StereoKit/StereoKit#490]
## Description
I'm getting an error on device telling that "The OpenXR application has provided no bindings for the current input device. Performin best-effort mapping to application defined bindings." on StereoKit application launch.
![Error message on device](https://user-images.githubusercontent.com/5882923/195832883-4622a86e-f6a7-4b25-a5fd-7a356cb4c396.png)
Message dissapears after a few seconds by itself or by clicking the close button. 
And it shows as below in the logs:
ERROR (OpenXR) : [SyncCurrentActionDeviceStates] Suggesting bindings not provided for current interaction profile. Current interaction profile has been mapped to /interaction_profiles/microsoft/motion_controller

I've also tried with [SKTemplate-Universal](https://github.com/StereoKit/SKTemplate-Universal).

## Platform / Environment
Device: Hololens 2
Windows version: 20348.1518.arm64fre.fe_release_svc_sydney_rel_prod.220906-1328
OpenXR Runtime Version: 111.2208.18003.0
OpenXR Preview Runtime Version: 112.2209.30002.0
OpenXR Services Version: 111.2208.18003.0
OpenXR Developer Tools App Version: 112.2209.30002.0

## Logs or exception details
[log.txt](https://github.com/StereoKit/StereoKit/files/9785446/log.txt)

**Comment by maluoi** [comment]
Yeah, this was introduced in a recent OS update! I have a fix for this on /develop right now, but that hasn't made itself into a build yet. I'll ping this issue when that build is up.

**Comment by maluoi** [comment]
v0.3.7-preview.5 is up and contains a fix for this!
