### ISSUE TITLE
Please parameterise UI color focus multiplier

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#506]
## Describe the feature
I believe that when you give focus to an input or change a toggle button state to pressed, it's colour (UIColor.Common) is multiplied by 2. This is fine if UIColor.Common is a dark colour, but the change can be too extreme for lighter buttons which then makes the text difficult to read.

Can you please parameterise the multiplier so we can have more flexibility when choosing our colour schemes.

## An example use-case
I'd like the change in "activated button" and input colours to be much more subtle than the following:
![SampleColours](https://user-images.githubusercontent.com/10079865/199947695-04756cd0-28cb-4b6f-b85d-2096e0556311.png)

**Comment by maluoi** [comment]
Would a `UI.SetThemeColor` that takes a regular color _and_ a highlight color be a reasonable approach for you?

**Comment by Jumbli** [comment]
Yes, that would be great :)

**Comment by maluoi** [comment]
Okay, this will be in the next build! Note that if you're using custom UI shaders, you may need to make some small adjustments (see: https://github.com/StereoKit/StereoKit/commit/842bfff881c435cdff1c14a26f673343cb9969d3#diff-180a23d97a296b1b12c12afd229fc03542b0df216b5741b7ed2b0613ef732ef7), as the app is now providing more specific colors to the shader.

This ended up being an overload for `UI.SetThemeColor` that also takes a `UIColorState`, allowing you to separately change colors for the `Active`, `Normal`, and `Disabled` states :)

**Comment by maluoi** [comment]
The build is up, let me know if you need anything more!
