### ISSUE TITLE
Missing/mismatch in shared libs with VS Code on Linux

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#507]
## Description

I'm following the VSCode guide at https://stereokit.net/Pages/Guides/Getting-Started-VS-Code.html on Linux. It appears some native shared libs are missing, either because the StereoKit package expects them to be installed globally, or perhaps due to some project dependency that wasn't added. 

When running `dotnet run` in a terminal window within VS Code I get:

```
melis@juggle 15:50:~/concepts/skmap$ dotnet run
[SK error] Failed to load StereoKitC!
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'StereoKitC' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libStereoKitC: cannot open shared object file: No such file or directory
   at StereoKit.NativeAPI.sk_run(Action app_update, Action app_shutdown)
   at StereoKit.SK.Run(Action onStep, Action onShutdown) in C:\Data\Repositories\Stereo Kit\StereoKit\SK.cs:line 199
   at Program.Main(String[] args) in /home/melis/concepts/skmap/Program.cs:line 9
```

Looking a bit closer with `LD_DEBUG=all dotnet run` it seems `/home/melis/concepts/skmap/bin/Debug/net6.0/runtimes/linux-x64/native/libStereoKitC.so` is not finding two libs:

```
melis@juggle 15:53:~$ ldd /home/melis/concepts/skmap/bin/Debug/net6.0/runtimes/linux-x64/native/libStereoKitC.so |grep not
	libGLEW.so.2.1 => not found
	libjsoncpp.so.1 => not found
```

I have both GLEW and jsoncpp installed as system packages, but the shared lib versions don't match. And I don't see them in the native code dir within the project:

```
melis@juggle 15:55:~/concepts/skmap/bin/Debug/net6.0$ find . -name libGLEW\*
melis@juggle 15:55:~/concepts/skmap/bin/Debug/net6.0$ find . -name \*jsoncpp\*
melis@juggle 15:55:~/concepts/skmap/bin/Debug/net6.0$ 
```

Should these be installed separately through `dotnet add package`?

## Platform / Environment

Arch Linux, VS Code 1.66.0, dotnet 6.0.110

**Comment by maluoi** [comment]
Ahaaa, I suspect this could be the same as #485! The libGLEW and libjsoncpp version bits you've called out here are probably the details I've been missing, this all makes a lot more sense now.

I don't really know what exactly is the best way to handle this as a Linux user, ( I am still a Linux novice :( ) but I think there's some work I can do on the build side to make this smoother.

**Comment by maluoi** [comment]
FYI, I did write what I believe should be a fix for this! It'll be in the next build :)

**Comment by TrueGeek** [comment]
I've updated to v0.3.7-preview.6 and I'm still seeing this same issue. 

I'm on an M1 Mac. @paulmelis do you still see this on Linux?

**Comment by maluoi** [comment]
@TrueGeek Could you clarify on what you mean by M1 Mac? Are you running Linux on your Mac, or is this MacOS? SK doesn't currently support MacOS, so there's probably a number of different things that might trip up StereoKit in ways that might look like this.

**Comment by TrueGeek** [comment]
Ah, that would explain it. Yes, I'm on MacOS.

**Comment by paulmelis** [comment]
For completeness, just tested v0.3.7-preview.6 on Linux and the issue is gone!

**Comment by maluoi** [comment]
That's awesome to hear! Thanks so much for verifying that! :D
