### ISSUE TITLE
Toggle image button

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#514]
## Describe the feature

Just as we have `Button` and `ButtonImg` would be good to have a `ToggleImg`

**Comment by maluoi** [comment]
Should be easy enough! I did just start working on this, it's mostly boilerplate code, but I'll get it in :)

**Comment by maluoi** [comment]
![SKImageToggle](https://user-images.githubusercontent.com/8484884/201235788-c60781d8-a40b-404c-8de0-2d58f1b32b9a.gif)

Images are provided by argument, but here ya go! Will be in the next build :)

**Comment by maluoi** [comment]
This is now up in v0.3.7-preview.6!
