### ISSUE TITLE
Download into "Special Folder" on Android issue

### ISSUE THREAD

**Issue by ClonedPuppy** [StereoKit/StereoKit#517]
## Description
Using the library FluentFTP, downloading a file(s) to the "Special Folder" on Android
`Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)`
Does not work in SK builds over 0.3.6 Final. Breaks in 0.3.7 preview-1.

## Platform / Environment
Quest 2. Works on Windows desktop.

## Logs or exception details
```
Nothing really useful to you I think, but let me know if you need anything.

**Comment by ClonedPuppy** [comment]
So this was a lot simpler than I had anticipated. When I wrote the code back in 0.3.6, I used @"\" to build file path strings, however once 0.3.7-Previews started coming out, this only works if I change the backslash to a forward slash, such as @"/" which is proper on linux flavored systems, and perhaps ok on Win11 too now? 

Not sure what changed under the hood, but as it's working fine for me I'll close this issue!

**Comment by maluoi** [comment]
Windows will take whatever slash you throw at it, yeah! But on Linux based systems, you need to make sure you get case sensitive and everything, it's waaay pickier. Glad this worked out for you! I'll have to find a good way to at least message this, maybe a doc on platform compatibility? 🤔
