### ISSUE TITLE
VS 2022 MSbuild does not Compile HLSL files in SK 0.3.7 preview 6 (works in preview 5)

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#537]
## Description
HLSL files don't get compiled when the build is invoked. I tested by dropping back to preview 5 from preview 6 and executing a "rebuild" on the project.

## Platform / Environment
Windows 11, VS 2022 17.4.2, SK 0.3.7 preview 6

## Logs or exception details
output from the build from preview 5 (does not appear in preview 6):
5>Compiling Assets\holographic_quadrant.hlsl..
5> ________________
5>|--Buffer Info--
5>|  StereoKitBuffer - 784 bytes
5>|    sk_view        : +0    [  128] - flt32
5>|    sk_proj        : +128  [  128] - flt32
5>|    sk_proj_inv    : +256  [  128] - flt32
5>|    sk_viewproj    : +384  [  128] - flt32
5>|    sk_lighting_sh : +512  [  144] - flt36
5>|    sk_camera_pos  : +656  [   32] - flt8
5>|    sk_camera_dir  : +688  [   32] - flt8
5>|    sk_fingertip   : +720  [   32] - flt8
5>|    sk_cubemap_i   : +752  [   16] - flt4
5>|    sk_time        : +768  [    4] - flt1
5>|    sk_view_count  : +772  [    4] - uint1
5>|  TransformBuffer - 65520 bytes
5>|    sk_inst        : +0    [65520] - misc819
5>|  $Global - 16 bytes
5>|    color          : +0    [   16] - flt4
5>|--Vertex Shader--
5>|  b1 : StereoKitBuffer
5>|  b2 : TransformBuffer
5>|--Pixel Shader--
5>|  b1 : StereoKitBuffer
5>|  b0 : $Global
5>|________________
5>Compiled successfully to C:\Users\JLarryAultman\source\PL-3D\Engines\SK-MRDL\bin\Debug\netstandard2.0\Assets\holographic_quadrant.hlsl.sks
5>

**Comment by laultman** [comment]
Additional information about the issue. Rolling back to preview 5 generates the .sks file as expected. Then having the .sks file on disk and copying it to the destination folder in another project AND updating the nuget to preview 6. The next build with preview 6 deletes the .sks file on build from the output folder.

**Comment by maluoi** [comment]
This is fixed in 49777e25ac713ae317f46c54d69c7036e74aa577, and I should have a new preview build up this week!

**Comment by maluoi** [comment]
v0.3.7-preview.7 is now available on NuGet, please feel free to re-open if the problem persists :)

**Comment by laultman** [comment]
Tested, fixed!
