### ISSUE TITLE
Drawing with Text.Add does not show text in Window

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#540]
## Description
Using this simple window does not draw text:

			UI.WindowBegin(MenuHeaderText, ref infoPose, infoPoseSize * U.cm);
			StereoKit.Text.Add(DisplayText, Matrix.TR(new Vec3(0f, 0, -0.001f), Quat.LookDir(0, 0, -1)), 
				infoWindowSize, TextFit.Wrap, style,
				TextAlign.XLeft, TextAlign.CenterLeft, infoWindowCenter.x);
			UI.WindowEnd();

Where the infoPoseSize is a Vec2 30,16 and infoWindowsSize is a Vec2 = infoPoseSize * .999f.
DisplayText is multiple lines of text with new line characters.
The goal is to draw text inside the Window left aligned inside a margin box. 

			UI.WindowBegin(MenuHeaderText, ref infoPose, infoPoseSize * U.cm);
			StereoKit.Text.Add(DisplayText, Matrix.TR(new Vec3(0f, 0, -0.001f), Quat.LookDir(0, 0, -1)), 
				infoWindowSize, TextFit.Overflow, style,
				TextAlign.Center, TextAlign.Center, infoWindowCenter.x);
			UI.WindowEnd();
Text center is drawn centered on the infoWindowSize top left corner.

Any setting of TextAlign other than Center, no text is visible.

## Platform / Environment
Windows 11, VS 2022, SK 0.3.7 preview 7

## Logs or exception details
```
Logs are super helpful, please include them if they're at all relevant!
```
_If you have an exception, details about that would also be essential._

**Comment by maluoi** [comment]
I was going to say the best way to do this would probably be `UI.Text` with a size overload, but it looks like I forgot to add that to the API! That was an oversight, and I'll be adding this shortly.

In the meantime, creating custom UI elements is something best done using StereoKit's `UI.Layout...` APIs, as they can give you specific positions on the UI, and also allow other elements to layout around them. I believe the specific issue you were falling into is that an X of 0 in local space is the center of the window, not the left side.

Anyhow, here's a quick example using `UI.LayoutReserve` to find the correct position!

```csharp
Pose infoPose       = new(0,0,-0.5f, Quat.LookDir(0,0,1));
Vec2 infoPoseSize   = new(10, 10);
Vec2 infoWindowSize = infoPoseSize * U.cm;
SK.Run(() => {
	UI.WindowBegin("Window", ref infoPose, infoWindowSize);

	Bounds bounds = UI.LayoutReserve(infoWindowSize);
	Vec3   at     = bounds.center + bounds.dimensions/2.0f;
	at.z -= 0.001f;

	Text.Add("Hello!", Matrix.TR(at, Quat.LookDir(0, 0, -1)),
		infoWindowSize, TextFit.Wrap, TextStyle.Default,
		TextAlign.XLeft, TextAlign.CenterLeft);

	UI.WindowEnd();
});
```

**Comment by maluoi** [comment]
UI.Text with size is now in v0.3.7-preview.8!
