### ISSUE TITLE
Calculating a `Pose` in front of the user

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#543]
In HoloLens 2, at startup in SK Remote Rendering there is no way to begin a scene from a known position relative to the world coordinates. Problem: User is standing at a point. We want to start/go "home" the application from that point and we want to place all elements in the scene based on a line directly in front of the user's head position. The head position is completely arbitrary only have meaning to the user in the mixed reality. The user wants all the visible assets in front of him. The position of the elements in the world coordinates has not yet been decided by the user.
Concrete example. User is at a conference demonstrating the HoloLens 2 with SK as the platform. The world location is unimportant. The person wants to stand at a point of beginning. Whatever direction his head is facing at the moment the app HoloLens 2 Remote Rendering Player connects the SK rendering should be the start position. And there is a need to repeat this where the user has a menu button that he pushes to "Start" and the scene begins at the current head position.
How could I accomplish this?

**Comment by maluoi** [comment]
If I understand correctly, I believe you're looking for [`Input.Head`](https://stereokit.net/Pages/StereoKit/Input/Head.html), which is a `Pose`! If you want that as a Ray, [`Input.Head.Ray`](https://stereokit.net/Pages/StereoKit/Pose/Ray.html) will give you a ray from the user's head pointing in the same direction as their face.

**Comment by maluoi** [comment]
I suspect that's only doing it for you by chance! You're replacing the entire `Pose`, so what you're doing there is the equivalent of:

```csharp
Pose scenePose = new Pose(0,0,-1.0f, Quat.Identity);
```

Is it possible you're looking for something more like this?

```csharp
Pose  scenePose = Input.Head;
float distance  = 1.0f;
scenePose += scenePose.Forward.X0Z.Normalized * distance;
```

**Comment by laultman** [comment]
Naturally, you are correct. The "by chance" part just happened to be the behavior of the Player app. When you push the "play" button on the Player app you are looking at the button, naturally. The Player app grabs the Head position and feeds that to the remote process. On subsequent runs using my solution it is oriented to my original Player position. That as you pointed out is not my real goal, which is to reorient based on the current position when the remote app starts NOT based on the orientation when the Player starts.

**Comment by maluoi** [comment]
I'll expand on this code a little, since it may not do orientation as desired. Didn't test it, but should be about right.

```csharp
Pose  head     = Input.Head;
float distance = 1.0f;

// Flatten the orientation, so it only keeps rotation on the Y axis.
Quat rot = new Quat(0, head.orientation.y, 0, head.orientation.w).Normalized;

// Remove Y axis movement from the direction
Vec3 dir = head.Forward.X0Z.Normalized;

// Assemble the final position, include a 180 flip so it faces towards the user
Pose scenePose = new Pose(
    head.position + dir * distance,
    rot * Quat.FromAngles(0, 180, 0));
```

**Comment by laultman** [comment]
This latest code does do what I have in mind. The interesting part is the orchestration with the rest of the scene and update loop code. By this I mean, I am storing the state of the scene at strategic points and recall them in case the user has removed the HL2 and later picked it back up.
But the good thing is it does do want I want it to do. With this, what I really need to do is refactor the update code I have and simplify. An interesting thing is the way the loop runs and the async code behavior.  I appreciate the help.
