### ISSUE TITLE
TextContext.Password not implemented

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#552]
## Description

It seems using `TextContext.Password` on a `UI.Input()` field has no effect, i.e. characters are not masked out? 

## Platform / Environment

Windows UWP, SK 0.3.7 preview7

**Comment by maluoi** [comment]
There may be some additional stuff I can do WRT native keyboards, but I suspect masking out the contents of the `UI.Input` were probably the most important feature here?

I've added this in, and it'll be in the next build :)

**Comment by paulmelis** [comment]
Great, thanks! Indeed, not having the password show was the main thing (although viewing a password in an XR headset already provides some security 😉)

**Comment by maluoi** [comment]
This is now in v0.3.7-preview.8!
