### ISSUE TITLE
Padding configuration Windows / Pannels / Buttons

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#556]
I believe UISettings.padding affects buttons and the padding around windows / panels. I was once told by a designer that if you place content close to the boundary of windows it will feel cluttered and more overwhelming, as though you are struggling to cram everything in. Adding some space looks more professional. The current padding helps by moving labels away from the edge, but it doesn't affect panels and text. Also if you increase the padding it adds it to buttons making them too chunky.

Maybe the following would help in UISettings:
Window padding - this adds space around the whole window and all content (panels, text, labels) will be affected.
Panel padding - works the same as window, but I may want a smaller padding value for panels.
Button padding - how chunky you want your buttons.

Thanks.

**Comment by maluoi** [comment]
I separated out a `margin` property! I'll start with just that and try and publish a build of this on Friday :)

![image](https://user-images.githubusercontent.com/8484884/211994755-6f05eff4-3aff-4e8f-9489-e07f9e88842f.png)

**Comment by maluoi** [comment]
This is now in v0.3.7-preview.8! Let me know if this is enough, or what specifically more might be needed.
