### ISSUE TITLE
Point Cloud generation from `Mesh.SetData` not rendering on Quest 2 in both Maui/Android projects

### ISSUE THREAD

**Issue by austinbhale** [StereoKit/StereoKit#558]
## Description
The point cloud mesh is not rendering, e.g., the initial sphere in the PointCloudDemo does not show in the StereoKitTest app. The `point_cloud.hlsl` shader seems to have copied properly, because I can successfully see a default mesh with this material applied: `Mesh.Cube.Draw(cloud.mat, cloudPose.ToMatrix(0.1f));`

Additionally, the `DemoGeo` example has a similar initialization with `SetData` for a custom mesh, so I tried applying the point cloud shader which worked(?) since it had a rainbow color effect.

I've tried changing the point sizes and cloud scale with no luck. Still investigating further with the indices now, so I'll update here if I find out anything.

## Platform / Environment
Android/Maui + Meta Quest 2. Tested on the universal template and SK from source.

**Comment by maluoi** [comment]
I can confirm this happens! I suspect there could be something related to the shader transpilation pipeline here. I can't build to Android right now, but if I were to guess, it could be the input vertex format!

Currently it's:
```cpp
struct vsIn {
	float4 pos  : SV_POSITION;
	float2 off  : TEXCOORD0;
	float4 color: COLOR0;
};
```

And it may need to look more like this:
```cpp
struct vsIn {
	float4 pos  : SV_Position;
	float3 norm : NORMAL0;
	float2 off  : TEXCOORD0;
	float4 color: COLOR0;
};
```

I'll try this out and verify a little later.

**Comment by austinbhale** [comment]
That fixed it, thanks Nick!

**Comment by maluoi** [comment]
Oh wow, okay, that was a good guess! :D I do have some changes in the works with the shader compiler that may help eliminate this category of issue in the future, but I'm not sure what version that'll land in just yet. It should come bundled with the custom vertex format work :)

**Comment by maluoi** [comment]
This fix is now in /master and /develop.
