### ISSUE TITLE
"Shader '....' has no valid stages!" when loading a shader from a thread on Android

### ISSUE THREAD

**Issue by emielch** [StereoKit/StereoKit#561]
## Description
Loading a shader from a thread on Android causes the shader to load improperly, printing the following error: `[StereoKit] [SK warning] sk_gpu: Shader 'app/floor' has no valid stages!`
For example when loading the floor shader in the Universal Template like this:
```csharp
public void Init() {
  Task.Run(() => {
      floorMaterial = new Material(Shader.FromFile("floor.hlsl"));
      floorMaterial.Transparency = Transparency.Blend;
  });
}
public void Step() {
  if (floorMaterial!=null)
      Default.MeshCube.Draw(floorMaterial, floorTransform);
}
```

## Platform / Environment
This works on windows desktop but doesn't on the Quest. I'm using StereoKit version 0.3.7-preview.7

**Comment by emielch** [comment]
Seems to be any shader, I tried two with the same problem. This is indeed the same floor.hlsl from the examples. No other relevant messages during compile time other than `File 'Assets\floor.hlsl' is already up-to-date, skipping...`. During runtime I'm actually getting the following two:
```
[StereoKit] [SK warning] sk_gpu: Shader 'app/floor' has no valid stages!
[StereoKit] [SK warning] material_create was provided a null shader, defaulting to an unlit shader.
```

**Comment by maluoi** [comment]
I was able to repro an issue and fix this using the OpenGL override on Windows, I still need to double check this on Android, but I'm pretty sure I got this fixed :) I'll have this in the next build, and I'll ping this thread when that's up!

**Comment by maluoi** [comment]
This is now in v0.3.7-preview.8!
