### ISSUE TITLE
Request for a `ConcurrentQueue` for the main thread callback

### ISSUE THREAD

**Issue by austinbhale** [StereoKit/StereoKit#568]
I'm having trouble with `SK.ExecuteOnMain` when using it from a different thread many times. This method would be very convenient for `ISteppers` since you can simply change their states from these other threads. Could this be a `ConcurrentQueue` instead of a `List` so that we can continuously enqueue and run tasks safely:
https://github.com/StereoKit/StereoKit/blob/9752f5d84aabd624ef51c639e26dee243f05f4c4/StereoKit/SK.cs#L15

**Comment by maluoi** [comment]
A good suggestion, ty! It probably should have started that way :)

**Comment by maluoi** [comment]
This is now in v0.3.7-preview.8!

**Comment by austinbhale** [comment]
Probably a separate issue but how do you feel about having something like `SK.ExecuteBeforeMain`, where it's the same functionality but just before stepping through the steppers?

For example, if I were to call `UI.Image(someSprite)` in a stepper and then flip the pointer to a different sprite in the main thread callback queue, then it wouldn't reflect the most recent change and possibly even contain invalid data for drawing?

**Comment by maluoi** [comment]
I've been wanting to do something like expose SK's system API, which could allow developers to insert an update call very specifically between one system or another!

Unity does an `Update`, `LateUpdate`, `OnPreRender` etc. kind of callback system, which I've been trying to avoid. Having an `ISystem` that could specify what its dependencies are would be a lot clearer and less error prone!

SK's system manager just needs an update to allow dynamic insertions to its list, and a decent C# API for it.

**Comment by austinbhale** [comment]
Keeping system calls purposeful across platforms sounds much better! Looking forward to seeing how this C# API develops
