### ISSUE TITLE
Passthrough for Rift S

### ISSUE THREAD

**Issue by hwhite-eng** [StereoKit/StereoKit#573]
Passthrough for Rift S

I have the FBpassthrough stepper but it doesn't seem to work for Rift.
Is this intended or is there support for pass through on Rift?

**Comment by maluoi** [comment]
I've never owned a Rift S, so I don't exactly have firsthand experience here. If Rift S has passthrough in the OS shell, I'd expect it to work in StereoKit as well! :) You may need to enable it though, Oculus keeps these as "beta" features on PC.

![image](https://user-images.githubusercontent.com/8484884/212800062-9c4608b7-eb73-4158-bdef-851a30762834.png)

**Comment by HarrisonBT** [comment]
Nope, Rift S doesn't have that setting in the oculus application.
I'll double check I have all the required libraries .

**Comment by hwhite-eng** [comment]
Is there now support for Rift S pass through?

Thanks,
H

**Comment by maluoi** [comment]
I don't know! I still don't have a Rift S. If the Rift S doesn't have the switch for it, then it might not.

If Rift S does support it, it should work with StereoKit. If you have additional details that suggest passthrough should be available but something is wrong, please provide those details and re-open the issue :)
