### ISSUE TITLE
I can't get UI.PanelAt() to work. Docs are meaningless.

### ISSUE THREAD

**Issue by Chris-Tophski** [StereoKit/StereoKit#585]
Hi, I'm using HoloLens 2 and I was trying to figure out how your layout routines work etc., mostly successfully. Now, I've tried UI.PanelAt() and couldn't get it to work. I was able to draw an empty panel, but I either couldn't place buttons and such in it or the app just crashed. Unfortunately, the docs on this function don't tell me anything interesting, no example, no hint on its intended use, no reference to UI.PanelEnd() or how it might be related to UI.PanelBegin(), no clarification of why there is a 3D vector for positioning and no information about its context in a window. Is this just a bug or am I missing something? Could you please clarify and/or update your docs/framework?

What I tried so far:

````
Pose pose = new Pose(); // more complex than this, but working, never mind
UI.WindowBegin("My Window", ref pose, new Vec2(0.6f, 0.4f);
// I don't seem to be allowed to do PanelEnd() after a PanelAt()
UI.PanelAt(new Vec3(0.1f), new Vec2(0.1f)); // just for simplicity, changes have no effect
UI.Button("test 1");
// putting PanelBegin() before PanelAt() didn't change anything as well
UI.PanelBegin();
UI.Button("test 2");
UI.PanelEnd();
UI.WindowEnd();
````

There I see the buttons on the window, where ``test 2`` is just placed without a panel, ``test 1`` is placed inside the panel defined by ``UI.PanelBegin()`` just as expected and there is another panel without buttons. How do I put ``test 1`` into the latter panel?

**Comment by maluoi** [comment]
The `UI.---At` functions are intended for completely manual layout of UI elements, so it's probably best to avoid them unless you're working with the `UI.Layout---` functions! The Layout functions will give you the correct vectors and sizes needed for `UI.PanelAt`. A `UI.PanelAt` does not work with a `UI.PanelEnd`, as all its sizing info is provided up-front, and it doesn't need to know its contents.

However, you likely just want to use `UI.PanelBegin` and `UI.PanelEnd`! Basic usage is to call `UI.PanelBegin()`, do the UI you want inside the panel, then call `UI.PanelEnd()`.

So, just this:
```csharp
UI.WindowBegin("My Window", ref pose, new Vec2(0.6f, 0.4f);
{
    UI.PanelBegin();
    {
        UI.Button("test 1");
        UI.Button("test 2");
    }
    UI.PanelEnd();
}
UI.WindowEnd();
```

Sorry about the docs drifting a bit there, v1.0 is coming soon, and it's been a long update! Docs are frozen to the v0.3.6 build.

**Comment by Chris-Tophski** [comment]
I see, thanks for the reply. The ``PanelBegin()``/``PanelEnd()`` stuff is straightforward, though, but it isn't enough, so I had a look at ``PanelAt()``. So, I guess I'm looking forward to upcoming versions of this very great framework. Is there any resource to read about details of manual layout meanwhile?

**Comment by maluoi** [comment]
There's some rather fresh layout hierarchy functionality you might be interested in! New as of v0.3.7-preview.8 and no real samples, but should be fairly straightforward from the tests:

Check out the code for the window alll the way to the right here
https://github.com/StereoKit/StereoKit/blob/develop/Examples/StereoKitTest/Demos/DemoUITearsheet.cs#L130
![StereoKitTearsheet](https://user-images.githubusercontent.com/8484884/215701698-c86b87aa-5e18-464f-8825-5ab98871ac82.png)

This is the code for a small asset browser
https://github.com/StereoKit/StereoKit/blob/develop/Examples/StereoKitTest/Demos/DemoAssets.cs#L41
![TinyAssetBrowser](https://user-images.githubusercontent.com/8484884/215701950-17ba4ece-58c6-41d9-b678-4876e459a005.jpg)

And these are some of the helper functions for working with the layout system. Looks like I don't really have much in the way of code using them up in C#, but they're the foundation for just about all the UI auto-layout, so they're used a lot in the core C code. Many of them have only recently been added to the preview builds, so there's commentdocs, but don't show up in the site docs yet.
- [UI.LayoutReserve](https://stereokit.net/Pages/StereoKit/UI/LayoutReserve.html)
- [UI.LayoutRemaining](https://github.com/StereoKit/StereoKit/blob/c17f476d8b68bec7fb2918011831a70b8ff863d9/StereoKit/Systems/UI.cs#L55)
- [UI.LayoutAt](https://github.com/StereoKit/StereoKit/blob/c17f476d8b68bec7fb2918011831a70b8ff863d9/StereoKit/Systems/UI.cs#L62)
- [UI.LayoutLast](https://github.com/StereoKit/StereoKit/blob/c17f476d8b68bec7fb2918011831a70b8ff863d9/StereoKit/Systems/UI.cs#L67)

**Comment by Chris-Tophski** [comment]
Excellent, thanks a lot. I've had a quick look at this and there is quite a lot of what I was looking for. I'll have a deeper dive into that later. So for now, this issue is done in my view.
