### ISSUE TITLE
Desktop project targeting win10-x64 picks up UAP native DLLs instead of Desktop ones

### ISSUE THREAD

**Issue by dfields-msft** [StereoKit/StereoKit#586]
## Description
I have a Desktop (i.e. non-UWP) project (happens to be MAUI) which builds for win10-x64. It seems that the StereoKit nuget package places UWP-compatible binaries in the runtimes/native/win10-x64 folder, and Desktop-compatible binaries in the runtimes/native/win-64 folder. Since my project is using the more specific win10-x64 RID (which is the default for MAUI), it picks up the wrong binaries and fails to run. It seems that nuget supports a proper way to provide Desktop/UWP variants, per https://github.com/NuGet/Home/issues/2782. The layout would then be:

runtimes/win-x64/native/StereoKitC.dll <-- desktop binary goes here
runtimes/win10-x64/nativeassets/uap10.0/StereoKitC.dll <-- UWP binary goes here

## Platform / Environment
Running on Windows, consuming from a MAUI project, building AnyCPU, which defaults to setting RuntimeIdentifier to win10-x64.

**Comment by maluoi** [comment]
Oh thanks a bunch for bringing this up! I remember searching high and low for the most correct spot to put the binaries for this, but never quite stumbled across _that_ format! I'll definitely give this a spin.

I did think I had introduced a bit of a hack-ey fix for this somewhat recently though. Is this on /develop, or with the recent preview.8 build, or are you using something else?

**Comment by dfields-msft** [comment]
I'm currently on 0.3.6 - sorry, should have included that in the bug report! I can try bleeding edge and see if it works any better...

**Comment by dfields-msft** [comment]
Tried 0.3.7-preview.8 and got the same result; UWP binary is copied in from win10-x64 folder and fails to load.

**Comment by maluoi** [comment]
Yeah, the hack was that it'd copy the Win32 version overtop the UWP one later on in the build. It was working nicely for a while, but I'm not seeing that functioning properly right now either!

I'm investigating the whole setup right now, the `nativeassets` folder seems to be working great with regular UWP! But there's still some bits with Maui Windows that seem like they were borked even before. I'll try and have it fixed soon!

**Comment by maluoi** [comment]
Okay, these changes went into preview.9! I also updated [the Maui template](https://github.com/StereoKit/StereoKit.Templates) to behave better with this stuff out-of-the-box :) I hope it helps!

**Comment by dfields-msft** [comment]
I tried out preview.9 and it's working great for me; both MAUI and UWP projects are happy! Thanks for the quick fix!

**Comment by maluoi** [comment]
Faaantastic! Glad it worked out :) Thanks so much for that tip too!
