### ISSUE TITLE
Menu autosize causes menu to grow horizontally, SK 0.3.7 preview 9

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#593]
## Description
I have a simple menu that is designed to add or remove button components at runtime. I use the autosize capability of the menu to accomplish this. In SK 0.3.7 preview 7 and prior preview editions as did prior versions of SK all behaved as documented. I moved to preview 9 yesterday and did a clean/rebuild. On the first run my main menu immediately began growing and quickly was too big for me to push any button.
I rolled back to preview 7 (clean/rebuild) and the menu returned to normal autosizing behavior.

## Platform / Environment
Windows 11 .NET 6.0 SK 0.3.7 preview 9 (previously on preview 7) Using SK holographic remoting to the HoloLens 2 Remoting client.

## Logs or exception details
No exceptions seen.
```
Logs are super helpful, please include them if they're at all relevant!
```
_If you have an exception, details about that would also be essential._

**Comment by maluoi** [comment]
I believe I fixed this one over here: https://github.com/StereoKit/StereoKit/commit/4903fdda6f9d101c11a06f04c5162f800ba9fa53, which will be in the next preview build! I'm planning to have another preview build up in a few days.

This one popped up particularly with the `HolographicTheme`, and was related to the recent addition of the `margin` `UISettings` property. A temporary fix would also be to set the `padding` and `gutter` to the same size!
