### ISSUE TITLE
LastElementFocused reports incorrect states for overlapping handles

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#599]
## Description
If you have two overlapping handles, StereoKit intelligently works out which one will be grabbed. If you tell the handle to draw itself (for debugging), the handle is highlighted so you can see which of them is in focus and will therefore be grabbed. This works perfectly.

If I want to show a UIBox or otherwise highlight the handle only when it's grabbable, I expect "UI.LastElementFocused.IsActive()" should allow me to achieve this, but this returns all handles that are overlapped rather than the one which is in focus and ready to be grabbed.

![skTest](https://user-images.githubusercontent.com/10079865/221842409-aa7f528c-a8e9-46be-9f66-29527454666d.png)

## Sample code

```
using StereoKit;

SK.Initialize();


Pose p1 = Pose.Identity;
Pose p2 = Pose.Identity;

SK.Run(()=>{
    // Move the handles around so they overlap. Then move hand so it overlaps both handles. 
    // Both handles will claim they are in focus but only one will be grabbed
    UI.Handle("p1", ref p1, new Bounds(V.XYZ(.5f, .5f, .5f)), true);      
    if (UI.LastElementFocused.IsActive())
        Mesh.Cube.Draw(Material.UIBox, Matrix.TRS(p1.position, p1.orientation, V.XYZ(.52f, .52f, .52f)));

    UI.Handle("p2", ref p2, new Bounds(V.XYZ(.25f, .25f, .25f)), true);
    if (UI.LastElementFocused.IsActive())
        Mesh.Cube.Draw(Material.UIBox, Matrix.TRS(p2.position, p2.orientation, V.XYZ(.27f, .27f, .27f)));
});


```

**Comment by maluoi** [comment]
Sneaky issue! But I found a fix that should work quite well :)

I did notice that in the simulator, the left hand seems to be focusing objects even when it's not tracked at all. You can see this when your handles are sitting around the origin (where the untracked left hand defaults to). I'll look into this a bit as well.

**Comment by maluoi** [comment]
I don't remember this one terribly well, but whatever I added should be in now. Please feel free to re-open this one if there's anything still happening related to this!
