### ISSUE TITLE
Can you make input box activation work the same as button activation?

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#600]
## Describe the feature
Currently, input boxes are activated when your finger enters a volume, This means they can be activated by moving your finger from behind the window to in front of it. This leads to accidental activation and the virtual keyboard popping up when not required. I experience this when I press a button that changes the window and there now happens to be an input box where my finger is still situated. I have an easy work around for this where I call UI.PushEnable(false) for .25 seconds to give the user time to retract their finger after the button press, but ideally that wouldn't be required.

Preferably, activating the input box would invisibly work like a button, requiring that forward finger action. This is a low priority due to having a work around, but I thought a big enough niggle to mention.

Thanks.

**Comment by maluoi** [comment]
Thanks for bringing this one up! I didn't realize this was still using old volume code, should be fixed in the next build, I'll try to do another one of those quite soon here :)

**Comment by maluoi** [comment]
This should be in now!
