### ISSUE TITLE
Debounce inputs

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#607]
## Description
I have fielded a solution using SK with customers. Customers are reporting "multiple" button pushes. I've been testing this to see what is really happening. I am seeing multiple detections on the same button or sliders. It appears that HL2 is losing its detection (using remoting) of the finger as the user is in the act of pressing or releasing a button. Sliders just buzz with multiple hits.
The documentation says it fires only on the first detection. It seems that there needs to be some amount of "debouncing" of the hit for buttons. For sliders it seems to be more complicated "Fitts Law". The person is trying to move the slider while at the same time trying to look at an object that is changing (color, size, position, etc.).
This may be also related to sensitivity to the finger location. The HL2 seems to detect a pinch when a user is just moving their hands in the air making objects move or click un-commanded. The auto-grab is the worst of the overly sensitive actions. It takes the slightest movement and the object jumps to you hand.

## Platform / Environment
Windows 11 SK holographic remoting. SK 0.3.7 preview 9. HoloLens 2 22H1 (current as of today)

## Logs or exception details
```No exceptions reported
Logs are super helpful, please include them if they're at all relevant!
```
_If you have an exception, details about that would also be essential._

**Comment by maluoi** [comment]
It sounds like you may have some duplicate UI ids in your scene? When two UI elements share the same id, they often behave a little strange, as interacting with one will also affect the other. The buzz you're hearing in particular is a give-away that this is happening :)

This page talks about it a little more, and shows a strategy for working in cases where the id is, or may be the same as another.
https://stereokit.net/Pages/Guides/User-Interface.html#an-important-note-about-ids

UI ids are hierarchical, and inherit the ids above it in the hierarchy. So the id for a button on a window would be `"Window Title/Button Text"`. `UI.Push/PopId` allows you to add to the hierarchy and create more uniqueness in the ids :)

**Comment by laultman** [comment]
That's awesome info. I did not realize the hierarchy. That explains a couple other thing as well - nagging miss-match window end at odd times. Does the hierarchy get updated on each call to Step or Update? When is it established?
Can you address the problem I'm having with the auto-grab, don't know what it's really called, but it's the hand-laser-grab/pinch that brings the object origin to your fingertip. Sometimes I want to ignore the action on some objects.

**Comment by maluoi** [comment]
The hierarchy is built during any hierarchy related calls that involve an id! This is either explicitly with calls to `UI.Push/PopId`, or more implicitly with `UI.WindowBegin/End` or `UI.HandleBegin/End`. As with all push/pop and begin/end code, every push must be matched with a pop, and every begin should be matched with an end. The hierarchy should be empty at the end of the frame, and start again in the next frame.

The grab interaction you're seeing is controlled by [`UI.EnableFarInteract`](https://stereokit.net/Pages/StereoKit/UI/EnableFarInteract.html). You can set it to false before your UI element that shouldn't use this, and set it back to true afterwards.

**Comment by laultman** [comment]
Thanks Nick! Somehow, I figured it was there, I don't think you have missed much, if anything. SK is an awesome tool.

**Comment by laultman** [comment]
A few questions around the Step method, frames. Time and determinism. The documentation seems to indicate that there really is only **ONE** step loop and that all UI objects added via AddStepper get called each frame. This would seem to say that a Frame-time is a variable length (non-deterministic) quantity?
SK Time is or seems to be based on system clock time?
If the above is true, then the more "things" added to the Step cause progressively longer frame time spans thereby reducing the frames per second?
However, in one of my demo apps I have "components" each implemented as IStepper. One of those plays a "flipper" video and uses ssml audio. I have multiple components and they all seem to behave as if each is its own Step.
I am trying to understand the concept and limitations of Step. Why would I use the concept of an Update method if Step is called on each frame for each component that is implemented? Could you explain how the Step is implemented?

**Comment by maluoi** [comment]
I replied to this one as a Discussion over here! :) https://github.com/StereoKit/StereoKit/discussions/614
