### ISSUE TITLE
Cannot move the plane aroud 

### ISSUE THREAD

**Issue by camroo29** [StereoKit/StereoKit#609]
I am using a plane model. But I can't interact with it.
              
Yeah, the generated plane is currently XZ only in model space. You can use `Matrix` transforms to compensate for this without too much trouble, here's a quick example:

```CSharp
Model planeModel = new Model();
planeModel.AddSubset(
	Mesh.GeneratePlane(Vec2.One), 
	Material.Default,
	Matrix.R(Quat.FromAngles(-90,0,0)));

UI.Handle("planeHandle", ref meshPose, planeModel.Bounds, false);
planeModel.Draw(meshPose.ToMatrix());
```

I use `Model` here instead of a `Mesh`, largely because the `Model` will properly recalculate the `Bounds` taking into consideration the subset's transform. If Bounds aren't a concern, you can also mix Matrices like this:

`planeModel.Draw(Matrix.R(Quat.FromAngles(-90, 0, 0)) * meshPose.ToMatrix());`

You might also be interested in the [default quad mesh](https://stereokit.net/Pages/Reference/Default/MeshQuad.html), which I often use for occasions that require facing behavior! This is a pre-defined mesh without a generator, but it can be scaled nicely, and faces Forward by default, making it pretty versatile and re-usable.

_Originally posted by @maluoi in https://github.com/StereoKit/StereoKit/issues/169#issuecomment-874478438_

**Comment by maluoi** [comment]
Hmm, a plane/quad may actually not be the best for using with a `Handle`. SK's `Handle` will actually disable itself if the bounds are infinitely thin! That may not actually be all that intuitive of a behavior, so I'll think about that a bit, maybe change that in the future.

Two easy solution here would be: use a cube and make it thin (not flat), or add some additional size to the Bounds you pass along to Handle.

**Comment by camroo29** [comment]
Thanks man!
