### ISSUE TITLE
Deploying Fails SK Demo to HoloLens 2 Instructions Out of Date

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#610]
## Description
Trying to deploy the current 0.3.7 - preview 9 downloaded just now to HoloLens 2. I am using VS 2022 17.5.3. The SK code builds with no issues. I can't seem to get it to connect to my PC/VS to deploy. VS issues Error. Would appreciate some updated instructions on how to deploy to HL2 from VS2022 on Windows 11.

## Platform / Environment
Window 11, VS 2022, StereoKit out of the box. Configured VS for Release, ARM64, Selected Remote (Device as shown in the VS 2019) video does not work.

## Logs or exception details
3>------ Deploy started: Project: StereoKitTest_UWP, Configuration: Release ARM64 ------
3>Error: Unable to connect to the Microsoft Visual Studio Remote Debugger named '192.168.1.23'.  The Visual Studio 2022 Remote Debugger (MSVSMON.EXE) does not appear to be running on the remote computer. This may be because a firewall is preventing communication to the remote computer. Please see Help for assistance on configuring remote debugging.
========== Build: 2 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Build started at 8:18 PM and took 43.572 seconds ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
========== Deploy started at 8:18 PM and took 43.572 seconds ==========

Logs are super helpful, please include them if they're at all relevant!
```
_If you have an exception, details about that would also be essential._

**Comment by maluoi** [comment]
This is an intermittent issue with UWP that I've run into on occasions, and is not specific to StereoKit as far as I know (I believe people have had this issue with Unity as well). I'm honestly not too sure what exactly the root problem here is, though I have searched plenty!

The only thing I've been able to do to get around this is to change from running on `Device` to `Remote Machine`? You might also try visa versa if `Remote Machine` isn't working for you.

**Comment by laultman** [comment]
I tried, the Device first. I switched to the Remote Machine. It asked me for the IP address which I put into the dialog. I guess I will reboot :)

**Comment by laultman** [comment]
I switched to USB to deploy using Device. I had to install the optional USB Connectivity option in the UWP section of the VS Installer.
You might find this interesting, It seems that OpenCV is causing an issue deploying.
https://learn.microsoft.com/en-us/answers/questions/1095805/cant-deploy-uwp-apps-to-hololens-2?orderBy=Helpful

**Comment by laultman** [comment]
I did get it to deploy using the USB method. Also, I sent an email to you Nick directly because here didn't seem to be the right place to discuss non-bug or feature issues, fundamentals, etc.

**Comment by maluoi** [comment]
Great! I'll check that out as well :)

**Comment by jackdaus** [comment]
I was having a similar issue deploying to HoloLens 2 today, and following along with the advice from the link you provided solved my issue, thanks @laultman!

Just to reiterate those points in case someone finds this thread:
1. If you are deploying via `device`, you need to download a Visual Studio component called `USB Device Connectivity`
2. If you are deploying via `remote machine`, you should manually enter the IP address of the HoloLens. (Also, make sure you're on the same wifi network!)

**Comment by austinbhale** [comment]
For the remote machine option, you can also deploy to the HL2 local IP when plugged in via a cable and achieve the same speeds as deploying to a device! (I do this when Device doesn't work)

**Comment by jackdaus** [comment]
> For the remote machine option, you can also deploy to the HL2 local IP when plugged in via a cable and achieve the same speeds as deploying to a device! (I do this when Device doesn't work)

Oh thanks for this tip! I'll keep this in mind if/when the `device` option starts acting up.
