### ISSUE TITLE
StereoKit calls xrDestroySpace with null handle

### ISSUE THREAD

**Issue by Wallbraker** [StereoKit/StereoKit#640]
## Description

I noticed in the log that when shutting down Monado gives the following errors:

```txt
XR_ERROR_HANDLE_INVALID: xrDestroySpace(space == NULL)
XR_ERROR_HANDLE_INVALID: xrDestroySpace(space == NULL)
```

Runtimes are not expected to do null checking on handles, so this is pretty bad.

## Platform / Environment

Ubuntu 22.04 - Monado Git - NorthStar

## Logs or exception details

[stereokit.log](https://github.com/StereoKit/StereoKit/files/11565068/stereokit.log)

**Comment by maluoi** [comment]
This should be fixed now in 0.3.7-preview.1570! Please let me know if it ends up popping up again for whatever reason :)
