### ISSUE TITLE
Virus is in dev branch

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#648]
I downloaded the StereorKit dev branch. While building it Windows Defender detected a virus.

![Virus-screen shot](https://github.com/StereoKit/StereoKit/assets/20271666/f80d7017-70c1-47fa-be69-bb977e9525d4)

**Comment by laultman** [comment]
Just as a note. I first unzipped the code and opened the solution in VS 2022. I dropped all the Android components. I built the solution but had two errors in the configuration related to the maui project and the Android components. Since it was otherwise unmodified I tried to delete the entire unzipped folder. I could not delete the zip created folder. After a reboot it deleted.
I then unzipped the code again and this time did nothing to the solution, just ran the build. That is when the Windows Defender detected the virus.

**Comment by maluoi** [comment]
These files are generated by cmake when compiling a specific tag of the [OpenXR Loader](https://github.com/KhronosGroup/OpenXR-SDK/tree/release-1.0.24), so none of the relevant files are in SK itself. SK will first attempt to invoke the system's cmake, and if none is present, then use Visual Studio's copy of cmake. Based on the postfix in your version number, it looks like you may be using Visual Studio's copy of cmake.

I've scanned my own copy of this file, and Defender gives it a clean bill of health, but I'm using an official build of cmake 3.26.3. My primary guess is that this is a false positive? Use of the temp folder like this helps me a lot for build/clone times with multiple copies of StereoKit, but I could imagine this behavior looking odd to an antivirus. I may consider moving it back into the SK repository folder, I don't do a whole lot with multiple SK copies, so I won't mind the overhead too much.

I'm open to other possibilities, but nothing is jumping out at me.

**Comment by laultman** [comment]
Better safe than sorry when it comes to a computer virus. If I install CMake will the build find it? This is my backup dev computer and I don't think it has the official CMake on it.

**Comment by laultman** [comment]
@maluoi Rather long discussion. I am trying to do this so I can solve my actual problem detailed below.

I loaded the latest CMake on my computer. I scanned my entire computer and removed the virus (phantom or not). I deleted the folder where I had unzipped the SK project. I created a new unzipped folder. I opened the solution in VS2022 and upgraded the project to latest version for Windows 11/VS2022. In configuration manager I unselected the Android project and the Maui projects.
With CMake now installed I ran the build. I did not get a virus hit, but it will not build on my computer. I have included an output build dump. There are lots of errors (58). This is always frustrating to me. I know probably 95% of the people using SK just use the nuget package, I know I have because it is a pain to get it to build locally.
The only reason I am attempting this is because I can't get SK to work in a remoting environment where SK is in a server mode. When the remoting app is closed in the HoloLens 2 (same as X'ing out of a Window), SK.Run() shuts down and terminates. This action causes a network disconnect event in OpenXR. The Microsoft OXR extension then detects the entry into Disconnected state and closes the session and then stops listening for new connections.
What happens in the official sample application is slightly different. The sample has a Win32 app similar to the way SK remoting is effectively the Win32 app. The difference is the sample app does not close the window so the Microsoft extension does not stop listening. I am trying to find a way to not exit the SK.Run() on the close/network disconnect when in the "listen" mode i.e. Server mode.
The user can close the app from the HoloLens 2 main menu by hitting the "Home" button which is effectively the UWP app's X (close). It simply terminates the network connection, no grace here. The remoting HL2 App is unaware of the SK app running on the remoting device. It is entirely up to the server side what should be done on the disconnect event. I am trying to make SK aware of its role as a "server" to detect the three events from the Microsoft OXR extension: disconnected, connecting, connected. I need to handle the SK exit command by not shutting down SK but showing the user a main menu, with possible instructions on how to "end" the app using the HL2 main menu.

**Comment by laultman** [comment]
@maluoi trying not to give up on this. I got on my regular development machine that did have CMake on it and I updated it to a current version. I followed the same procedure as before with the same result. CMake will not build on a basically out of the box Windows 11 and Visual Studio 2022. There are so many errors that I really don't know where to begin.

**Comment by maluoi** [comment]
It's possible maybe something from earlier caused corrupted in your build folder? I think the `"Cannot open compiler generated file"` and `unable to unlink old` issues at the start may be the big clues. I might try nuking the `C:/Temp/StereoKitBuild` folder and trying again.

Building SK itself will always be trickier that using the NuGet, unfortunately. Cross platform development for C++ is rough, and VS makes it worse by having no idea what dependencies are. I have been working a _lot_ on the build system recently in preparation for CI/CD on GitHub Actions, so the next update may help make things a little smoother.

Regarding the functionality you're trying to solve, I don't know if OpenXR really has a good way to intercept and deny an exit event? I might recommend [taking a peek over here](https://github.com/StereoKit/StereoKit/blob/develop/StereoKitC/xr_backends/openxr.cpp#L730) though, where SK receives OpenXR's events. It does look like there could be some wiggle room for trying a few things.

**Comment by laultman** [comment]
@maluoi I did finally get a build on my regular dev box. Undoubtedly there is a difference between the machines. My dev box has been building C++ and SK since SK ver 0.3.0. It may have accumulated some hidden gems through the years that my backup machine does not have. I did update my old CMake to the most recent stable release on this machine.
I took a shot of my configuration so you can see what is getting built and of my solution in VS so you can see the projects. I have not modified anything except to upgrade to the VS Windows 11 SDK that VS offers when it first loads.
![SK-VS-config](https://github.com/StereoKit/StereoKit/assets/20271666/e7711f4b-fb9c-4a5b-a7b9-8876df7531ea)
