### ISSUE TITLE
Need to process OpenXR events received via xrPollEvent

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#650]
## Describe the feature
Many of the Oculus OpenXR extensions submit an asynchronous request and then use the xrPollEvent to detect and retrieve the data when it is ready. While I can execute xrPollEvent via OpenXR extensions, StereoKit is already calling it and discarding the events it isn't interested in, meaning I never get them.

Can we either register callbacks for events we want to be notified of or have a queue we can read from to detect and process events.

I expect this is a common model for asynchronous operations so will be useful for non-Oculus uses too.

Thank you.

**Comment by maluoi** [comment]
v0.3.7-preview.6 added `Backend.OpenXR.OnPollEvent`, which should let you tap into OpenXR's events! You'll get all events this way, including the ones that StereoKit has already reacted to.

**Comment by Jumbli** [comment]
Thanks. I've given it a try and am getting the events through. Sorry I missed it.
