### ISSUE TITLE
Appears to be an architecture mismatch problem in the StereoKitTest_UWP

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#711]
Visual Studio 2022 throws an error building the StereoKitTest_UWP app in Release/ARM64 configuration. The error (see below) is complaining about AMD64 architecture. I have no idea where AMD64 comes from. This has been happening at least since preview 1739. I use this configuration to build for HoloLens 2. Note: a solution wide text search for AMD64 does not find any reference.

In my setup, I downloaded a fresh copy of the StereoKit project. I opened the solution in VS. I removed all the projects related to linux and android because I am targeting HoloLens 2. I modified the StereoKit.csproj file to comment out all references to linux and android. I don't have those workloads installed in VS. I have found that if I build just the StereoKitC project as a debug and release version that I avoid multiple builds because it is always X64. It also has the advantage of avoiding a failure in the physics lib build evidently due to a latency in the build (this could be specific to my machine's processing speed or lack thereof.)
I then build the StereoKitC_UWP in debug and release in X64, ARM64, and AnyCPU configurations.
Next, I repeat this process for StereoKit project. At this point there should be no need to recompile the core projects.

With the core projects now built I set my configuration to target only the StereoKitTest and StereoKitTest_UWP with the latter set as the default startup project. I set the solution configuration to Release ARM64 and Remote Machine. Additionally, I have experimented with other configurations with all projects selected with the same result.

Dev Configuration:
Windows 11 current, VS2022 current, StereoKit 0.3.7 preview 1779 (also appeared in 1739, 1751)

## Logs or exception details
```
Severity	
Code	
Description	
Error		There was a mismatch between the processor architecture of the project being built "" and the processor architecture of the reference "C:\Users\me\source\SK-preview1779\bin\netstandard2.0\StereoKit.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	
Project	StateStereoKitTest_UWP	
File	
Line	Suppression 		
```

![Screenshot 2023-08-26 073925](https://github.com/StereoKit/StereoKit/assets/20271666/1a29fb57-26eb-47e4-aba7-7c2f505d88f0)

**Comment by laultman** [comment]
Problem solved. I am trying to exclude Linux and Android because I am targeting HoloLens 2 development and I don't have the VS2022 component workloads installed on this development machine. To do this I am commenting out the inclusion of those platforms. I also will never target the ARM (32) processor type because HoloLens 2 is ARM64.

However, something in the build make file tries to build ARM even if I comment out the specific lines in the StereoKit C# project. Leaving the ARM processor type in the build solves the issue. No big loss here.

For those who may want to do as I, here is the modified part of the StereoKit.csproj file:
`
	
	<ItemGroup>
		<None Pack="true" Visible="false" Include="../tools/img/StereoKitLogo64.png" PackagePath="images/" />

		<Content Pack="true" Visible="false" Include="../bin/netstandard2.0/StereoKit.pdb" PackagePath="lib/netstandard2.0/" />
		
		
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/Win32/x64/Release/StereoKitC.dll" PackagePath="runtimes/win-x64/native/" Condition="Exists('../bin/distribute/bin/Win32/x64/Release/StereoKitC.dll')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/Win32/x64/Release/StereoKitC.pdb" PackagePath="runtimes/win-x64/native/" Condition="Exists('../bin/distribute/bin/Win32/x64/Release/StereoKitC.pdb')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/Win32/ARM64/Release/StereoKitC.dll" PackagePath="runtimes/win-arm64/native/" Condition="Exists('../bin/distribute/bin/Win32/ARM64/Release/StereoKitC.dll')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/Win32/ARM64/Release/StereoKitC.pdb" PackagePath="runtimes/win-arm64/native/" Condition="Exists('../bin/distribute/bin/Win32/ARM64/Release/StereoKitC.pdb')" />

		
		
		
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/UWP/x64/Release/StereoKitC.dll" PackagePath="runtimes/win10-x64/nativeassets/uap10.0/" Condition="Exists('../bin/distribute/bin/UWP/x64/Release/StereoKitC.dll')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/UWP/x64/Release/StereoKitC.pdb" PackagePath="runtimes/win10-x64/nativeassets/uap10.0/" Condition="Exists('../bin/distribute/bin/UWP/x64/Release/StereoKitC.pdb')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/UWP/ARM64/Release/StereoKitC.dll" PackagePath="runtimes/win10-arm64/nativeassets/uap10.0/" Condition="Exists('../bin/distribute/bin/UWP/ARM64/Release/StereoKitC.dll')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/UWP/ARM64/Release/StereoKitC.pdb" PackagePath="runtimes/win10-arm64/nativeassets/uap10.0/" Condition="Exists('../bin/distribute/bin/UWP/ARM64/Release/StereoKitC.pdb')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/UWP/ARM/Release/StereoKitC.dll" PackagePath="runtimes/win10-arm/nativeassets/uap10.0/" Condition="Exists('../bin/distribute/bin/UWP/ARM/Release/StereoKitC.dll')" />
		<Content Pack="true" Visible="false" Include="../bin/distribute/bin/UWP/ARM/Release/StereoKitC.pdb" PackagePath="runtimes/win10-arm/nativeassets/uap10.0/" Condition="Exists('../bin/distribute/bin/UWP/ARM/Release/StereoKitC.pdb')" />

		
		<Content Pack="true" Visible="false" Include="../tools/skshaderc.exe" PackagePath="tools/" />
		<Content Pack="true" Visible="false" Include="../tools/skshaderc" PackagePath="tools/" />
		<Content Pack="true" Visible="false" Include="../tools/include/*.*" PackagePath="tools/include/" />

		
		<Content Pack="true" Include="StereoKit.targets" PackagePath="build/" />
		<Content Pack="true" Include="StereoKit.props" PackagePath="build/" />
		<Content Pack="true" Include="SKAssets.targets" PackagePath="build/" />
		<Content Pack="true" Include="SKShaders.targets" PackagePath="build/" />
		<Content Pack="true" Include="SKMaui.targets" PackagePath="build/" />
		<Content Pack="true" Include="SKShader.xml" PackagePath="build/" />
	</ItemGroup>

	
	<Target Name="SKErrPlatformFiles" AfterTargets="BeforeBuild" BeforeTargets="CoreBuild" Condition="'$(GeneratePackageOnBuild)'=='true' and '$(SKIgnoreMissingBinaries)' != 'true'">
		<Error Condition="!Exists('../bin/distribute/bin/Win32/x64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing Win32 x64 binaries." />
		<Error Condition="!Exists('../bin/distribute/bin/Win32/ARM64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing Win32 ARM64 binaries." />
		
		<Error Condition="!Exists('../bin/distribute/bin/UWP/x64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing UWP x64 binaries." />
		<Error Condition="!Exists('../bin/distribute/bin/UWP/ARM64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing UWP ARM64 binaries." />
		<Error Condition="!Exists('../bin/distribute/bin/UWP/ARM/Release/StereoKitC.dll')" Text="[SK NuGet] Missing UWP ARM binaries." />

	</Target>
	<Target Name="SKWarnPlatformFiles" AfterTargets="BeforeBuild" BeforeTargets="CoreBuild" Condition="'$(GeneratePackageOnBuild)'=='true'">
		<Warning Condition="!Exists('../bin/distribute/bin/Win32/x64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing Win32 x64 binaries." />
		<Warning Condition="!Exists('../bin/distribute/bin/Win32/ARM64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing Win32 ARM64 binaries." />
		
		<Warning Condition="!Exists('../bin/distribute/bin/UWP/x64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing UWP x64 binaries." />
		<Warning Condition="!Exists('../bin/distribute/bin/UWP/ARM64/Release/StereoKitC.dll')" Text="[SK NuGet] Missing UWP ARM64 binaries." />
		<Warning Condition="!Exists('../bin/distribute/bin/UWP/ARM/Release/StereoKitC.dll')" Text="[SK NuGet] Missing UWP ARM binaries." />
		
	</Target>
</Project>
`

**Comment by maluoi** [comment]
FYI, HoloLens2 does run ARM just fine, and is a useful short-circuit for a number of features. Among other things, HL2 has an actual .NET runtime for ARM, which it does not have for ARM64. This means ARM64 apps on HL2 are always compiled via .NET Native, which takes extra time. ARM allows you to skip the .NET Native compile step, and get faster build times.

**Comment by laultman** [comment]
Thanks, for the info! That kind of information is the stuff I want to know about - gems hidden in the docs. What we know we must do is to create lots of "applets" that customers can just "use, as-is" for the type of business they're in. Much the same as a they would expect of a PC. Thanks Nick, I really appreciate the work.
