### ISSUE TITLE
Origin.Floor - not reacting to resetting view / position

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#715]
## Description
Using OriginMode.Local, you can reset the view on Quest and the game world is realigned as expected.

If you use OriginMode.Floor on Android / Quest, the position / orientation is correct when you start the app, but nothing happens when you reset the view. I would expect it to be updated to correct itself as per on app startup.

**Comment by maluoi** [comment]
Thanks for catching this one! Easy enough fix once I knew it was there, should be in tomorrow's build!

**Comment by Jumbli** [comment]
Seems to be working well. Thanks ;)
