### ISSUE TITLE
bug: FlatscreenWindow position code is overridden by Registry on startup

### ISSUE THREAD

**Issue by Strepto** [StereoKit/StereoKit#724]
https://github.com/StereoKit/StereoKit/blob/f8905b1f8745424a012f4c9d24e6ef28434b0dd3/StereoKitC/platforms/win32.cpp#L226-L236

If the window for the simulator has ever been moved the registry code will overwrite the target window position.

Note: What I would really like is for the stored window position to be on a per window basis, maybe based on appName or a custom window ID or similar?

User Story: As a multiplayer developer I want to be able to open multiple separate stereokit windows in diffent spots on my screen to be able to quickly iterate multiplayer sessions. Currently I need to manually move the windows each time I restart the app as all windows start at the position of the last closed StereoKit window.

PS: 
If this takes some time to fix and anyone else for any strange reason needs this fixed. This works as a workaround to move the window after StereoKit starts:
```cs
    [DllImport("user32.dll", SetLastError = true)]
    internal static extern bool MoveWindow(IntPtr hWnd, int X, int Y, int nWidth, int nHeight, bool bRepaint);

    public void Init()
    {
        MoveWindow(Process.GetCurrentProcess().MainWindowHandle, Settings.flatscreenPosX, Settings.flatscreenPosY, Settings.flatscreenWidth, Settings.flatscreenWidth, true);
        // snip
```

**Comment by maluoi** [comment]
Fix is inbound, this will work as expected for when SKSettings has specified any window positioning/sizing info! Will be in tomorrow's build.

Per-window may be nice, but I did actually choose not to do this intentionally! So I guess I'd probably enjoy some feedback on this thought:

> Since the Simulator is a development tool, keeping the simulator in the same location for all apps in development would be helpful for a dev arranging their windows. Especially if that dev works on more than one SK app.

**Comment by Strepto** [comment]
> Since the Simulator is a development tool, keeping the simulator in the same location for all apps in development would be helpful for a dev arranging their windows. Especially if that dev works on more than one SK app.

Not sure if I agree that different apps debug windows should appear at the same space. But as you say, its a debug help thing so I'm ok with leaving this complexity for us us edge-case users

**Comment by maluoi** [comment]
Yeah okay, I do see where you're coming from! I'm going leave this with the current fix, and let this marinate in my mind for a while and see what comes out of it. I still have some more code to do with the windows recovery feature in the near future, so may be more opportunities to improve it yet :)
