### ISSUE TITLE
model_node_info_get() crash if the key value do not exist in the dictionary_t

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#736]
## Description
Using the rust binding, the program is crashing when searching an info key value that do not exist in the node properties.

## Platform / Environment
Linux ubuntu 23.04 /OpenXR runtime 1.0.20 with the flatscreen simulator / Rust binding on the "develop" branch of Stereokit

## Logs or exception details
Sorry, I only have the ASM debug trace.

**Comment by maluoi** [comment]
Thanks for the report! This is now fixed on /develop, but you may need to ping @technobaboo to get this in the rust bindings.

**Comment by mvvvv** [comment]
Thanks, it's ok I'm already worrking on the develop branch. I've sent them somme PR.

**Comment by mvvvv** [comment]
Hi, badly I have a new error when the key is not present in the dictionary_t : 

'''Stop reason: signal SIGSEGV: invalid address (fault address: 0x0)'''

it works well if the key exists.

**Comment by maluoi** [comment]
If the key does _not_ exist, then `model_node_info_get` will return `null`. I do have a test checking this, and it seems to be working fine in my code. I'm a little fuzzy on rust, but it does kinda look like you're checking this here as well? I can't read it well enough to verify this code for correctness. If you're confident on your null check, I'd love a little more context about the model node info setup, to see if it's something more situational.
