### ISSUE TITLE
Mesh does not render (draw) all the faces.

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#738]
## Description
I am using the Mesh to create procedurally a mesh and then adding the vertices and indices to the mesh. I do not understand why the generate cube mesh method works and a procedurally generated one does not.
I ended up using the Cube.GetVerts to extract the default Mesh.Cube vertices. I know that it draws a cube just fine. But not when I try to create the mesh using the extracted vertices.
I tried making each side a different color so that I could tell what is being drawn. The draw method draws only one triangle for each side of the cube. Stranger still all faces of the triangles face the inside of the cube (color is on the inside) except the face that is facing forward when the mesh is created.

I have attached a file that has just the failing code to draw the cube (should anyway). I use a simple test app with holographic remoting to simply add the file to the StereoKit using the SK.AddStepper method. To test, I used the SK template for Visual Studio. I added the file in the attached zip to the project. I added the holographic remoting so I could test rapidly locally and with HoloLens 2.

Any help in understanding why the mesh behaves at it does, is greatly appreciated.

## Platform / Environment
Windows 11 using remoting and HoloLens2 latest build. Visual Studio Enterprise latest version, StereoKit 0.3.8 version.

[MeshCube.zip](https://github.com/StereoKit/StereoKit/files/12841231/MeshCube.zip)

**Comment by laultman** [comment]
@maluoi This is likely more a documentation issue than a code issue. I have struggled for a couple days now trying to figure out how to draw a cube using a mesh with the colors on the faces. My goal is to create complex shapes where complex is an odd-shaped object from a point cloud with vector data. The point data contains all edges to all other points.

**Comment by laultman** [comment]
@maluoi I kept reading and found that most descriptions of mesh diagramming kept referring to the particular render engine design. I had used the Mesh.GetVerts method so I used the Mesh.GetInds method to get the indices of the Mesh.Cube. With pencil and paper, I sketched out the cube and all the verts. I then created a connection flow for each side. Turns out to be fairly simple.
Think of it as a stack of paper squares where the edge closest to you is the bottom. The 0 corner is the left bottom corner and the 1 corner it the bottom right. The top left is number 2 and the top right is number 3. The winding flow then is left 0->right 1 then up 3. Then start back at left 0 -> across to right 3 then from right 3 -> left top 2. Repeat this flow for all sides.

Now that I can see the flow, I can image a number of arrangements.

**Comment by maluoi** [comment]
Sounds like one thing you might be missing here is that the winding order of your indices is important to how culling works! For example:

```
Defining a triangle as:
0 1 2

Is different from defining it as:
2 1 0
```

Here, these triangle definitions face in different directions. StereoKit uses a counter-clockwise order to mean "forward" facing, meanin that if the vertex order looks counter-clockwise from your position, it's facing towards you, and if it looks clockwise, then it's facing away from you.

You can set the Material's FaceCull property to flip how this behaves on a per-material basis as well. By default, StereoKit culls back facing triangles.
