### ISSUE TITLE
UI.Text() no longer handling newlines?

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#744]
## Description

I just started testing with a Quest 3, developing on Linux with the new templates. Really cool that that now allows a non-windows dev workflow for Android/Quest! 

I override the Log function and gather all messages in a List. This then gets turned into a single string, by combining each line with a `\n` in between. And finally display the single string with `UI.Text()`. Something like this:

```
    List<string> log_lines;
    string log_text;
    LogLevel log_level = LogLevel.Info;

    log_lines = new List<string>();
    Log.Subscribe(OnLog);

    void OnLog(LogLevel level, string text)
    {
        string time = DateTime.Now.ToString("HH:mm:ss.fff");

        // Max number of lines shown
        if (log_lines.Count > 50)
            log_lines.RemoveAt(0);
        
        text = $"{time} {text}";
        // XXX newline not working in UI.Text() as it used to?
        log_lines.Add(text.Length < 120 ? text : text.Substring(0, 120) + "...\n");
        //log_lines.Add(text);

        log_text = "";
        for (int i = 0; i < log_lines.Count; i++)
            log_text += log_lines[i];
    }

    // UI draw
    UI.WindowBegin("Log", ref log_window_pose, new Vec2(80, 0) * U.cm, UIWin.Normal);
    UI.Text(log_text);
    UI.WindowEnd();
```

This used to work in another project, but with my small testing thingy the newlines are not printed. Here's a screenshot from the simulator, a new line should start at each timestamp:

![image](https://github.com/StereoKit/StereoKit/assets/1408287/324c7146-5140-43d9-9094-a42edac62ab7)

## Platform / Environment

0.3.8, sk-multi template, Linux host. Android 13.0 SDK.

In the simulator (`dotnet run`) the line behaviour is the same, i.e. no newlines.

**Comment by maluoi** [comment]
I think this may have actually been a small behavior change in the log strings! (shame on me, I know, but it's an improvement, I promise) Previously, they came with their own `\n` postfix in the string, in addition to a `[SK log_level]` prefix. I removed both of those for more control over how the log gets displayed, so you're probably relying on the `\n` that was there previously. I can see you're only adding a `\n` in the case of shortening the string, but not elsewhere.

You might also be interested in the log viewer I built recently! It does log coloring, de-duplication, as well as scrolling. No filtering though, though probably not too too hard to add:
https://github.com/StereoKit/StereoKit/blob/master/Examples/StereoKitTest/Tools/LogWindow.cs

**Comment by paulmelis** [comment]
Good spot on the `\n` only being added by me on long strings. Adding the newline always fixes it, thanks :)

The log window is indeed interesting, will need to see about integrating it.

**Comment by paulmelis** [comment]
Somewhat related: I just integrated your LogWindow code and can see it works in the simulator with `dotnet run`. Building the APK works as well, and so does deploying (commands from the getting started guide). Yet, the app I see on the Quest is not updated. And I've had this multiple times now when making changes, but can't figure out how to force an update. Even deleting the app on the Quest and redeploying doesn't help. Any ideas?

**Comment by maluoi** [comment]
Haha, no worries :)

I believe I remember something where Release mode apps unfortunately don't install over eachother when they have the same version number? I believe it _should_ be calling that out when you run the adb install command, so you'd probably notice that if it's happening. An uninstall/reinstall _should_ work 100%, but I haven't been doing this enough to have a better/nicer solution off the top of my head.
