### ISSUE TITLE
SK is blank after the first frame when running MRC on HL2

### ISSUE THREAD

**Issue by austinbhale** [StereoKit/StereoKit#750]
## Description
Hey Nick, I found a pretty niche issue when launching an SK app while streaming MRC on the HL2. Reporting here since this would occur when customers want to stream the application for other people to see.

To reproduce,
1) Start Mixed Reality Capture from the Device Portal with `Render from Camera` enabled
2) Launch StereoKit app (latest dev)

Important Notes:
* MRC and `Render from Camera` works with an already running SK app
* The SK app renders for the first frame, then everything disappears and SK continues to step without rendering anything
* I couldn't reproduce this behavior with MSFT's [BasicXrApp](https://github.com/microsoft/OpenXR-MixedReality/blob/main/samples/BasicXrApp/OpenXrProgram.cpp), which leads me to believe this might be SK-related

## Platform / Environment
- UWP HoloLens 2
- Latest develop

## Logs or exception details
The initialization is successful and there is nothing notable to report from the logs. 
```
[SK diagnostic] Creating view: PrimaryStereo color:bgra32_sRGB depth:depth16 blend:Additive
[SK diagnostic] Set view: PrimaryStereo to 1440x936@1msaa
[SK diagnostic] Creating view: SecondaryMonoFPO_Msft color:bgra32_sRGB depth:depth16 blend:Alpha Blend
[SK diagnostic] Created unbounded app space at an offset of (0.0025,0.00017,-0.00034) (0,-0.0089,0,1)
[SK info] Initialization successful
```

After the first step, the following error repeats for [xrAcquireSwapchainImage](https://github.com/StereoKit/StereoKit/blob/6549a6cd9fb8a9168e7d70d1e98b0014601d0815/StereoKitC/xr_backends/openxr_view.cpp#L801) (throws [here](https://github.com/KhronosGroup/OpenXR-SDK/blob/55224479ab13db8ebc8ab1e3d49197bce6201b0b/src/loader/xr_generated_loader.cpp#L351)):
```
ERROR (OpenXR) : Invalid XrSwapchain handle with value 'XR_NULL_HANDLE'.
Exception thrown at 0x76BF56FF in SKApp.UWP.exe: Microsoft C++ exception: msxr::XrResultException at memory location 0x0470E6B0.
ERROR (OpenXR) : Invalid XrSwapchain handle with value 'XR_NULL_HANDLE'.
Exception thrown at 0x76BF56FF in SKApp.UWP.exe: Microsoft C++ exception: msxr::XrResultException at memory location 0x0470E6B0.
```

I'm wondering if there is anything else I could check for differences between the two apps?

Also, the OpenXR app defaults to `XR_ENVIRONMENT_BLEND_MODE_ADDITIVE` and the color & depth swapchains seem similar to SK:

![image](https://github.com/StereoKit/StereoKit/assets/32556981/f6f88c9b-66d2-45a8-aedd-a83bee045be7)

**Comment by austinbhale** [comment]
In the latest \develop branch after the backend refactoring, the HL2 is unable to stream or record video while running StereoKit.

The exception is "Access violation reading ..." when calling `xrEndFrame`. When the secondary view is active (HL2 is recording), it successfully renders a frame once, but for the second frame it throws the exception. 

I was able to find a workaround by doing the following:
1. If the camera is recording before the SK app initializes, the secondary view config is active. Since we assume [it starts as inactive](https://github.com/StereoKit/StereoKit/blob/092d717609425b8f9cb0bc4be00a3c53c91f2b32/StereoKitC/xr_backends/openxr_view.cpp#L310), the swapchain doesn't get updated.
![image](https://github.com/StereoKit/StereoKit/assets/32556981/54bdacd9-1557-4bba-8343-6d87bfdcbb23)
2. Commenting out the XR extension
![image](https://github.com/StereoKit/StereoKit/assets/32556981/53937fdd-58be-4def-821d-b31921aed040)

I can't wrap my ahead around it since the lifetime of the `XrSecondaryViewConfigurationFrameEndInfoMSFT` and `XrSecondaryViewConfigurationLayerInfoMSFT` should still be alive for `xrEndFrame` to have them in the header. The bytes and offset arrays seem to be valid for the header. I've also tried disabling the color swapchain's surface and reverting back to the non-list approach of `xr_display_2nd_layers`. Is there any chance you might know what info to grab next?

**Comment by maluoi** [comment]
Off the top of my head, I can't really think of much! I skimmed it now and didn't see anything obvious. I don't believe that the xrEndFrame chain code gets used in this codebase except for this secondary view stuff, so it doesn't get much exercise!

I'll try and peek a little more tomorrow. Do you have any more info about the Access Violation error? Can you tell what bit is causing that? Is it actually the chained data?
