### ISSUE TITLE
UI.HandleEnd() Causes unhandled exception

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#761]
@maluoi Upgrading some older SK projects to SK latest version 0.3.8 release. Kept getting a hard crash at the SK.Run() method as an unhandled exception. The issue is isolated and reproducible.
The problem is the method UI.HandleEnd() causes the exception. Commenting the method call removes the error. The behavior is interesting in that a subsequent call to UI.HandleBegin() method in the same Step() seems to "close" the prior handlebegin call. The app works as expected in the second call to the UI.HandleBegin() method.

System configuration is Windows 11 current build and Visual Studio 2022 current build build. StereoKit version 0.3.8 release. Running VS in debug AnyCpu.

## Logs or exception details

![SK-error](https://github.com/StereoKit/StereoKit/assets/20271666/7b3d6818-d406-4c76-90b4-bbce893abf70)
![Sk-stacktrace](https://github.com/StereoKit/StereoKit/assets/20271666/6f264fd9-6a5d-42ac-919d-a86cccb376dc)
[SK-output.txt](https://github.com/StereoKit/StereoKit/files/13199144/SK-output.txt)

## A simple project to reproduce the error.

[RepoProject.zip](https://github.com/StereoKit/StereoKit/files/13199149/RepoProject.zip)

**Comment by laultman** [comment]
Update: I expanded the test. I modified one of the classes in the repo project to include a Window. In the window is a button that should draw a cube. It has the HandleEnd() method.
The code compiles and runs as long as the method is not called.

```
	public class CubeObj1 : IStepper
	{
		Matrix contentPose = Matrix.TR(0, -0.1f, -0.6f, Quat.LookDir(0, 0, 1));
		Pose testPose;
		Pose cubePose;
		Model cube;


		Pose cubePose1 = new Pose(.2f, 0, -0.5f, Quat.Identity);
		Model cube1 = Model.FromMesh(
			Mesh.GenerateRoundedCube(Vec3.One * 0.1f, 0.02f),
			Default.MaterialUI);

		Pose cubePose2 = new Pose(.2f, .1f, -0.5f, Quat.Identity);
		Model cube2 = Model.FromMesh(
			Mesh.GenerateRoundedCube(Vec3.One * 0.1f, 0.02f),
			Default.MaterialUI);

		public bool Enabled { get; }

		public bool Initialize()
		{
			testPose = (Matrix.T(0.1f, -.2f, 0) * contentPose).Pose;
			cubePose = new Pose(-0.2f, 0, -0.5f, Quat.Identity);
			cube = Model.FromMesh(
				Mesh.GenerateRoundedCube(Vec3.One * 0.1f, 0.02f),
				Default.MaterialUI);
			return true;
		}

		public void Step()
		{
			UI.Handle("Cube", ref cubePose, cube.Bounds);
			cube.Draw(cubePose.ToMatrix(), new Color(1, 0, 0));
			//UI.HandleEnd();	// ************************************ This causes the crash. Comment this line and it works.

			UI.WindowBegin("Cube", ref testPose);

			if (UI.Button("Error Maker"))
			{
				UI.Handle("Cube err", ref cubePose2, cube2.Bounds);
				cube2.Draw(cubePose2.ToMatrix(), new Color(0, 1, 1));
				UI.HandleEnd(); // ************************************ This causes a crash when clicked.
			}
			UI.WindowEnd();


			UI.Handle("Cube1", ref cubePose1, cube1.Bounds);
			cube1.Draw(cubePose1.ToMatrix(), new Color(0, 0, 1));
			//UI.HandleEnd();
		}

		public void Shutdown()
		{

		}
	}

```

**Comment by maluoi** [comment]
`UI.HandleEnd` should be used with `UI.HandleBegin`! If you're only using `UI.Handle`, then `UI.HandleEnd` is not needed, as it stands on its own and doesn't add anything to the hierarchy stack.

**Comment by laultman** [comment]
@maluoi That's clearly why you ask for full details! Code migration is a real bear. Funny how you can look at somethign for days and not see the answer. I even read the documentation half a dozen times. I did not catch the difference between the two!
Where the issue originated was the sample code had the UI.Handle (not UI.HandleBegin). I propagated the problem into my existing code with the infamous "cut-n-paste".
Thanks Nick as always.

**Comment by maluoi** [comment]
Yeah, I should still probably have better error messages for that situation at least! 😅  I think I may have had some that got lost in a refactor, I'll make a note to revisit that and make them work again!

**Comment by laultman** [comment]
@maluoi Cool! Got it working now. I had a bunch of places where it worked and a bunch more where I had pasted code that didn't. I just didn't see the difference. I think a simple comment in the docs of the similarity would have triggered me to check.
