### ISSUE TITLE
Varjo Hands in C# project 

### ISSUE THREAD

**Issue by JackRumboll** [StereoKit/StereoKit#763]
## Description

The Hand size on the Varjo XR-3 is too big. I know you fixed it in the C++ part of the project I just want to know if there is a way we can fix the size of the and for the Varjo?

**Comment by paulmelis** [comment]
Did you try `Backend.OpenXR.SetHandJointScale(float scale_factor)`?

**Comment by maluoi** [comment]
Yeah, this is an issue that Varjo has. @paulmelis's suggestion is the correct workaround for now.
 
For context, see this issue: https://github.com/StereoKit/StereoKit/issues/425

Do we know how aware Varjo is that this is an issue? I haven't filed a ticket with them myself yet.

**Comment by JackRumboll** [comment]
should I add that code to the step function or on initialization?

**Comment by maluoi** [comment]
Initialization

**Comment by JackRumboll** [comment]
okay I will give it a try and let you know if it works

**Comment by JackRumboll** [comment]
It worked thanks.
