### ISSUE TITLE
Eye tracking at all times.

### ISSUE THREAD

**Issue by JackRumboll** [StereoKit/StereoKit#764]
## Describe the feature
Can the eye tracking panel be set up to be fixed to the head so that you can always see where your eyes are even if you turn your head?

## An example use-case
For training purposes if you want to show someone where you are looking.

**Comment by maluoi** [comment]
Is this a request to change the behavior of [DemoEyes.cs](https://github.com/StereoKit/StereoKit/blob/master/Examples/StereoKitTest/Demos/DemoEyes.cs)? Or is this something else?

**Comment by JackRumboll** [comment]
it will be for That demo yes I'm using that as the base and just need a way to have the eye tracking follow my head so I can always see where my eyes are

**Comment by maluoi** [comment]
Try using something like this to position an object in front of the user each frame:

```csharp
Vec3 pos = Input.Head.position + Input.Head.Forward * 0.5f;
Quat rot = Quat.LookAt(pos, Input.Head.position);
Mesh.Quad.Draw(Material.Default, Matrix.TR(pos, rot));
```

**Comment by JackRumboll** [comment]
should I add it to the Plane code?

`Matrix quadPose = Matrix.S(0.4f) * Demo.contentPose;
		Plane  plane    = new Plane(quadPose * Vec3.Zero, quadPose.TransformNormal(Vec3.Forward));`
