### ISSUE TITLE
SetElementVisual doesn't allow modification of grab aura

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#792]
## Describe the feature
I'm excited to implement the grab aura and line pinch build, but it seems that it's not included in the SetElementVisual so I can't modify it to work with my custom theme. My theme has 2d windows and fixes alias issues for Quest so the aura is very jarring and the default is not suitable for my app. Can you please add support for SetElementVisual for it, or if not can you have the ability to disable the aura for now. It feels really nice to use by the way.

Thanks.

**Comment by maluoi** [comment]
I have a few notes on enabling/disabling the grab aura over here: https://github.com/StereoKit/StereoKit/pull/784

Looks like I did forget to surface the relevant UIVisual all the way up to C# though 😬 Easy fix, I'll add that today!

**Comment by Jumbli** [comment]
Great news :)
