### ISSUE TITLE
native call with bad function signature.

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#814]
## Description
Native render_screenshot_capture function  do not have texFormat parameter but CS code call it with this parameter.

## Platform / Environment
All for develop branch

## Logs or exception details
in Renderer.cs file : 
```
public static void Screenshot(ScreenshotCallback onScreenshot, Vec3 from, Vec3 at, int width, int height, float fieldOfViewDegrees = 90, TexFormat texFormat = TexFormat.Rgba32)
		{
			if (_renderCaptureCallbacks is null) _renderCaptureCallbacks = new Queue<RenderOnScreenshotCallback>();
			RenderOnScreenshotCallback renderCaptureCallback = (IntPtr dataPtr, int w, int h, IntPtr context) =>
			{
				onScreenshot.Invoke(dataPtr, w, h);
				_ = _renderCaptureCallbacks.Dequeue();
			};
			_renderCaptureCallbacks.Enqueue(renderCaptureCallback);
		}
```

**Comment by mvvvv** [comment]
The screenshot callback has a "context: *mut c_void" parameter but this parameter can't be sat when calling neither render_screenshot_capture nor render_screenshot_viewpoint. Should it be possible to have it as it's the only way to use closure in rust ?

Log.Subscribe and Input.Subscribe don't have this contex parameter at all. Could we have it for them too ?

**Comment by maluoi** [comment]
Yeah good catch, thanks! These should also have a context parameter as well. I'll take a look at Log.Subscribe and Input.Subscribe, see what I can do there.

**Comment by maluoi** [comment]
I'm skipping `Input.Subscribe` for now. I'll likely be deprecating and removing these functions pretty soon.

The rest are now in /develop though :)

**Comment by mvvvv** [comment]
Thanks, I can create my closure now.

Testing both functions with the simulator on linux, I have now the same deep error :

[sk_gpu] skg_tex_get_mip_contents_arr: eating a gl error from somewhere else: 1282

I tested with different texFormat and different parameters without any success .

![capture](https://github.com/StereoKit/StereoKit/assets/810124/3643f7d3-4ae9-4d88-872c-4570dc22a3b8)

**Comment by mvvvv** [comment]
This error is flooding the log and  I launch the screenshot only once.
