### ISSUE TITLE
[sk_gpu] skg_tex_get_mip_contents_arr: eating a gl error from somewhere else: 1282

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#825]
## Description
I thought it was an error that only occurred on the Linux simulator during screenshots, but this message floods the log every time we call tex_get_data_mip or tex_get_data. Both on the Linux simulator and  Quest 2.

## Platform / Environment
rust binding on : 
Ubuntu 23.10 - gnome wayland  / Meta Quest 2

## Logs or exception details
```
[sk_gpu] skg_tex_get_mip_contents_arr: eating a gl error from somewhere else: 1282
```
_If you have an exception, details about that would also be essential._

**Comment by mvvvv** [comment]
This happens on examples that worked perfectly well a few days ago

**Comment by maluoi** [comment]
I'll try and check this out soon. Any ideas what this is from? That error message indicates something upstream is not working properly, and is not an issue with `skg_tex_get_mip_contents_arr` itself.

Was this something that worked one day and then not the next, or was there a particular StereoKit commit where this started happening? Did you upgrade your OS, or add notable graphics features in your own code?

**Comment by mvvvv** [comment]
I can't be sure. I believe it's after Syncing from you repo. I also changed to the last ndk.

**Comment by mvvvv** [comment]
I'm still having this problem. But I found a  problem that can help I guess.

Previously I was able to set a texture r16 using the function text_set_colors.

Now I receive the following message :

**Comment by maluoi** [comment]
I added a test that can repro this on Linux, 17561515019caa0dce3f062cea2295795b75d191. I still need to chase down where this comes from though.

**Comment by maluoi** [comment]
This may actually be something related to the switch to GLES from OpenGL. `GL_R16F` seemed to work fine with a `ushort` in OpenGL, but may be out-of-spec for GLES. I might have to do a half-float conversion on the backend here? Still investigating.

**Comment by maluoi** [comment]
Alright, I put in a bunch of fixes related to texture formats! Looks like there was a good bit of mess related to GL 16 bpp textures, and that should be pretty cleaned up now :)

I did see that screenshots don't seem to be working right now on my WSL setup, so I'll look into that a bit as well. But overall, I think this should behave a bit better! Let me know if these changes fix anything for you :)

A note for rust bindings, this does change some values on the `tex_format_` enum.

**Comment by mvvvv** [comment]
It's better. tex_set_colors works fine with R16f

Renderer::screenshot do not flood the log any more.
On the Quest 2 : I only have this single line
StereoKit: [sk_gpu] skg_tex_get_mip_contents_arr: eating a gl error from somewhere else: 1282

On linux/simulator :  These 2 lines
`[SK error] [sk_gpu] API/ERROR - 0x1 - GL_INVALID_OPERATION in glBlitFramebuffer(destination samples must be 0)
[SK warning] [sk_gpu] skg_tex_get_mip_contents_arr: eating a gl error from somewhere else: 1282`

**Comment by mvvvv** [comment]
On linux it creates a file with the right size but nothing inside ( the tiles of transparent background only). On the quest I have no clue where it should create the file.

**Comment by maluoi** [comment]
Ok, cool! Thanks for that :) I think this PR should fix the screenshot issue now.

**Comment by mvvvv** [comment]
Yes !! Well done !
