### ISSUE TITLE
C# default values in stereokit_ui.h

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#839]
## Description
Lines 226 to 231 of stereokit_ui.h contain some C# default values that break the rust bindgen build.

## Platform / Environment
rust binding. Linux 23.10 gnome wayland

**Comment by mvvvv** [comment]
The old signature for these function is still used so :

**Comment by maluoi** [comment]
These default values were for C++, and default values in that format can trip up tools that parse the header as just plain C. It's wrapped in the correct macro now, so that should be good, but I'm uncertain what that error in `virtual_keyboard.cpp` comes from? Let me know if it still sticks around.

**Comment by mvvvv** [comment]
it works fine now. Thanks !
