### ISSUE TITLE
Texture from external sources

### ISSUE THREAD

**Issue by lostmsu** [StereoKit/StereoKit#86]
It would be nice to be able to mirror contents of a shared DXGI surface (such as ones provided by new screen capture APIs) into a render target-like texture.

Normally engines do it by exposing native pointer to the texture resource (and potentially a device too), so that users could call SharpDX or some other DX binding to do the copying manually.

**Comment by maluoi** [comment]
I do actually have a little bit of code for this on the native side of the library! At one point I implemented screen->texture for some experimentation with different styles of curving screens. They haven't made it up to C# yet and may be a bit limited in functionality, but this sounds like a great idea to work on a bit more!

My previous experiments were using a pretty old C API, so I'm curious if you have a link to a newer one, or a C# one I could use for reference?

**Comment by lostmsu** [comment]
Here's a set of fresh samples: https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/ScreenCapture

**Comment by maluoi** [comment]
Awesome, thanks! I'll definitely ref this when testing :)

**Comment by maluoi** [comment]
Reference from how Stardust is currently doing this:
https://github.com/StardustXR/stardust-xr/blob/dev/src/integrations/wayland/surface.cpp

**Comment by maluoi** [comment]
This is now live on NuGet in v0.3.6-preview.7! See `Tex.SetNativeSurface` as well as some of the new desktop duplication demos.
