### ISSUE TITLE
Unable to compile release version with ndk

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#970]
## Description
I'm unable to build the android release library  : 
`   /home/mv/android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-objcopy: error: '/home/mv/dvlt/abacaba/stereokit-rust/target/aarch64-linux-android/release/build/stereokit-rust-b8324bff3780670e/out/build/libStereoKitC.a(color.cpp.o)': The file was not recognized as a valid object file
  gmake[2]: *** [CMakeFiles/StereoKitC.dir/build.make:1471 : libStereoKitC.a] Erreur 1
  gmake[2]: *** Suppression du fichier « libStereoKitC.a »
  gmake[1]: *** [CMakeFiles/Makefile2:232 : CMakeFiles/StereoKitC.dir/all] Erreur 2
  gmake: *** [Makefile:136 : all] Erreur 2
  thread 'main' panicked at /home/mv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:`

This error seems due to debug parameters which are systematically added in CMakeList.txt lines 464-466

Knowing that the Release compilation for Linux passes without problem.
[build.make.txt](https://github.com/StereoKit/StereoKit/files/15065395/build.make.txt)

## Platform / Environment
rust binding. Linux 24.04 gnome wayland

**Comment by mvvvv** [comment]
Looking at the build.make produced. For Linux and Android I'm using the cmake v3.28.3 from the /usr/bin/cmake.
The differences are about the tools used  from the ndk (clang+ ... llvm-objcopy ...) or from linux (/usr/bin/c++ ... /usr/bin/objcopy ...)
I add the linux build.make to show you what are the diffences
[build.make.txt](https://github.com/StereoKit/StereoKit/files/15067300/build.make.txt)

**Comment by mvvvv** [comment]
I wonder if the ndk tools are more sensitive about these debug options which should not be in a release build script IMHO

**Comment by maluoi** [comment]
These lines? https://github.com/StereoKit/StereoKit/blob/a62695d87c392dc29c7bd009b6134d3d58d32d52/CMakeLists.txt#L464-L466

The only thing they're doing is stripping debug symbols out of the binary, and putting them in a separate file. I wanted to have debug symbols around for release, but not embedded in the release binaries. This shouldn't have any impact here. I do this in the official StereoKit Android builds from Linux in CI/CD, so this path definitely does work in the right environment. I'm mostly expecting that rust is doing something a bit differently here that's tripping the build up.

**Comment by mvvvv** [comment]
Maybe it's a ndk problem. I'll try older version tomorrow.

**Comment by maluoi** [comment]
I'd also definitely recommend trying to build straight from the presets, and see if they work. If they work, then the issue is not with the NDK, and if they don't work, then the issue is not with rust's invocation.

```
cmake --preset Android_Arm64_Release
cmake --build --preset Android_Arm64_Release
```

**Comment by mvvvv** [comment]
The build from the presets work. I will use them. Thanks.

**Comment by mvvvv** [comment]
After going through everything again to use the presets I came across the same error. At least now I know how to reproduce it. The problem comes from the need to produce a static library StereoKit/bin/intermediate/Linux_x64_Release/libStereoKitC.a
For this, using the presets, I configure with the following command `cmake --preset Linux_x64_Release -DSK_BUILD_SHARED_LIBS=OFF -DSK_BUILD_TESTS=OFF
cmake --build --preset Linux_x64_Release`

While the same command for Debug instead of Release works.

**Comment by mvvvv** [comment]
Android_Arm64_Debug compiles and Android_Arm64_Release does not. With the same error.

**Comment by maluoi** [comment]
Awesome, okay! I can reproduce this, I'll dig around with it and see what I can do to fix it :) Thanks!

**Comment by maluoi** [comment]
Okay, I'm still a little fuzzy on the details, but it looks like static libraries shouldn't be stripped. This is likely a step that should be done after a final executable is built instead? I've disabled stripping for static builds, and the cmake commands you've pointed out work great now. Lemme know if it fixes the issue in your context :)

**Comment by mvvvv** [comment]
Well done!! Everything compiles perfectly and works on Linux and Android. For the record, I cannot use the presets because it risks using several versions of LLvm and this prevents the use of this same static library. I therefore use the cmake-rs tool, the aim of which is to ensure that I use a compatible toolchain from what I understand.
