### ISSUE TITLE
Since #986 (and maybe v65 on quest) apps do not wakeup anymore.

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#991]
## Description
When you turn the headset off (power button) then turn it back on (power button again) the application does not restart. First black screen with 3 small dots then screen: "do you want to close the app or wait ?".

## Platform / Environment
rust binding. Linux 24.04 gnome wayland + Quest 2 v65 

## Logs or exception details
``` 
05-15 09:38:57.003 18443 18508 I VrApi   : FPS=72/72,Prd=34ms,Tear=0,Early=0,Stale=0,Stale2/5/10/max=0/0/0/0,VSnc=1,Lat=-1,Fov=0,CPU4/GPU=2/3,1171/490MHz,OC=FF,TA=0/0/70,SP=N/N/F,Mem=1353MHz,Free=1854MB,PLS=0,Temp=28.7C/0.0C,TW=1.58ms,App=8.49ms,GD=0.55ms,CPU&GPU=12.46ms,LCnt=2(DR72,LM2),GPU%=0.78,CPU%=0.20(W0.32),DSF=1.00,CFL=11.57/16.94,ICFLp95=14.78,LD=0,SF=1.50,LP=0,DVFS=0
05-15 09:38:57.598 18443 18443 I OpenXR  : nativeOnActivityPaused
05-15 09:38:57.598 18443 18443 D android_activity::act..: Pause: 0x7a673cf640
05-15 09:38:57.604 18443 18467 I OpenXR  : PostSessionStateChange: XR_SESSION_STATE_FOCUSED -> XR_SESSION_STATE_VISIBLE
05-15 09:38:57.606 18443 18467 I Deque   : AddEventToQueue called. eventInfo.type: 18, eventInfo.next: 1
05-15 09:38:57.606 18443 18467 I OpenXR  : PostSessionStateChange: XR_SESSION_STATE_VISIBLE -> XR_SESSION_STATE_SYNCHRONIZED
05-15 09:38:57.606 18443 18467 I Deque   : AddEventToQueue called. eventInfo.type: 18, eventInfo.next: 1
05-15 09:38:57.606 18443 18467 I OpenXR  : PostSessionStateChange: XR_SESSION_STATE_SYNCHRONIZED -> XR_SESSION_STATE_STOPPING
05-15 09:38:57.607 18443 18467 I Deque   : AddEventToQueue called. eventInfo.type: 18, eventInfo.next: 1
05-15 09:38:57.607 18443 18467 I OpenXR  : ------------ xrEndSession [start] -----------
05-15 09:38:57.607 18443 18467 I XrRuntimeUtils: XrRuntimeUtils::EndSession
05-15 09:38:57.662 18443 18467 I Sensor  : OSSDKTRACKING Shutdown tracking
05-15 09:38:57.662 18443 18467 I LogTimer: CPUTIME: VrRuntimeClient_EndSession took 41.2818 ms
05-15 09:38:57.663 18443 18467 I InputDeviceManager: ovrInputDeviceManager::~ovrInputDeviceManager
05-15 09:38:57.663 18443 18467 I OSHandDataQuerier: OSSDKTRACKING shutting down HandsTracker
05-15 09:38:57.663 18443 18467 I OSHandDataQuerier: OSSDKTRACKING shutting down HandsTracker
05-15 09:38:57.663 18443 18467 D OsSdk   : TrackingServiceConnection dtor
05-15 09:38:57.664 18443 18467 D OsSdk   : TrackingServiceConnection unregistered
05-15 09:38:57.664 18443 18467 I InputHooks_Internal: Disabling Native Input Hooks
05-15 09:38:57.673 18443 18507 I ClientInputThread_Internal: InputThreadRun ShutdownRequest received
05-15 09:38:57.674 18443 18467 I ClientInputTrackedKeyboardManager: TRACKEDKEYBOARD ClearTrackedObjectManager called on client
05-15 09:38:57.680 18443 18510 I FenceChecker: FenceChecker::MainLoop - ended
05-15 09:38:57.680 18443 18467 I VrRuntimeClient: PhaseSync Instance deleted
05-15 09:38:57.680 18443 18467 I OpenXR  : PostSessionStateChange: XR_SESSION_STATE_STOPPING -> XR_SESSION_STATE_IDLE
05-15 09:38:57.681 18443 18467 I Deque   : AddEventToQueue called. eventInfo.type: 18, eventInfo.next: 1
05-15 09:38:57.681 18443 18467 I OpenXR  : ------------ xrEndSession [end] -----------
05-15 09:38:57.681 18443 18467 I VrRuntimeClient: Client has gained focus.
05-15 09:38:57.693 18443 18443 D android_activity::act..: NativeWindowDestroyed: 0x7a673cf640 -- 0x7a48a74810
05-15 09:38:57.717 18443 18467 D StereoKit: Sleeping until OpenXR session wakes
05-15 09:38:57.718 18443 18467 W Telemetry: [OpenXR] Unsupported threadType; 2
05-15 09:39:00.950 18443 18467 I Deque   : AddEventToQueue called. eventInfo.type: 40, eventInfo.next: 1
05-15 09:39:00.950 18443 18467 D StereoKit: Created local floor app space at an offset of (0,0,0) (0,0,0,1)
05-15 09:39:00.950 18443 18467 D StereoKit: Bounds updated: 3.6x3.4 at (0.3,0,-2) (0,0.95,0,-0.3)
05-15 09:39:01.551 18443 18467 I VrRuntimeClient: Client has lost focus.
05-15 09:39:07.582 18443 18449 I inding_templat: Thread[3,tid=18449,WaitingInMainSignalCatcherLoop,Thread*=0x7a6726a400,peer=0x12f000d8,"Signal Catcher"]: reacting to signal 3
05-15 09:39:07.582 18443 18449 I inding_templat: 
05-15 09:39:07.729 18443 18449 I inding_templat: Wrote stack traces to tombstoned
```
Logs are super helpful, please include them if they're at all relevant!
```
_If you have an exception, details about that would also be essential._

**Comment by maluoi** [comment]
Hmmm, I'm unable to reproduce this one on my Quest 3 or Quest Pro! However, it is interesting that you're getting these ones while sleeping:

> 05-15 09:39:00.950 18443 18467 D StereoKit: Created local floor app space at an offset of (0,0,0) (0,0,0,1)
> 05-15 09:39:00.950 18443 18467 D StereoKit: Bounds updated: 3.6x3.4 at (0.3,0,-2) (0,0.95,0,-0.3)

I haven't seen these logs in my own tests, and it feels kinda weird to be receiving these with no session available.

Does this happen 100% of the time for you? And how about sleep duration, does this happen after a few seconds, or a few minutes or both? Are you moving the device to a new room while sleeping, causing it to relocate while waking? Etc.

**Comment by mvvvv** [comment]
Yep all the time with the 3 apk I'm working on.

```
05-15 18:58:31.572 10819 10824 I com.mv81.giza: Thread[4,tid=10824,WaitingInMainSignalCatcherLoop,Thread*=0x7a6732a000,peer=0x12ec07b0,"Signal Catcher"]: reacting to signal 3
05-15 18:58:31.572 10819 10824 I com.mv81.giza: 
05-15 18:58:32.468 10819 10824 I com.mv81.giza: Wrote stack traces to tombstoned
05-15 18:58:37.394 10819 10844 I Deque   : AddEventToQueue called. eventInfo.type: 40, eventInfo.next: 1
05-15 18:58:37.394 10819 10844 D StereoKit: Bounds updated: 3.6x3.4 at (-0.9,-2,-2) (0,0.82,0,-0.57)
05-15 18:58:37.494 10819 10844 I VrRuntimeClient: Client has lost focus.
05-15 18:58:37.644 10819 10844 I Deque   : AddEventToQueue called. eventInfo.type: 40, eventInfo.next: 1
05-15 18:58:37.645 10819 10844 D StereoKit: Bounds updated: 3.6x3.4 at (-0.9,-2,-2) (0,0.82,0,-0.57)
```

and nothing more.

I'm not 100% sure about when it starts.  But I can't believe I missed it in the last 10 days. If you don't have this problem I should check with previous commit.

**Comment by mvvvv** [comment]
My fault, It's not while the headset is sleeping but at its wake-up. Last log line before sleep is `Telemetry: [OpenXR] Unsupported threadType; 2`

Something new is v65 too.

**Comment by mvvvv** [comment]
I changed the title of this issue as #986 is indeed the cause and perhaps the new v65 on Quest but I can no longer verify this.

**Comment by mvvvv** [comment]
Hi ! I added some log and I wonder if the problem is not about gettid() function that return an odd value ( 28306)  when the thread id is 2.

The log I  have : 
`07-21 16:37:12.861 28283 28306 D StereoKit: Sleeping until OpenXR session wakes
07-21 16:37:12.861 28283 28306 W Telemetry: [OpenXR] Unsupported threadType; 2
07-21 16:37:12.861 28283 28306 E StereoKit: Sleeping thread failed [XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR] for gettid [28306]`

**Comment by mvvvv** [comment]
lol and now I see the thread id in the log.

**Comment by mvvvv** [comment]
I think I found the problem. When I abandoned ndk_glue for winit and android-activity, I had a hard time understanding how to initialize openxr which got stuck on XR_SESSION_STATE_IDLE. To make it progress it was necessary to purge the first Android events, at least until the first RedrawNeeded. 
https://github.com/mvvvv/StereoKit-rust/blob/2bfa9a812422a2b5b98db9979b5a4cc28cea151e/src/sk.rs#L618
Subsequently I purge the Android events at each start of Step and everything is fine. When you turn off the Quest it goes into XR_SESSION_STATE_IDLE state but I no longer have the possibility of purging the events and that's the tragedy.

I imagine ndk_glue or the C# version has a thread that purges Android events.

Would it be possible to have an option (like disableUnfocusedSleep or during compilation) to be able to manage in the Android event loop the moment when the headset goes then exits the AppFocus::Hidden state.

If so, it would be cool to also be able to access audio_pause() and audio_resume via stereokit.h

I'll take any good advice.

**Comment by maluoi** [comment]
Okay, that's interesting! So far I've generally had the Android event loop on a different thread from StereoKit, so this hasn't been an issue in my codebases.

I remember when I first started Android dev, I ran into the issues that clogging up the main Android thread can result in the OS shutting your app down really quickly, even a call to sk_init can pause long enough for the OS to kill it? Maybe I've mis-remembered how that works. C# Android isn't even structured in a way where you really have control over the main thread either, and I don't really know if C# even gives you the main thread or a UI thread.

I guess my suggestion would be to keep the android events on a different thread from SK, but I might be open to better changes. I'm not super keen on the idea of disabling the sleep behavior, as that seems like more of a backdoor than anything else. But I guess a lot of Android's lifecycle (like windows) seems to require some amount of backdooring :(

**Comment by mvvvv** [comment]
I think I have the right solution. I tried to avoid going through openxr_step_end by testing at the start of each step sk_app_focus() == AppFocus::Hidden. But obviously the transition to Hidden takes place later. If I had one more Step between switching to Hidden and going to sleep, I could manage waking up before going back to sk_step()

I'm talking about AppFocus::Hidden but it could be xr_session_state == XR_SESSION_STATE_IDLE or other.

Another advantage would be to give the user the means to prepare for sleep
- by leaving the sound of a night cricket for example to remind the user that he is on standby,
- for social networks, allow the possibility of changing the connection status,

and similarly a way to handle waking up (but this is already possible by testing changing sk_app_focus()

**Comment by mvvvv** [comment]
If I'm calling openxr_poll_events() at the end, I'm able to sleep until I receive a new redrawRequested
```
void openxr_step_begin() {

	if (xr_has_session)
		openxr_poll_actions();
	input_step();
	
	anchors_step_begin();
}

///////////////////////////////////////////

void openxr_step_end() {
	anchors_step_end();

	if (xr_has_session) { openxr_render_frame(); }
	else                { render_clear(); platform_sleep(33); }

	xr_extension_structs_clear();

	// If the OpenXR state is idling, the device is likely in some sort of
	// standby. Either way, the session isn't available, so there's little
	// point in stepping the application. Instead, we block the thread and
	// just poll OpenXR until we leave the state.
	//
	// This happens at the end of step_end so that the app still can receive a
	// message about the app going into a hidden state.
	if (xr_session_state == XR_SESSION_STATE_IDLE) {
		log_diagf("Sleeping again");
		openxr_poll_events();
	}
	if (xr_session_state == XR_SESSION_STATE_IDLE) {
		log_diagf("Sleeping until OpenXR session wakes");
#if defined(SK_OS_ANDROID)
		if (xr_ext.KHR_android_thread_settings == xr_ext_active) {
			xr_extensions.xrSetAndroidApplicationThreadKHR(xr_session, XR_ANDROID_THREAD_TYPE_APPLICATION_WORKER_KHR, gettid());
		}
#endif
		audio_pause();
		while (xr_session_state == XR_SESSION_STATE_IDLE) {
			platform_sleep(100);
			openxr_poll_events();
		}
		audio_resume();
#if defined(SK_OS_ANDROID)
		if (xr_ext.KHR_android_thread_settings == xr_ext_active) {
			xr_extensions.xrSetAndroidApplicationThreadKHR(xr_session, XR_ANDROID_THREAD_TYPE_RENDERER_MAIN_KHR, gettid());
		}
#endif
		log_diagf("Resuming from sleep");
	}
	openxr_poll_events();
}
```

**Comment by maluoi** [comment]
SK does do one step with `AppFocus.Hidden`! `openxr_step_begin` happens before the App's step, and `openxr_step_end` happens after, so it's in the correct state in-between. I did make sure this was the case because I do have behavior that happens before and after suspend on other projects.

**Comment by mvvvv** [comment]
You right. Now that I've made my own sleep management I can see AppFocus::Hidden.

Thanks a lot I believe I can close this bug. 
My log is almost perfect now
And I have nothing to complain.
